<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyEmails.templates.SupportManager.ticket_received_name'] = "Ticket Recebido";
$lang['AdminCompanyEmails.templates.SupportManager.ticket_received_desc'] = "Aviso enviado a um utilizador quando um ticket é recebido.";
$lang['AdminCompanyEmails.templates.SupportManager.ticket_updated_name'] = "Ticket Atualizado";
?>