<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminStaff.!success.staff_added'] = "O membro de Staff foi adicionado com sucesso.";
$lang['AdminStaff.!success.staff_updated'] = "O membro do staff foi atualizado com sucesso.";
$lang['AdminStaff.index.categorylink_addstaff'] = "Adicionar Equipa";
$lang['AdminStaff.index.heading_first_name'] = "Nome";
$lang['AdminStaff.index.heading_email'] = "Email";
$lang['AdminStaff.index.heading_options'] = "Opções";
$lang['AdminStaff.index.option_edit'] = "Editar";
$lang['AdminStaff.index.option_delete'] = "Apagar";
$lang['AdminStaff.add.boxtitle_addstaff'] = "Adicionar Staff";
$lang['AdminStaff.add.heading_schedule'] = "Calendário";
$lang['AdminStaff.add.heading_settings'] = "Definições";
$lang['AdminStaff.add.heading_departments'] = "Departamentos";
$lang['AdminStaff.add.field_staff_group_id'] = "Grupo da Staff";
$lang['AdminStaff.add.field_staff_id'] = "Membro da Equipa";
$lang['AdminStaff.add.heading_day'] = "Dia";
$lang['AdminStaff.add.heading_all_day'] = "Todo o Dia";
$lang['AdminStaff.add.heading_end_time'] = "Hora de Fim";
$lang['AdminStaff.add.text_assigneddepartments'] = "Departamentos Atribuídos";
$lang['AdminStaff.add.text_availabledepartments'] = "Departamentos Disponíveis";
$lang['AdminStaff.edit.heading_settings'] = "Definições";
$lang['AdminStaff.edit.heading_departments'] = "Departamentos";
$lang['AdminStaff.edit.heading_day'] = "Dia";
$lang['AdminStaff.edit.heading_all_day'] = "Todo o dia";
$lang['AdminStaff.edit.heading_end_time'] = "Hora de Fim";
$lang['AdminStaff.edit.ticket_emails'] = "Receber e-mails de ingresso";
$lang['AdminStaff.edit.text_assigneddepartments'] = "Departamentos Atribuídos";
$lang['AdminStaff.edit.text_availabledepartments'] = "Departamentos disponíveis";
$lang['AdminStaff.edit.field_editsubmit'] = "Editar Staff";
$lang['AdminStaff.staff.name'] = "%1\$s %2\$s"; // %1$s is the staff member's first name, %2$s is the staff member's last name
$lang['AdminStaff.schedule_list.heading_day'] = "Dia";
$lang['AdminStaff.schedule_list.heading_end_time'] = "Hora de Fim";
$lang['AdminStaff.schedule_list.heading_departments'] = "Departamentos";
$lang['AdminStaff.schedule_list.heading_department'] = "Departamento";
$lang['AdminStaff.schedule_list.heading_description'] = "Descrição";
$lang['AdminStaff.schedule_list.no_department_results'] = "Este membro da equipa não está associado a nenhum departamento.";
$lang['AdminStaff.text.no_time'] = "--";
$lang['AdminStaff.!tooltip.signature'] = "Insira uma assinatura para disponibilizá-la automaticamente ao responder aos tickets. A sintaxe do Markdown é suportada.";
$lang['AdminStaff.add.title'] = "Título";
$lang['AdminStaff.add.signature'] = "Assinatura";
$lang['AdminStaff.edit.title'] = "Título";
$lang['AdminStaff.edit.signature'] = "Assinatura";
?>