<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminResponses.!success.category_added'] = "A categoria %1\$s foi adicionada com sucesso."; // %1$s is the name of the category
$lang['AdminResponses.!success.category_updated'] = "A categoria %1\$s foi actualizada com sucesso."; // %1$s is the name of the category
$lang['AdminResponses.!success.category_deleted'] = "A categoria %1\$s foi apagada com sucesso."; // %1$s is the name of the category
$lang['AdminResponses.!success.response_added'] = "A resposta %1\$s foi adicionada com sucesso."; // %1$s is the name of the predefined response
$lang['AdminResponses.!success.response_updated'] = "A resposta %1\$s foi atualizada com sucesso."; // %1$s is the name of the predefined response
$lang['AdminResponses.!success.response_deleted'] = "A resposta %1\$s foi apagada com sucesso."; // %1$s is the name of the predefined response
$lang['AdminResponses.edit.page_title'] = "Gestão de Suporte > Editar Respostas Pré-definidas";
$lang['AdminResponses.editcategory.page_title'] = "Gestor de Suporte > Editar Categoria";
$lang['AdminResponses.!text.open_parenthesis'] = "(";
$lang['AdminResponses.!text.forward_slash'] = "/";
$lang['AdminResponses.!text.closed_parenthesis'] = ")";
$lang['AdminResponses.index.boxtitle_responses'] = "Respostas pré-definidas";
$lang['AdminResponses.index.add_response'] = "Adicionar Resposta Aqui";
$lang['AdminResponses.index.add_category'] = "Adicionar categoria aqui";
$lang['AdminResponses.index.text_up_level'] = "Subir um Nível";
$lang['AdminResponses.index.edit'] = "Editar";
$lang['AdminResponses.index.delete'] = "Apagar";
$lang['AdminResponses.add.field_name'] = "Nome";
$lang['AdminResponses.add.field_details'] = "Detalhes da Resposta";
$lang['AdminResponses.add.field_submit'] = "Criar Resposta";
$lang['AdminResponses.edit.field_name'] = "Nome";
$lang['AdminResponses.edit.field_submit'] = "Resposta de Atualização";
$lang['AdminResponses.addcategory.boxtitle_root'] = "Adicionar Categoria";
$lang['AdminResponses.addcategory.boxtitle_addcategory'] = "Adicionar Categoria à Categoria [%1\$s]"; // %1$s is the name of the parent category
$lang['AdminResponses.addcategory.field_name'] = "Nome";
$lang['AdminResponses.addcategory.field_submit'] = "Criar Categoria";
$lang['AdminResponses.editcategory.boxtitle_root'] = "Editar Categoria";
$lang['AdminResponses.editcategory.boxtitle_editcategory'] = "Atualizar Categoria";
$lang['AdminResponses.editcategory.field_name'] = "Nome";
$lang['AdminResponses.editcategory.field_submit'] = "Atualizar Categoria";
?>