<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminDepartments.!success.department_created'] = "O departamento %1\$s foi criado com sucesso."; // %1$s is the name of the department
$lang['AdminDepartments.!success.department_deleted'] = "O departamento %1\$s foi apagado com sucesso."; // %1$s is the name of the department
$lang['AdminDepartments.index.categorylink_adddepartment'] = "Adicione Departamento";
$lang['AdminDepartments.index.boxtitle_departments'] = "Departamentos";
$lang['AdminDepartments.index.heading_name'] = "Nome";
$lang['AdminDepartments.index.heading_description'] = "Descrição";
$lang['AdminDepartments.index.heading_email'] = "Email";
$lang['AdminDepartments.index.heading_options'] = "Opções";
$lang['AdminDepartments.index.option_edit'] = "Editar";
$lang['AdminDepartments.index.no_results'] = "Não existem departamentos.";
$lang['AdminDepartments.assigned_staff.heading_staff'] = "Equipa";
$lang['AdminDepartments.assigned_staff.no_results'] = "Não existe staff atribuído a este departamento.";
$lang['AdminDepartments.add.boxtitle_adddepartment'] = "Adicionar Departamento";
$lang['AdminDepartments.add.field_name'] = "Nome";
$lang['AdminDepartments.add.field_description'] = "Descrição";
$lang['AdminDepartments.add.field_email'] = "Email";
$lang['AdminDepartments.add.field_security'] = "Segurança";
$lang['AdminDepartments.add.field_mark_messages'] = "Marcar Mensagens como";
$lang['AdminDepartments.add.field_user'] = "Utilizador";
$lang['AdminDepartments.add.field_port'] = "Porta";
$lang['AdminDepartments.add.field_status'] = "Estado";
$lang['AdminDepartments.add.field_addsubmit'] = "Adicione Departamento";
$lang['AdminDepartments.edit.boxtitle_adddepartment'] = "Editar Departamento";
$lang['AdminDepartments.edit.field_name'] = "Nome";
$lang['AdminDepartments.edit.field_description'] = "Descrição";
$lang['AdminDepartments.edit.field_clients_only'] = "Permitir que só clientes possam abrir ou responder a tickets";
$lang['AdminDepartments.edit.field_email'] = "Email";
$lang['AdminDepartments.edit.field_default_priority'] = "Prioridade predefinida";
$lang['AdminDepartments.edit.field_security'] = "Segurança";
$lang['AdminDepartments.edit.field_box_name'] = "Nome da caixa";
$lang['AdminDepartments.edit.field_user'] = "Utilizador";
$lang['AdminDepartments.edit.field_port'] = "Porta";
$lang['AdminDepartments.edit.field_status'] = "Estado";
$lang['AdminDepartments.edit.field_addsubmit'] = "Editar Departamento";
$lang['AdminDepartments.!text.remove_response'] = "Remover";
?>