<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminKnowledgebase.!success.category_deleted'] = "A categoria foi apagada com sucesso.";
$lang['AdminKnowledgebase.!success.article_added'] = "O artigo foi criado com sucesso.";
$lang['AdminKnowledgebase.index.page_title'] = "Gestor de Suporte > Base de Conhecimento";
$lang['AdminKnowledgebase.add.page_title'] = "Gestor de Suporte > Base de Conhecimento > Adicionar Artigo";
$lang['AdminKnowledgebase.addcategory.page_title'] = "Gestor de Suporte > Base de Conhecimento > Adicionar Categoria";
$lang['AdminKnowledgebase.index.add_article'] = "Adicionar Artigo";
$lang['AdminKnowledgebase.index.add_category'] = "Adicionar Categoria";
$lang['AdminKnowledgebase.index.boxtitle_knowledgebase'] = "Base de Conhecimento";
$lang['AdminKnowledgebase.index.go_back'] = "Subir um nível";
$lang['AdminKnowledgebase.index.edit'] = "Editar";
$lang['AdminKnowledgebase.index.delete'] = "Apagar";
$lang['AdminKnowledgebase.modal.delete_article'] = "Tem a certeza de que quer apagar este artigo?";
$lang['AdminKnowledgebase.index.no_results'] = "Não existem categorias ou artigos nesta secção.";
$lang['AdminKnowledgebase.addcategory.boxtitle_addcategory'] = "Adicionar Categoria";
$lang['AdminKnowledgebase.addcategory.field_name'] = "Nome";
$lang['AdminKnowledgebase.addcategory.field_parent_id'] = "Categoria Pai";
$lang['AdminKnowledgebase.addcategory.field_description'] = "Descrição";
$lang['AdminKnowledgebase.addcategory.field_access'] = "Acessibilidade";
$lang['AdminKnowledgebase.addcategory.submit_add'] = "Criar Categoria";
$lang['AdminKnowledgebase.addcategory.submit_cancel'] = "Cancelar";
$lang['AdminKnowledgebase.editcategory.boxtitle_editcategory'] = "Atualizar Categoria";
$lang['AdminKnowledgebase.editcategory.field_name'] = "Nome";
$lang['AdminKnowledgebase.editcategory.field_parent_id'] = "Categoria Pai";
$lang['AdminKnowledgebase.editcategory.field_description'] = "Descrição";
$lang['AdminKnowledgebase.editcategory.field_access'] = "Acessibilidade";
$lang['AdminKnowledgebase.add.field_access'] = "Acessibilidade";
$lang['AdminKnowledgebase.add.field_categories'] = "Categoria";
$lang['AdminKnowledgebase.add.submit_add'] = "Criar Artigo";
$lang['AdminKnowledgebase.add.submit_cancel'] = "Cancelar";
$lang['AdminKnowledgebase.edit.boxtitle_edit'] = "Atualizar Artigo";
$lang['AdminKnowledgebase.edit.field_access'] = "Acessibilidade";
$lang['AdminKnowledgebase.edit.field_categories'] = "Categoria";
$lang['AdminKnowledgebase.edit.submit_edit'] = "Atualizar Artigo";
$lang['AdminKnowledgebase.edit.submit_cancel'] = "Cancelar";
$lang['AdminKnowledgebase.article_content.title'] = "Título";
$lang['AdminKnowledgebase.article_content.content_type'] = "Tipo de conteúdo";
$lang['AdminKnowledgebase.article_content.body'] = "Corpo";
$lang['AdminKnowledgebase.select.none'] = "-- Nenhum --";
$lang['AdminKnowledgebase.!text.open_enclosure'] = "(";
$lang['AdminKnowledgebase.!text.closed_enclosure'] = ")";
$lang['AdminKnowledgebase.!text.enclosure_separator'] = "/";
$lang['AdminKnowledgebase.!text.add_category'] = "Adicionar Categoria";
$lang['AdminKnowledgebase.!text.directory_separator'] = "/";
?>