<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminTickets.!success.ticket_created'] = "O ticket #%1\$s foi aberto com sucesso."; // %1$s is the ticket number
$lang['AdminTickets.!success.ticket_updated'] = "O ticket #%1\$s foi atualizado com sucesso."; // %1$s is the ticket number
$lang['AdminTickets.index.page_title'] = "Gestor de Suporte > Tickets";
$lang['AdminTickets.add.page_title'] = "Gestor de Suporte > Abrir Ticket";
$lang['AdminTickets.text.unassigned'] = "Não Atribuído";
$lang['AdminTickets.index.category_open'] = "Aberto";
$lang['AdminTickets.index.category_awaiting_reply'] = "À espera de resposta";
$lang['AdminTickets.index.category_in_progress'] = "Em Progresso";
$lang['AdminTickets.index.category_closed'] = "Fechado";
$lang['AdminTickets.index.categorylink_createticket'] = "Abrir Ticket";
$lang['AdminTickets.index.boxtitle_tickets'] = "Tickets";
$lang['AdminTickets.index.heading_priority'] = "Prioridade";
$lang['AdminTickets.index.heading_department_name'] = "Departamento";
$lang['AdminTickets.index.heading_summary'] = "Sumário";
$lang['AdminTickets.index.heading_last_reply_date'] = "Última Resposta";
$lang['AdminTickets.add.boxtitle_add'] = "Abrir Ticket";
$lang['AdminTickets.add.text_no_clients'] = "Nenhum cliente encontrado. Tente pesquisar novamente.";
$lang['AdminTickets.add.heading_summary'] = "Sumário";
$lang['AdminTickets.add.heading_client'] = "Cliente";
$lang['AdminTickets.add.heading_department'] = "Departamento";
$lang['AdminTickets.add.heading_staff_id'] = "Atribuído a";
$lang['AdminTickets.add.heading_priority'] = "Prioridade";
$lang['AdminTickets.add.heading_status'] = "Estado";
$lang['AdminTickets.add.field_attachments'] = "Anexos";
$lang['AdminTickets.add.field_details'] = "Detalhes";
$lang['AdminTickets.add.text_add_attachment'] = "Adicionar Anexo";
$lang['AdminTickets.add.field_addsubmit'] = "Abrir Ticket";
$lang['AdminTickets.reply.boxtitle_reply'] = "Ticket #%1\$s"; // %1$s is the ticket number
$lang['AdminTickets.reply.heading_summary'] = "Sumário";
$lang['AdminTickets.reply.heading_client'] = "Cliente";
$lang['AdminTickets.reply.heading_department'] = "Departamento";
$lang['AdminTickets.reply.heading_staff_id'] = "Atribuído a";
$lang['AdminTickets.reply.heading_status'] = "Estado";
$lang['AdminTickets.reply.heading_date_added'] = "Data de Abertura";
$lang['AdminTickets.reply.heading_reply'] = "Adicionar resposta";
$lang['AdminTickets.reply.field_note'] = "Nota";
$lang['AdminTickets.reply.field_attachments'] = "Anexos";
$lang['AdminTickets.reply.text_add_attachment'] = "Adicionar Anexo";
$lang['AdminTickets.reply.reply_date'] = "A %1\$s %2\$s %3\$s respondeu"; // %1$s is the ticket reply date, %2$s is the first name of the reply author, %3$s is the last name of the reply author
$lang['AdminTickets.reply.system'] = "Sistema";
$lang['AdminTickets.reply.staff_title'] = "Equipa de Apoio";
$lang['AdminTickets.client.category_open'] = "Abrir";
$lang['AdminTickets.client.category_awaiting_reply'] = "À Espera de Resposta";
$lang['AdminTickets.client.category_in_progress'] = "Em Progresso";
$lang['AdminTickets.client.category_closed'] = "Fechado";
$lang['AdminTickets.client.categorylink_createticket'] = "Abrir Ticket";
$lang['AdminTickets.client.heading_priority'] = "Prioridade";
$lang['AdminTickets.client.heading_department_name'] = "Departamento";
$lang['AdminTickets.client.heading_summary'] = "Sumário";
$lang['AdminTickets.client.heading_last_reply_date'] = "Última Resposta";
$lang['AdminTickets.client.no_results'] = "De momento não existem tickets com este estado.";
$lang['AdminTickets.search.boxtitle_tickets'] = "Procurar Tickets por \"%1\$s\""; // %1$s is the search criteria
$lang['AdminTickets.search.heading_priority'] = "Prioridade";
$lang['AdminTickets.search.heading_status'] = "Estado";
$lang['AdminTickets.search.heading_department_name'] = "Departamento";
$lang['AdminTickets.search.heading_last_reply_date'] = "Última Resposta";
$lang['AdminTickets.index.heading_assigned_staff'] = "Atribuído a";
$lang['AdminTickets.index.text_to_status'] = "Alterar para:";
$lang['AdminTickets.index.ticket_number_placeholder'] = "Número do Ticket";
$lang['AdminTickets.index.text_no_tickets'] = "Não foram encontrados bilhetes disponíveis. Tente pesquisar novamente.";
$lang['AdminTickets.index.ticket_name'] = "#%1\$s %2\$s %3\$s"; // %1$s is the ticket number, %2$s is the client's first name, %3$s is the client's last name
$lang['AdminTickets.index.ticket_email'] = "#%1\$s %2\$s"; // %1$s is the ticket number, %2$s is the client's email address
$lang['AdminTickets.reply.field_actionsubmit'] = "Ir";
$lang['AdminTickets.index.heading_client'] = "Cliente";
?>