<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientTickets.!success.ticket_updated'] = "O ticket #%1\$s foi atualizado com sucesso."; // %1$s is the ticket number
$lang['ClientTickets.!success.ticket_closed'] = "O Ticket #%1\$s foi fechado com sucesso."; // %1$s is the ticket number
$lang['ClientTickets.!notice.no_departments'] = "Não existem departamentos de suporte disponíveis.";
$lang['ClientTickets.index.page_title'] = "Suporte > Tickets";
$lang['ClientTickets.add.page_title'] = "Suporte > Abrir Ticket";
$lang['ClientTickets.reply.page_title'] = "Suporte > Actualizar Ticket";
$lang['ClientTickets.index.category_open'] = "Aberto";
$lang['ClientTickets.index.category_closed'] = "Fechado";
$lang['ClientTickets.index.categorylink_createticket'] = "Pedido Aberto";
$lang['ClientTickets.index.boxtitle_tickets'] = "Tickets";
$lang['ClientTickets.index.heading_priority'] = "Prioridade";
$lang['ClientTickets.index.heading_last_reply_date'] = "Última Resposta";
$lang['ClientTickets.index.heading_status'] = "Estado";
$lang['ClientTickets.index.heading_options'] = "Opções";
$lang['ClientTickets.index.option_close'] = "Fechado";
$lang['ClientTickets.add.text_add_attachment'] = "Juntar anexo";
$lang['ClientTickets.index.no_results'] = "Atualmente não existem tickets com este estado.";
$lang['ClientTickets.index.confirm_close'] = "Tem a certeza de que quer fechar este ticket?";
$lang['ClientTickets.add.boxtitle_add'] = "Abrir Ticket";
$lang['ClientTickets.add.field_email'] = "Email";
$lang['ClientTickets.add.field_summary'] = "Resumo";
$lang['ClientTickets.add.field_priority'] = "Prioridade";
$lang['ClientTickets.add.field_details'] = "Detalhes";
$lang['ClientTickets.add.field_addsubmit'] = "Abrir Ticket";
$lang['ClientTickets.reply.boxtitle_reply'] = "Ticket #%1\$s"; // %1$s is the ticket number
$lang['ClientTickets.reply.heading_summary'] = "Sumário";
$lang['ClientTickets.reply.heading_priority'] = "Prioridade";
$lang['ClientTickets.reply.heading_status'] = "Estado";
$lang['ClientTickets.reply.heading_date_added'] = "Data de Abertura";
$lang['ClientTickets.reply.heading_reply'] = "Adicionar Resposta";
$lang['ClientTickets.reply.field_details'] = "Detalhes";
$lang['ClientTickets.reply.field_attachments'] = "Anexos";
$lang['ClientTickets.reply.text_add_attachment'] = "Adicionar Anexo";
$lang['ClientTickets.reply.log_date'] = "%1\$s por %2\$s %3\$s"; // %1$s is the ticket reply date, %2$s is the first name of the reply author, %3$s is the last name of the reply author
$lang['ClientTickets.reply.system'] = "Sistema";
$lang['ClientTickets.reply.staff_title'] = "Equipa de Suporte";
$lang['ClientTickets.departments.boxtitle_departments'] = "Departamentos de Suporte";
$lang['ClientTickets.index.option_reply'] = "Responder";
$lang['ClientTickets.add.placeholder_summary'] = "Introduzir Sumário";
$lang['ClientTickets.add.placeholder_details'] = "Introduzir Detalhes";
$lang['ClientTickets.reply.field_closesubmit'] = "Fechar";
$lang['ClientTickets.reply.confirm_close'] = "Tem a certeza de que deseja fechar este ticket?";
$lang['ClientTickets.reply.field_replysubmit'] = "Responder";
?>