<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Global.time_since.day'] = "%1\$s d"; // %1$s is the number of days
$lang['Global.time_since.hour'] = "%1\$s hr"; // %1$s is the number of hours
$lang['Global.time_since.minute'] = "%1\$s min"; // %1$s is the number of minutes
$lang['Global.select.never'] = "-- Nunca --";
$lang['Global.action.merge'] = "Juntar";
$lang['Global.action.update_status'] = "Atualizar Estado";
$lang['Global.action.quote'] = "Citar";
?>