<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Knowledgebase.index.page_title'] = "Base de Conhecimento";
$lang['Knowledgebase.view.page_title'] = "%1\$s"; // %1\$s is the title of the knowledge base article
$lang['Knowledgebase.index.heading_categories'] = "Categorias";
$lang['Knowledgebase.index.heading_subcategories'] = "Sub Categorias";
$lang['Knowledgebase.index.category_items'] = "(%1\$s)"; // %1$s is the number of items within this category
$lang['Knowledgebase.index.categories_no_results'] = "Não existem categorias disponíveis.";
$lang['Knowledgebase.index.heading_popular'] = "Artigos Populares";
$lang['Knowledgebase.index.heading_articles'] = "Artigos";
$lang['Knowledgebase.search.articles_no_results'] = "Não existem artigos que correspondam aos critérios de pesquisa.";
$lang['Knowledgebase.view.edit'] = "Editar";
$lang['Knowledgebase.view.text_vote_thanks'] = "Obrigado por votar neste artigo!";
$lang['Knowledgebase.!text.ellipsis'] = "...";
?>