<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SupportManagerResponses.!error.name.length'] = "O nome da categoria não deve exceder os 64 caracteres de comprimento.";
$lang['SupportManagerResponses.!error.category_id.exists'] = "ID de categoria inválido.";
$lang['SupportManagerResponses.!error.name.response_empty'] = "Por favor introduza um nome para esta resposta.";
?>