<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SupportManagerStaff.!error.company_id.exists'] = "O ID da Empresa é inválido.";
$lang['SupportManagerStaff.!error.departments.exists'] = "Pelo menos um dos departamento definidos não existe.";
$lang['SupportManagerStaff.!error.schedules[][day].format'] = "Dia agendado inválido.";
$lang['SupportManagerStaff.days.sun'] = "Domingo";
$lang['SupportManagerStaff.days.mon'] = "Segunda-Feira";
$lang['SupportManagerStaff.days.tue'] = "Terça-Feira";
$lang['SupportManagerStaff.days.wed'] = "Quarta-feira";
$lang['SupportManagerStaff.days.thu'] = "Quinta-feira";
$lang['SupportManagerStaff.days.fri'] = "Sexta-Feira";
$lang['SupportManagerStaff.days.sat'] = "Sábado";
?>