<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SupportManagerTickets.!error.code.format'] = "O código do ticket só pode conter dígitos.";
$lang['SupportManagerTickets.!error.department_id.exists'] = "Por favor selecione um departamento válido.";
$lang['SupportManagerTickets.!error.service_id.belongs'] = "O serviço selecionado é inválido.";
$lang['SupportManagerTickets.!error.client_id.exists'] = "O cliente escolhido para este ticket não existe.";
$lang['SupportManagerTickets.!error.email.format'] = "Por favor insira um endereço de e-mail válido.";
$lang['SupportManagerTickets.!error.status.format'] = "Por favor, selecione um estado válido.";
$lang['SupportManagerTickets.!error.date_closed.format'] = "A data de fecho do ticket está num formato de data inválido.";
$lang['SupportManagerTickets.!error.ticket_id.exists'] = "ID de Ticket inválido.";
$lang['SupportManagerTickets.priority.emergency'] = "Emergência";
$lang['SupportManagerTickets.priority.critical'] = "Crítico";
$lang['SupportManagerTickets.priority.high'] = "Alta";
$lang['SupportManagerTickets.priority.medium'] = "Médio";
$lang['SupportManagerTickets.priority.low'] = "Baixa";
$lang['SupportManagerTickets.status.open'] = "Aberto";
$lang['SupportManagerTickets.status.in_progress'] = "Em Andamento";
$lang['SupportManagerTickets.status.closed'] = "Fechado";
$lang['SupportManagerTickets.type.reply'] = "Responder";
$lang['SupportManagerTickets.type.note'] = "Nota";
$lang['SupportManagerTickets.type.log'] = "Registos";
$lang['SupportManagerTickets.log.department_id'] = "O departamento foi alterado para %1\$s."; // %1$s is the department name
$lang['SupportManagerTickets.log.summary'] = "O resumo foi atualizado.";
$lang['SupportManagerTickets.log.status'] = "O estado foi alterado para %1\$s."; // %1$s is the status
$lang['SupportManagerTickets.log.ticket_staff_id'] = "Associado a %1\$s"; // %1$s is the name of the department staff member the ticket was assigned to
$lang['SupportManagerTickets.log.unassigned'] = "Não Atribuido";
$lang['SupportManagerTickets.status.awaiting_reply'] = "Aguardando Resposta";
?>