<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SupportManagerDepartments.!error.company_id.exists'] = "ID da Empresa inválido.";
$lang['SupportManagerDepartments.!error.name.empty'] = "Por favor introduza um nome para este departamento.";
$lang['SupportManagerDepartments.!error.description.empty'] = "Por favor introduza uma descrição.";
$lang['SupportManagerDepartments.!error.email.format'] = "Por favor insira um endereço de email válido.";
$lang['SupportManagerDepartments.!error.host.format'] = "Digite um nome de host válido.";
$lang['SupportManagerDepartments.!error.user.format'] = "Introduza um nome de utilizador.";
$lang['SupportManagerDepartments.!error.user.length'] = "O nome de utilizador não deve exceder 64 caracteres de cumprimento.";
$lang['SupportManagerDepartments.!error.password.format'] = "Por favor introduza uma palavra-passe.";
$lang['SupportManagerDepartments.!error.port.length'] = "A porta não pode ser superior a 6 dígitos.";
$lang['SupportManagerDepartments.!error.service.format'] = "Por favor selecione um tipo de serviço válido.";
$lang['SupportManagerDepartments.!error.security.format'] = "Selecione um tipo de segurança válido.";
$lang['SupportManagerDepartments.!error.mark_messages.valid'] = "Mensagens que usam POP3 só podem ser marcadas como apagadas.";
$lang['SupportManagerDepartments.!error.status.format'] = "Tipo de estado inválido.";
$lang['SupportManagerDepartments.!error.department_id.exists'] = "ID de departamento inválido.";
$lang['SupportManagerDepartments.methods.none'] = "Nenhum";
$lang['SupportManagerDepartments.methods.pop3'] = "POP3";
$lang['SupportManagerDepartments.methods.imap'] = "IMAP";
$lang['SupportManagerDepartments.statuses.hidden'] = "Escondido";
$lang['SupportManagerDepartments.statuses.visible'] = "Visível";
$lang['SupportManagerDepartments.priorities.emergency'] = "Emergência";
$lang['SupportManagerDepartments.priorities.critical'] = "Crítico";
$lang['SupportManagerDepartments.priorities.medium'] = "Médio";
$lang['SupportManagerDepartments.priorities.low'] = "Baixa";
$lang['SupportManagerDepartments.security_types.none'] = "Nenhum";
$lang['SupportManagerDepartments.security_types.ssl'] = "SSL";
$lang['SupportManagerDepartments.security_types.tls'] = "TLS";
$lang['SupportManagerDepartments.ticket_intervals.day'] = "1 Dia";
$lang['SupportManagerDepartments.ticket_intervals.days'] = "%1\$s Dias"; // %1$s is the number of days
?>