<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SupportManagerKbCategories.!error.company_id.exists'] = "ID de empresa inválido.";
$lang['SupportManagerKbCategories.!error.name.empty'] = "Por favor introduza um nome de categoria.";
$lang['SupportManagerKbCategories.!error.category_id.exists'] = "ID de categoria inválido.";
$lang['SupportManagerKbCategories.access_types.public'] = "Público";
$lang['SupportManagerKbCategories.access_types.hidden'] = "Escondido";
?>