<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SupportManagerKbArticles.!error.company_id.exists'] = "ID de companhia inválido.";
$lang['SupportManagerKbArticles.!error.article_id.exists'] = "ID de categoria inválido.";
$lang['SupportManagerKbArticles.!error.categories.company'] = "Pelo menos uma categoria seleccionada não pertence à empresa seleccionada";
$lang['SupportManagerKbArticles.access_types.public'] = "Público";
$lang['SupportManagerKbArticles.access_types.private'] = "Privado";
$lang['SupportManagerKbArticles.access_types.hidden'] = "Escondido";
$lang['SupportManagerKbArticles.content_types.html'] = "HTML";
?>