<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SupportManagerPlugin.nav_primary_staff.main'] = "Suporte";
$lang['SupportManagerPlugin.nav_primary_staff.tickets'] = "Tickets";
$lang['SupportManagerPlugin.nav_primary_staff.departments'] = "Departamentos";
$lang['SupportManagerPlugin.widget_staff_client.tickets'] = "Tickets";
$lang['SupportManagerPlugin.action_staff_client.add'] = "Abrir Ticket";
$lang['SupportManagerPlugin.event_getsearchoptions.tickets'] = "Procurar Ticket";
$lang['SupportManagerPlugin.permission.admin_main'] = "Suporte";
$lang['SupportManagerPlugin.permission.admin_tickets'] = "Tickets";
$lang['SupportManagerPlugin.permission.admin_departments'] = "Departamentos";
$lang['SupportManagerPlugin.permission.admin_responses'] = "Respostas";
$lang['SupportManagerPlugin.permission.admin_staff'] = "Equipa";
$lang['SupportManagerPlugin.cron.close_tickets_name'] = "Fechar Tickets";
$lang['SupportManagerPlugin.nav_primary_client.knowledgebase'] = "Base de Conhecimento";
$lang['SupportManagerPlugin.nav_primary_staff.knowledgebase'] = "Base de Conhecimento";
$lang['SupportManagerPlugin.permission.admin_knowledgebase'] = "Base de Conhecimentos";
?>