<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['TransactionsApplied.name'] = "Transações Aplicadas";
$lang['TransactionsApplied.option.any'] = "Qualquer";
$lang['TransactionsApplied.options.field_end_date'] = "Data de Fim";
$lang['TransactionsApplied.options.field_gateway'] = "Gateway";
$lang['TransactionsApplied.options.field_status'] = "Estado";
$lang['TransactionsApplied.options.field_payment_type'] = "Tipo de Pagamento";
$lang['TransactionsApplied.heading.id'] = "Transação #";
$lang['TransactionsApplied.heading.transaction_id'] = "ID da Transação";
$lang['TransactionsApplied.heading.client_id_code'] = "Cliente #";
$lang['TransactionsApplied.heading.invoice_id_code'] = "Fatura #";
$lang['TransactionsApplied.heading.gateway_name'] = "Gateway de Pagamento";
$lang['TransactionsApplied.heading.type_name'] = "Tipo de Pagamento";
$lang['TransactionsApplied.heading.applied_amount'] = "Montante Aplicado";
$lang['TransactionsApplied.heading.amount'] = "Quantia de Pagamento";
$lang['TransactionsApplied.heading.currency'] = "Moeda";
$lang['TransactionsApplied.heading.status'] = "Estado";
$lang['TransactionsApplied.heading.income_type'] = "Tipo de Transação";
?>