<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Bitpay.name'] = "Bitpay";
$lang['Bitpay.api_key'] = "Chave da API";
$lang['Bitpay.transaction.speed.high'] = "Alta";
$lang['Bitpay.transaction.speed.medium'] = "Médio";
$lang['Bitpay.transaction.speed.low'] = "Baixa";
$lang['Bitpay.buildprocess.submit'] = "Pagar com Bitcoin";
$lang['Bitpay.!error.failed.response'] = "A transação não pôde ser processada.";
?>