<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Domain.lookup.title'] = "Verificar disponibilidade do Domínio";
$lang['Domain.lookup.transfer_btn'] = "Transferir";
$lang['Domain.lookup.domain_unavailable'] = "Não Disponível";
$lang['Domain.lookup.order_btn'] = "Comprar o Selecionado";
?>