<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Centoswebpanel.manage.module_groups_heading.options'] = "Opções";
$lang['Centoswebpanel.add_row.basic_title'] = "Definições Básicas";
$lang['Centoswebpanel.add_row.notes_title'] = "Notas";
$lang['Centoswebpanel.add_row.name_server_host_col'] = "Hostname";
$lang['Centoswebpanel.add_row.remove_name_server'] = "Remover";
$lang['Centoswebpanel.edit_row.notes_title'] = "Notas";
$lang['Centoswebpanel.edit_row.add_btn'] = "Editar Servidor";
$lang['Centoswebpanel.row_meta.api_key'] = "Chave da API";
$lang['Centoswebpanel.service_info.password'] = "Password";
?>