<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Centovacast.name'] = "CentovaCast";
$lang['Centovacast.module_row'] = "Servidor";
$lang['Centovacast.tab_stats'] = "Estatísticas";
$lang['Centovacast.tab_client_stats'] = "Estatísticas";
$lang['Centovacast.add_module_row'] = "Adicionar Servidor";
$lang['Centovacast.manage.module_rows_title'] = "Servidores";
$lang['Centovacast.manage.module_rows_heading.hostname'] = "Hostname";
$lang['Centovacast.manage.module_rows_heading.accounts'] = "Contas";
$lang['Centovacast.manage.module_groups_heading.servers'] = "Contagem de Servidores";
$lang['Centovacast.manage.module_groups_heading.options'] = "Opções";
$lang['Centovacast.manage.module_rows.edit'] = "Editar";
$lang['Centovacast.manage.module_rows.delete'] = "Apagar";
$lang['Centovacast.manage.module_rows.confirm_delete'] = "Tem certeza de que deseja apagar este servidor?";
$lang['Centovacast.manage.module_groups.confirm_delete'] = "Tem a certeza de que quer apagar este grupo de servidores?";
$lang['Centovacast.manage.module_rows_no_results'] = "Não existem servidores.";
$lang['Centovacast.add_row.add_btn'] = "Adicionar Servidor";
$lang['Centovacast.edit_row.box_title'] = "Editar Servidor CentovaCast";
$lang['Centovacast.edit_row.basic_title'] = "Definições Básicas";
$lang['Centovacast.edit_row.add_btn'] = "Editar Servidor";
$lang['Centovacast.row_meta.hostname'] = "Hostname";
$lang['Centovacast.row_meta.ipaddress'] = "Endereço IP";
$lang['Centovacast.row_meta.username'] = "Username";
$lang['Centovacast.row_meta.password'] = "Password";
$lang['Centovacast.row_meta.port'] = "Porta";
$lang['Centovacast.package_fields.maxclients'] = "Máximo de clientes";
$lang['Centovacast.service_field.password'] = "Password";
$lang['Centovacast.service_field.ipaddress'] = "Endereço IP";
$lang['Centovacast.service_field.port'] = "Porta";
$lang['Centovacast.tab_actions.action_restart'] = "Reiniciar";
$lang['Centovacast.tab_actions.action_stop'] = "Parar";
$lang['Centovacast.tab_stats.info_title'] = "Informação";
$lang['Centovacast.tab_stats.info_heading.value'] = "Valor";
$lang['Centovacast.tab_stats.info.username'] = "Username";
$lang['Centovacast.tab_stats.info.ipaddress'] = "Endereço IP";
$lang['Centovacast.tab_stats.bandwidth_heading.used'] = "Usado";
$lang['Centovacast.tab_stats.bandwidth_heading.limit'] = "Limite";
$lang['Centovacast.tab_stats.bandwidth_value'] = "%1\$s MB"; // %1$s is the amount of bandwidth in MB
$lang['Centovacast.tab_stats.bandwidth_unlimited'] = "ilimitado";
$lang['Centovacast.tab_stats.disk_title'] = "Disco";
$lang['Centovacast.tab_stats.disk_heading.used'] = "Utilizado";
$lang['Centovacast.tab_stats.disk_heading.limit'] = "Limite";
$lang['Centovacast.tab_stats.disk_value'] = "%1\$s MB"; // %1$s is the amount of disk in MB
$lang['Centovacast.tab_stats.disk_unlimited'] = "Ilimitado";
$lang['Centovacast.tab_client_actions.heading_status'] = "Estado do Servidor";
$lang['Centovacast.tab_client_actions.status_online'] = "Online";
$lang['Centovacast.tab_client_actions.heading_actions'] = "Ações";
$lang['Centovacast.tab_client_actions.action_restart'] = "Reiniciar";
$lang['Centovacast.tab_client_actions.action_stop'] = "Parar";
$lang['Centovacast.tab_client_actions.action_password'] = "Alterar Password";
$lang['Centovacast.tab_client_actions.field_password'] = "Password";
$lang['Centovacast.tab_client_stats.info_title'] = "Informação";
$lang['Centovacast.tab_client_stats.info_heading.value'] = "Valor";
$lang['Centovacast.tab_client_stats.info.hostname'] = "Hostname";
$lang['Centovacast.tab_client_stats.info.ipaddress'] = "Endereço IP";
$lang['Centovacast.tab_client_stats.info.adminpassword'] = "Password";
$lang['Centovacast.tab_client_stats.disk_title'] = "Utilização do Disco";
$lang['Centovacast.tab_client_stats.usage_unlimited'] = "(%1\$s MB/?)"; // %1$s is the amount of resource usage
$lang['Centovacast.service_info.hostname'] = "Hostname";
$lang['Centovacast.service_info.password'] = "Password";
$lang['Centovacast.!error.host_name_valid'] = "O Hostname aparenta ser inválido.";
$lang['Centovacast.!error.user_name_valid'] = "O Username aparenta ser inválido.";
?>