<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Virtualmin.module_row_plural'] = "Servidores";
$lang['Virtualmin.module_group'] = "Grupo do Servidor";
$lang['Virtualmin.add_module_row'] = "Adicionar Servidor";
$lang['Virtualmin.manage.module_rows_title'] = "Servidores";
$lang['Virtualmin.manage.module_rows_heading.hostname'] = "Hostname";
$lang['Virtualmin.manage.module_rows_heading.accounts'] = "Contas";
$lang['Virtualmin.manage.module_rows_heading.options'] = "Opções";
$lang['Virtualmin.manage.module_groups_heading.name'] = "Nome do Grupo";
$lang['Virtualmin.manage.module_groups_heading.servers'] = "Contagem de Servidores";
$lang['Virtualmin.manage.module_groups_heading.options'] = "Opções";
$lang['Virtualmin.manage.module_rows.count'] = "%1\$s / %2\$s"; // %1$s is the current number of accounts, %2$s is the total number of accounts available
$lang['Virtualmin.manage.module_rows.edit'] = "Editar";
$lang['Virtualmin.manage.module_rows.delete'] = "Apagar";
$lang['Virtualmin.manage.module_groups.delete'] = "Apagar";
$lang['Virtualmin.manage.module_rows.confirm_delete'] = "Tem a certeza de que quer apagar este servidor?";
$lang['Virtualmin.manage.module_groups.confirm_delete'] = "Tem a certeza de que quer apagar este grupo de servidores?";
$lang['Virtualmin.manage.module_rows_no_results'] = "Não existem servidores.";
$lang['Virtualmin.edit_row.add_btn'] = "Editar Servidor";
$lang['Virtualmin.row_meta.host_name'] = "Hostname";
$lang['Virtualmin.package_fields.plan'] = "Plano VirtualMin";
$lang['Virtualmin.package_fields.template'] = "Template VirtualMin";
$lang['Virtualmin.service_field.username'] = "Username";
$lang['Virtualmin.service_field.confirm_password'] = "Confirme a Senha";
$lang['Virtualmin.tab_client_actions.field_virtualmin_password'] = "Password";
$lang['Virtualmin.tab_client_actions.field_virtualmin_confirm_password'] = "Confirme a Senha";
$lang['Virtualmin.tab_client_actions.field_password_submit'] = "Atualizar Password";
$lang['Virtualmin.tab_stats.info_title'] = "Informação";
$lang['Virtualmin.tab_stats.info_heading.value'] = "Valor";
$lang['Virtualmin.service_info.username'] = "Username";
$lang['Virtualmin.service_info.password'] = "Password";
$lang['Virtualmin.service_info.options'] = "Opções";
$lang['Virtualmin.service_info.option_login'] = "Login";
$lang['Virtualmin.service_field.tooltip.password'] = "Pode deixar a password em branco para que seja gerada uma automaticamente.";
?>