<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Whmsonic.name'] = "WHMSonic";
$lang['Whmsonic.module_row'] = "Servidor";
$lang['Whmsonic.module_row_plural'] = "Servidores";
$lang['Whmsonic.module_group'] = "Grupo de Servidores";
$lang['Whmsonic.tab_client_actions'] = "Ações";
$lang['Whmsonic.tab_stats.info_heading.field'] = "Campo";
$lang['Whmsonic.tab_stats.info.client_type'] = "Tipo de Cliente";
$lang['Whmsonic.tab_stats.info.autodj'] = "Acesso AutoDJ";
$lang['Whmsonic.tab_stats.info.username'] = "Username";
$lang['Whmsonic.tab_stats.info.password'] = "Password";
$lang['Whmsonic.tab_stats.info.whmsonic_ftp'] = "Acesso FTP";
$lang['Whmsonic.tab_stats.info.whmsonic_radio_ip'] = "IP de Rádio";
$lang['Whmsonic.tab_stats.info.whmsonic_radio_password'] = "Senha de rádio";
$lang['Whmsonic.tab_client_actions.password'] = "Password cPanel";
$lang['Whmsonic.add_module_row'] = "Adicionar Servidor";
$lang['Whmsonic.manage.module_rows_title'] = "Servidores";
$lang['Whmsonic.manage.module_groups_title'] = "Gupos de Servidores";
$lang['Whmsonic.manage.module_rows_heading.ip_address'] = "Endereço IP";
$lang['Whmsonic.manage.module_rows_heading.options'] = "Opções";
$lang['Whmsonic.manage.module_groups_heading.options'] = "Opções";
$lang['Whmsonic.manage.module_groups.edit'] = "Editar";
$lang['Whmsonic.manage.module_rows.delete'] = "Apagar";
$lang['Whmsonic.manage.module_groups.delete'] = "Apagar";
$lang['Whmsonic.manage.module_rows.confirm_delete'] = "Tem a certeza de que quer apagar este servidor?";
$lang['Whmsonic.manage.module_rows_no_results'] = "Não existem servidores.";
$lang['Whmsonic.manage.module_groups_no_results'] = "Não existem grupos de servidores.";
$lang['Whmsonic.add_row.box_title'] = "Adicionar Server WHMSonic";
$lang['Whmsonic.add_row.basic_title'] = "Definições Básicas";
$lang['Whmsonic.add_row.add_btn'] = "Adicionar Servidor";
$lang['Whmsonic.row_meta.ip_address'] = "Endereço IP";
$lang['Whmsonic.package_fields.client_type'] = "Tipo de Cliente";
$lang['Whmsonic.package_fields.client_type.internal'] = "Interno";
$lang['Whmsonic.package_fields.autodj.no'] = "Não";
$lang['Whmsonic.service_info.ip_address'] = "Endereço IP";
$lang['Whmsonic.service_info.username'] = "Username";
$lang['Whmsonic.service_info.password'] = "Password";
$lang['Whmsonic.service_info.options'] = "Opções";
$lang['Whmsonic.!error.user_name.empty'] = "O Username não pode estar vazio.";
?>