<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ImportManagerManagePlugin.index.boxtitle_importmanager'] = "Gestor de Importação";
$lang['ImportManagerManagePlugin.index.platform'] = "Plataforma";
$lang['ImportManagerManagePlugin.index.versions'] = "Versões";
$lang['ImportManagerManagePlugin.import.submit'] = "Importar";
?>