<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['BuycPanel.!error.key.empty'] = "Por favor, digite a sua chave API.";
$lang['BuycPanel.!error.meta[license_type].valid'] = "Por favor escolha um tipo de licença válido.";
$lang['BuycPanel.!error.buycpanel_ipaddress.format'] = "Por favor introduza um endereço IP válido.";
$lang['BuycPanel.!error.api.internal'] = "Ocorreu um erro interno ou o servidor não respondeu ao pedido.";
$lang['BuycPanel.name'] = "BuycPanel";
$lang['BuycPanel.module_row.name'] = "Conta";
$lang['BuycPanel.module_rows.name'] = "Contas";
$lang['BuycPanel.module_group.name'] = "Grupo da Conta";
$lang['BuycPanel.order_options.first'] = "Primeiro";
$lang['BuycPanel.add_module_row'] = "Adicionar Conta";
$lang['BuycPanel.manage.module_rows_title'] = "Contas";
$lang['BuycPanel.manage.module_rows_heading.email'] = "Email";
$lang['BuycPanel.manage.module_rows_heading.test_mode'] = "Modo de Teste";
$lang['BuycPanel.manage.module_rows_heading.options'] = "Opções";
$lang['BuycPanel.manage.module_rows.delete'] = "Apagar";
$lang['BuycPanel.manage.module_rows.confirm_delete'] = "Tem certeza de que deseja apagar esta conta?";
$lang['BuycPanel.manage.module_rows.test_no'] = "Não";
$lang['BuycPanel.manage.module_rows_no_results'] = "Não existem contas.";
$lang['BuycPanel.tab_client_ip.heading_changeip'] = "Alterar IP";
$lang['BuycPanel.tab_client_ip.field_ipaddress'] = "Novo Endereço IP";
$lang['BuycPanel.tab_ip'] = "Alterar IP";
$lang['BuycPanel.tab_client_ip.field_submit'] = "Gravar";
$lang['BuycPanel.package_fields.license_type'] = "Tipo de Licença";
$lang['BuycPanel.service_fields.ipaddress'] = "Endereço IP";
$lang['BuycPanel.service_fields.domain'] = "Domínio";
$lang['BuycPanel.service_info.ip_address'] = "Endereço IP";
$lang['BuycPanel.service_info.license_type'] = "Licença";
$lang['BuycPanel.row_meta.email'] = "Email";
$lang['BuycPanel.row_meta.tooltip.email'] = "Introduza o email da sua conta BuycPanel.";
$lang['BuycPanel.row_meta.key'] = "Chave API";
$lang['BuycPanel.row_meta.test_mode'] = "Modo de teste";
$lang['BuycPanel.add_row.box_title'] = "Adicionar Conta BuycPanel";
$lang['BuycPanel.add_row.basic_title'] = "Definições Básicas";
$lang['BuycPanel.add_row.add_btn'] = "Adicionar Conta";
$lang['BuycPanel.edit_row.basic_title'] = "Definições Básicas";
$lang['BuycPanel.license_types.10'] = "cPanel VPS Optimized";
$lang['BuycPanel.license_types.20'] = "cPanel VPS Optimized Anual";
$lang['BuycPanel.license_types.3'] = "Licença de 1 ano";
$lang['BuycPanel.license_types.4'] = "Licença de Dois Anos";
$lang['BuycPanel.license_types.5'] = "Licença de Três Anos";
$lang['BuycPanel.license_types.blesta'] = "Blesta";
$lang['BuycPanel.license_types.clientexec'] = "ClientExec";
$lang['BuycPanel.license_types.cloudlinux'] = "CloudLinux";
$lang['BuycPanel.license_types.fantastico'] = "Fantastico";
$lang['BuycPanel.license_types.installatron'] = "Installatron";
$lang['BuycPanel.license_types.installatronvps'] = "Installatron VPS";
$lang['BuycPanel.license_types.litespeed'] = "Lite Speed";
$lang['BuycPanel.license_types.litespeedvps'] = "Lite Speed VPS";
$lang['BuycPanel.license_types.rvsitebuilder'] = "RVSiteBuilder";
$lang['BuycPanel.license_types.rvskin'] = "RVSkin";
$lang['BuycPanel.license_types.softaculous'] = "Softaculous";
$lang['BuycPanel.license_types.solusvminislave'] = "SolusVM Mini Slave";
$lang['BuycPanel.license_types.solusvmunslave'] = "SolusVM Slave";
$lang['BuycPanel.license_types.trendyflash'] = "TrendySite Builder Lite";
$lang['BuycPanel.license_types.trendyflashdedicated'] = "Construtor dedicado TrendySite";
$lang['BuycPanel.license_types.whmsonic'] = "WHMSonic";
$lang['BuycPanel.license_types.whmxtra'] = "WHMXtra";
?>