<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['QuickbooksInvoice.page_of'] = "Página %1\$s de %2\$s"; // %1$s is the current page number, %2$s is the total number of pages
$lang['QuickbooksInvoice.terms_heading'] = "Termos";
$lang['QuickbooksInvoice.type_active'] = "FATURA";
$lang['QuickbooksInvoice.type_draft'] = "FATURA - RASCUNHO";
$lang['QuickbooksInvoice.type_void'] = "FATURA - ANULADA";
$lang['QuickbooksInvoice.client_id_code'] = "Nº de Cliente";
$lang['QuickbooksInvoice.date_billed'] = "Data";
$lang['QuickbooksInvoice.date_due'] = "Data de Vencimento";
$lang['QuickbooksInvoice.notes_heading'] = "Notas";
$lang['QuickbooksInvoice.total_heading'] = "Total";
$lang['QuickbooksInvoice.lines_description'] = "Descrição";
$lang['QuickbooksInvoice.lines_quantity'] = "Quantidade";
$lang['QuickbooksInvoice.lines_unit_price'] = "Preço Unitário";
$lang['QuickbooksInvoice.lines_cost'] = "Custo";
$lang['QuickbooksInvoice.address_city_state'] = "%1\$s, %2\$s %3\$s %4\$s"; // %1$s is the city, %2$s is the state code, %3$s is the zip/postal code, %4$s is the country code
$lang['QuickbooksInvoice.client_tax_id'] = "ID de imposto do cliente/VATIN: %1\$s"; // %1$s is the tax ID/VATIN
$lang['QuickbooksInvoice.type_proforma'] = "FATURA PRÓ FORMA";
$lang['QuickbooksInvoice.payments_heading'] = "Pagamentos";
$lang['QuickbooksInvoice.payments_applied_date'] = "Data de Aplicação";
$lang['QuickbooksInvoice.payments_type_name'] = "Tipo";
$lang['QuickbooksInvoice.payments_applied_amount'] = "Montante Aplicado";
$lang['QuickbooksInvoice.balance_heading'] = "Balanço";
$lang['QuickbooksInvoice.draft_id_code'] = "Rascunho Num.";
?>