<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Solusvm.!actions.boot'] = "Iniciar";
$lang['Solusvm.!actions.reboot'] = "Reiniciar";
$lang['Solusvm.!actions.shutdown'] = "Desligar";
$lang['Solusvm.!actions.reinstall'] = "Reinstalar";
$lang['Solusvm.!actions.password'] = "Alterar Palavra-passe";
$lang['Solusvm.!error.host.format'] = "O hostname parece ser inválido.";
$lang['Solusvm.!error.port.format'] = "Por favor introduza um número de porta válido.";
$lang['Solusvm.!error.meta[type].valid'] = "Por favor escolha um tipo de virtualização válido.";
$lang['Solusvm.!error.solusvm_template.valid'] = "Por favor escolha uma template válida.";
$lang['Solusvm.!error.create_client.failed'] = "Ocorreu um erro interno e a conta do cliente não pôde ser criada";
$lang['Solusvm.!error.api.template.valid'] = "A Template selecionada é inválida.";
$lang['Solusvm.!bytes.value'] = "%1\$s%2\$s"; // %1$s is a number value, %2$s is the unit of that value (i.e., one of B, KB, MB, GB)
$lang['Solusvm.!percent.used'] = "%1\$s%"; // %1$s is a percentage value
$lang['Solusvm.name'] = "SolusVM";
$lang['Solusvm.module_row_plural'] = "Servidores";
$lang['Solusvm.add_module_row'] = "Adicionar Servidor";
$lang['Solusvm.manage.module_rows_title'] = "Servidores Mestres SolusVM";
$lang['Solusvm.manage.module_rows_heading.host'] = "Hostname";
$lang['Solusvm.manage.module_rows_heading.options'] = "Opções";
$lang['Solusvm.manage.module_groups_heading.name'] = "Nome do Grupo";
$lang['Solusvm.manage.module_groups_heading.options'] = "Opções";
$lang['Solusvm.manage.module_rows.edit'] = "Editar";
$lang['Solusvm.manage.module_groups.edit'] = "Editar";
$lang['Solusvm.manage.module_rows.delete'] = "Apagar";
$lang['Solusvm.manage.module_groups.confirm_delete'] = "Tem a certeza de que quer apagar este grupo de servidores?";
$lang['Solusvm.manage.module_rows_no_results'] = "Não existem servidores.";
$lang['Solusvm.manage.module_groups_no_results'] = "Não existem grupos de servidores.";
$lang['Solusvm.order_options.first'] = "Primeiro servidor não-completo";
$lang['Solusvm.row_meta.server_name'] = "Etiqueta do servidor";
$lang['Solusvm.row_meta.user_id'] = "ID de Utilizador";
$lang['Solusvm.row_meta.key'] = "Chave";
$lang['Solusvm.row_meta.port'] = "Número de Porta SSL";
$lang['Solusvm.row_meta.default_port'] = "5656";
$lang['Solusvm.types.openvz'] = "OpenVZ";
$lang['Solusvm.types.xen'] = "Xen";
$lang['Solusvm.types.xen_hvm'] = "Xen HVM";
$lang['Solusvm.types.kvm'] = "KVM";
$lang['Solusvm.add_row.box_title'] = "Adicionar Servidor SolusVM";
$lang['Solusvm.add_row.basic_title'] = "Definições Básicas";
$lang['Solusvm.edit_row.box_title'] = "Editar Servidor SolusVM";
$lang['Solusvm.edit_row.basic_title'] = "Definições Básicas";
$lang['Solusvm.edit_row.add_btn'] = "Atualizar Servidor";
$lang['Solusvm.package_fields.type'] = "Tipo";
$lang['Solusvm.package_fields.admin_set_template'] = "Escolha uma template";
$lang['Solusvm.package_fields.plan'] = "Plano";
$lang['Solusvm.service_field.solusvm_hostname'] = "Hostname";
$lang['Solusvm.service_field.solusvm_template'] = "Template";
$lang['Solusvm.service_info.solusvm_main_ip_address'] = "Endereço IP Primário";
$lang['Solusvm.tab_console'] = "Consola";
$lang['Solusvm.tab_actions.heading_actions'] = "Ações";
$lang['Solusvm.tab_actions.status_online'] = "Online";
$lang['Solusvm.tab_actions.status_offline'] = "Offline";
$lang['Solusvm.tab_actions.status_disabled'] = "Desactivado";
$lang['Solusvm.tab_actions.server_status'] = "Estado do servidor";
$lang['Solusvm.tab_actions.field_reinstall_submit'] = "Reinstalar";
$lang['Solusvm.tab_actions.heading_hostname'] = "Alterar Hostname";
$lang['Solusvm.tab_actions.field_hostname'] = "Hostname";
$lang['Solusvm.tab_actions.field_hostname_submit'] = "Alterar Hostname";
$lang['Solusvm.tab_actions.heading_password'] = "Alterar Password";
$lang['Solusvm.tab_actions.field_password'] = "Nova password de Root";
$lang['Solusvm.tab_actions.field_confirm_password'] = "Confirmar Palavra-passe";
$lang['Solusvm.tab_actions.field_password_submit'] = "Alterar Password";
$lang['Solusvm.tab_client_actions.heading_actions'] = "Ações";
$lang['Solusvm.tab_client_actions.heading_server_status'] = "Estado do Servidor";
$lang['Solusvm.tab_client_actions.status_online'] = "Online";
$lang['Solusvm.tab_client_actions.status_offline'] = "Offline";
$lang['Solusvm.tab_client_actions.status_disabled'] = "Desativado";
$lang['Solusvm.tab_client_actions.heading_reinstall'] = "Reinstalar";
$lang['Solusvm.tab_client_actions.field_template'] = "Template";
$lang['Solusvm.tab_client_actions.field_reinstall_submit'] = "Reinstalar";
$lang['Solusvm.tab_client_actions.heading_hostname'] = "Alterar Hostname";
$lang['Solusvm.tab_client_actions.field_hostname'] = "Hostname";
$lang['Solusvm.tab_client_actions.field_hostname_submit'] = "Alterar Hostname";
$lang['Solusvm.tab_client_actions.heading_password'] = "Alterar Palavra-passe";
$lang['Solusvm.tab_client_actions.field_confirm_password'] = "Confirme a sua senha";
$lang['Solusvm.tab_client_actions.field_password_submit'] = "Alterar Password";
$lang['Solusvm.tab_stats.heading_stats'] = "Estatísticas";
$lang['Solusvm.tab_stats.bandwidth_stats'] = "%1\$s/%2\$s"; // %1$s is the bandwidth used, %2$s is the total bandwidth available
$lang['Solusvm.tab_stats.bandwidth_percent_available'] = "(%1\$s%%)"; // %1$s is the percentage of bandwidth used. You MUST use two % signs to represent a single percent (i.e. %%)
$lang['Solusvm.tab_stats.memory_stats'] = "%1\$s/%2\$s"; // %1$s is the memory used, %2$s is the total memory available
$lang['Solusvm.tab_stats.memory_percent_available'] = "(%1\$s%%)"; // %1$s is the percentage of memory used. You MUST use two % signs to represent a single percent (i.e. %%)
$lang['Solusvm.tab_stats.space'] = "Espaço em Disco:";
$lang['Solusvm.tab_stats.space_stats'] = "%1\$s/%2\$s"; // %1$s is the hard disk space used, %2$s is the total hard disk space available
$lang['Solusvm.tab_stats.space_percent_available'] = "(%1\$s%%)"; // %1$s is the percentage of hard disk space used. You MUST use two % signs to represent a single percent (i.e. %%)
$lang['Solusvm.tab_client_stats.heading_stats'] = "Estatísticas";
$lang['Solusvm.tab_client_stats.heading_graphs'] = "Gráficos";
$lang['Solusvm.tab_console.heading_console'] = "Consola";
$lang['Solusvm.tab_console.console_password'] = "Palavra-passe da Consola:";
$lang['Solusvm.tab_console.vnc_port'] = "Porta VNC:";
$lang['Solusvm.tab_client_console.heading_console'] = "Consola";
$lang['Solusvm.package_fields.set_node_group'] = "Atribuir um grupo de node";
$lang['Solusvm.package_fields.node_group'] = "Grupo do Node";
$lang['Solusvm.service_field.solusvm_vserver_id'] = "ID do Servidor Virtual";
$lang['Solusvm.tab_status.no_results'] = "Estatísticas não estão atualmente disponíveis.";
$lang['Solusvm.tab_client_stats.usage'] = "(%1\$s/%2\$s)"; // %1$s is the amount of resources used, %2$s is the amount of total resources available
$lang['Solusvm.tab_client_stats.memory'] = "Memória";
$lang['Solusvm.tab_client_stats.space'] = "Espaço em Disco";
$lang['Solusvm.tab_client_console.vnc_password'] = "Password VNC";
$lang['Solusvm.tab_ips'] = "Endereços IP";
$lang['Solusvm.tab_ips.heading_ips'] = "Endereço IP";
$lang['Solusvm.tab_ips.primary_ip'] = "Endereço IP Primário: %1\$s"; // %1$s is the IP address
$lang['Solusvm.tab_ips.heading_extra_ips'] = "Endereços de IP Extra";
$lang['Solusvm.tab_ips.heading_ip'] = "Endereço IP";
$lang['Solusvm.tab_ips.option_remove'] = "Remover IP";
$lang['Solusvm.tab_ips.confirm_remove'] = "Tem a certeza de que deseja remover permanentemente este endereço IP?";
$lang['Solusvm.tab_client_ips.heading_extra'] = "Endereços IP adicionais";
$lang['Solusvm.tab_client_ips.confirm_remove_ip'] = "Tem a certeza de que quer remover este Endereço IP permanentemente?";
$lang['Solusvm.tab_client_ips.remove_ip'] = "Remover IP";
$lang['Solusvm.tab_client_ips.cancel'] = "Cancelar";
$lang['Solusvm.tab_actions.node'] = "Node: %1\$s"; // %1$s is the name of the node
$lang['Solusvm.tab_client_actions.heading_node'] = "Nó";
?>