<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Authorize_net.name'] = "Authorize.Net";
$lang['Authorize_net.login_id'] = "ID de Login";
$lang['Authorize_net.transaction_key'] = "Chave de Transação";
$lang['Authorize_net.api'] = "API de Pagamento";
$lang['Authorize_net.test_mode'] = "Modo de Teste";
$lang['Authorize_net.validation_modes_none'] = "Nenhum";
$lang['Authorize_net.validation_modes_test'] = "Teste";
?>