<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Blue_pay.!error.secret_key.empty'] = "Por favor introduza a sua chave secreta.";
$lang['Blue_pay.name'] = "BluePay";
$lang['Blue_pay.account_id'] = "ID de Conta";
$lang['Blue_pay.secret_key'] = "Chave Secreta";
$lang['Blue_pay.test_mode'] = "Modo de Teste";
?>