<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PhpidsManagePlugin.!success.settings_updated'] = "As definições foram actualizadas com sucesso.";
$lang['PhpidsManagePlugin.index.boxtitle_phpids'] = "PHPIDS";
$lang['PhpidsManagePlugin.index.tab_settings'] = "Definições";
$lang['PhpidsManagePlugin.index.tab_logs'] = "Registos";
$lang['PhpidsManagePlugin.index.field.submit'] = "Actualizar Definições";
$lang['PhpidsManagePlugin.getIntervals.mins_plural'] = "%1\$s Minutos"; // %1$s is the number of minutes
$lang['PhpidsManagePlugin.getDays.days_plural'] = "%1\$s Dias"; // %1$s is the number of days
$lang['PhpidsManagePlugin.getDays.days_never'] = "Nunca rodar";
$lang['PhpidsManagePlugin.logs.heading.name'] = "Nome";
$lang['PhpidsManagePlugin.logs.heading.value'] = "Valor";
$lang['PhpidsManagePlugin.logs.heading.uri'] = "URI";
$lang['PhpidsManagePlugin.logs.heading.ip'] = "IP";
$lang['PhpidsManagePlugin.logs.heading.user_id'] = "ID de Utilizador";
$lang['PhpidsManagePlugin.logs.heading.tags'] = "Tags";
$lang['PhpidsManagePlugin.logs.heading.impact'] = "Impacto";
$lang['PhpidsManagePlugin.logs.no_results'] = "Não existem resultados.";
?>