<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SharedLoginManagePlugin.index.page_title'] = "Início de sessão partilhado";
$lang['SharedLoginManagePlugin.index.boxtitle_manage'] = "Login Partilhado";
$lang['SharedLoginManagePlugin.index.field_key'] = "Chave Partilhada";
$lang['SharedLoginManagePlugin.index.submit'] = "Guardar";
?>