<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Offline.name'] = "Pagamento offline";
$lang['Offline.instructions'] = "Instruções";
$lang['Offline.!error.instructions.valid'] = "Tem de introduzir algumas instruções.";
?>