<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Alipay.signature_key'] = "Chave de Assinatura";
$lang['Alipay.!error.merchant_email.valid'] = "Tem de introduzir um endereço de email válido.";
?>