<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Converge.name'] = "Convergir";
$lang['Converge.login_id'] = "ID de Login";
$lang['Converge.transaction_key'] = "Chave de Transação";
$lang['Converge.api'] = "API de Pagamento";
$lang['Converge.merchant_id'] = "ID de Comerciante";
$lang['Converge.user_id'] = "ID de Utilizador";
$lang['Converge.pin'] = "PIN";
$lang['Converge.yes'] = "Sim";
$lang['Converge.no'] = "Não";
?>