<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Ispconfig.manage.module_groups_title'] = "Grupos de Servidores";
$lang['Ispconfig.manage.module_groups.edit'] = "Editar";
$lang['Ispconfig.manage.module_groups_no_results'] = "Não existem grupos de servidores.";
$lang['Ispconfig.add_row.name_server'] = "Name Server %1\$s"; // %1$s is the name server number (e.g. 3)
$lang['Ispconfig.add_row.add_btn'] = "Adicionar Servidor";
$lang['Ispconfig.edit_row.name_servers_title'] = "Name Servers";
$lang['Ispconfig.edit_row.notes_title'] = "Notas";
$lang['Ispconfig.service_field.username'] = "Username";
$lang['Ispconfig.tab_stats.info_title'] = "Informação";
$lang['Ispconfig.tab_client_actions.change_password'] = "Alterar Password";
$lang['Ispconfig.tab_client_actions.field_password_submit'] = "Atualizar Password";
$lang['Ispconfig.tab_client_stats.info_heading.value'] = "Valor";
$lang['Ispconfig.tab_client_stats.usage_unlimited'] = "(%1\$s MB/?)"; // %1$s is the amount of resource usage
$lang['Ispconfig.service_info.username'] = "Username";
$lang['Ispconfig.service_info.password'] = "Password";
$lang['Ispconfig.service_info.options'] = "Opções";
$lang['Ispconfig.!error.name_servers_count'] = "Tem de definir pelo menos 2 Name Servers.";
$lang['Ispconfig.!error.ispconfig_domain.format'] = "Por favor introduza um domínio válido, ex: dominio.com";
?>