<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Stripe_gateway.!error.api_key.empty'] = "Por favor introduza uma Chave API.";
$lang['Stripe_gateway.name'] = "Stripe";
$lang['Stripe_gateway.api_key'] = "Chave Secreta da API";
?>