<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Payflow.name'] = "PayPal Payflow Pro";
$lang['Payflow.user'] = "Utilizador";
$lang['Payflow.password'] = "Palavra-passe";
$lang['Payflow.test_mode'] = "Modo de Teste";
$lang['Payflow.!error.password.format'] = "Por favor introduza uma palavra-passe entre 6 a 32 caracteres de comprimento.";
?>