<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Checkout.index.heading_other_payment_options'] = "Outras Opções de Pagamento";
$lang['Checkout.index.heading_payment_options'] = "Opções de Pagamento";
$lang['Checkout.contact_info.heading_contact'] = "Informações de Contacto";
$lang['Checkout.complete.invoice_paid'] = "PAGO";
?>