<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Config.index.header_configuration'] = "Configuração";
$lang['Config.index.header_configure_service'] = "Configurar %1\$s"; // %1$s is the service name to configure
$lang['Config.index.header_term'] = "Termo e Preço";
?>