<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Main.index.group_heading'] = "Escolha um pacote abaixo.";
$lang['Main.index.sold_out'] = "Esgotado";
$lang['Main.index.field_currency'] = "Moeda:";
$lang['Main.index.show_cart_btn'] = "Mostrar Carrinho";
$lang['Main.packages.price_start'] = "Desde";
$lang['Main.packages.box_sold_out'] = "Fora de Stock";
$lang['Main.packages.continue_note'] = "Continue para a configuração e pagamento.";
?>