<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Signup.index.login_note'] = "Você terá uma oportunidade de confirmar a encomenda após fazer login.";
$lang['Signup.index.client_note'] = "Esta encomenda será adicionada à seguinte conta.";
$lang['Signup.index.configure_btn'] = "Continuar";
$lang['Signup.index.heading_contact'] = "Informação de Contacto";
$lang['Signup.index.heading_billing'] = "Informação de Faturação";
$lang['Signup.index.heading_authentication'] = "Autenticação";
?>