<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Tcadmin.name'] = "TCAdmin";
$lang['Tcadmin.module_row'] = "Servidor";
$lang['Tcadmin.module_row_plural'] = "Servidores";
$lang['Tcadmin.add_module_row'] = "Adicionar Servidor";
$lang['Tcadmin.manage.module_rows_title'] = "Servidores";
$lang['Tcadmin.manage.module_rows_heading.hostname'] = "Hostname";
$lang['Tcadmin.manage.module_rows_heading.port'] = "Porta";
$lang['Tcadmin.manage.module_rows.edit'] = "Editar";
$lang['Tcadmin.manage.module_groups.edit'] = "Editar";
$lang['Tcadmin.manage.module_groups.delete'] = "Apagar";
$lang['Tcadmin.manage.module_groups.confirm_delete'] = "Tem a certeza de que quer apagar este grupo de servidores?";
$lang['Tcadmin.add_row.basic_title'] = "Definições Básicas";
$lang['Tcadmin.add_row.add_btn'] = "Adicionar Servidor";
$lang['Tcadmin.edit_row.box_title'] = "Editar Servidor TCAdmin";
$lang['Tcadmin.row_meta.host_name'] = "Hostname";
$lang['Tcadmin.row_meta.password'] = "Password";
$lang['Tcadmin.row_meta.port'] = "Porta";
$lang['Tcadmin.package_fields.server_type'] = "Tipo de Servidor";
$lang['Tcadmin.package_fields.game_server'] = "Servidor de Jogo";
$lang['Tcadmin.package_fields.supported_servers'] = "Servidor TCAdmin suportados";
$lang['Tcadmin.package_fields.start'] = "Iniciar após Criação";
$lang['Tcadmin.package_fields.priority'] = "Prioridade";
$lang['Tcadmin.package_fields.priority.normal'] = "Normal";
$lang['Tcadmin.package_fields.priority.realtime'] = "Tempo Real";
$lang['Tcadmin.package_fields.startup.manual'] = "Manual";
$lang['Tcadmin.service_field.user_name'] = "Username TCAdmin";
$lang['Tcadmin.service_field.user_password'] = "Password TCAdmin";
$lang['Tcadmin.service_field.rcon_password'] = "Password RCON";
$lang['Tcadmin.service_field.private_password'] = "Password Privada";
$lang['Tcadmin.service_info.hostname'] = "Hostname";
$lang['Tcadmin.service_info.password'] = "Password";
$lang['Tcadmin.service_info.option_login'] = "Entrar";
$lang['Tcadmin.!error.password_valid'] = "A Password aparenta ser inválida.";
$lang['Tcadmin.!error.meta[server_type].valid'] = "Por favor escolha um tipo de servidor válido.";
?>