<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Eway.!error.libxml_required'] = "As extensões libxml e simplexml são requeridas para este gateway.";
$lang['Eway.name'] = "eWAY";
$lang['Eway.developer_mode'] = "Modo de Desenvolvedor";
$lang['Eway.test_mode'] = "Modo de Teste";
?>