<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMain.!success.options_updated'] = "As opções de faturamento de relance foram atualizadas com sucesso!";
$lang['AdminMain.index.boxtitle_overview'] = "Faturamento num relance";
$lang['AdminMain.index.statistic.revenue_today'] = "Receita de Hoje";
$lang['AdminMain.index.statistic.revenue_month'] = "Receita este Mês";
$lang['AdminMain.index.statistic.invoiced_today'] = "Faturado Hoje";
$lang['AdminMain.index.statistic.invoiced_month'] = "Faturado este Mês";
$lang['AdminMain.index.statistic.balance_outstanding'] = "Balanço Negativo";
$lang['AdminMain.index.statistic.balance_overdue'] = "Saldo em atraso";
$lang['AdminMain.index.statistic.services_active'] = "Serviços Ativos";
$lang['AdminMain.index.statistic.services_added_today'] = "Serviços Adicionados Hoje";
$lang['AdminMain.index.statistic.services_canceled_today'] = "Serviços Cancelados Hoje";
$lang['AdminMain.settings.heading_statistics'] = "Estatísticas";
$lang['AdminMain.settings.heading_graphs'] = "Gráficos";
$lang['AdminMain.settings.heading_graph_settings'] = "Definições de Gráficos";
$lang['AdminMain.settings.revenue_today'] = "Receita Hoje";
$lang['AdminMain.settings.revenue_month'] = "Receita este Mês";
$lang['AdminMain.settings.invoiced_today'] = "Faturado Hoje";
$lang['AdminMain.settings.invoiced_month'] = "Faturado este mês";
$lang['AdminMain.settings.scheduled_cancelation'] = "Cancelamentos Agendados";
$lang['AdminMain.settings.services_active'] = "Serviços Ativos";
$lang['AdminMain.settings.services_added_today'] = "Serviços Adicionados Hoje";
$lang['AdminMain.settings.services_canceled_today'] = "Serviços Cancelados Hoje";
$lang['AdminMain.settings.graph_invoiced'] = "Gráfico de Montante Faturado";
$lang['AdminMain.settings.show_legend'] = "Mostrar legenda nos Gráficas";
$lang['AdminMain.date_range.days'] = "dias";
$lang['AdminMain.graph_name.graph_invoiced'] = "Montante Faturado";
$lang['AdminMain.graph_line_name.total'] = "Total";
$lang['AdminMain.graph_line_name.credit'] = "Cartão de Crédito";
$lang['AdminMain.graph_line_name.ach'] = "ACH";
$lang['AdminMain.graph_line_name.other'] = "Outro";
$lang['AdminMain.index.statistic.revenue_year'] = "Receita este Ano";
$lang['AdminMain.settings.revenue_year'] = "Receita este Ano";
$lang['AdminMain.index.statistic.credits_today'] = "Créditos Hoje";
$lang['AdminMain.index.statistic.credits_year'] = "Créditos este Ano";
$lang['AdminMain.settings.credits_month'] = "Créditos este mês";
$lang['AdminMain.settings.credits_year'] = "Créditos este Ano";
?>