<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['BillingOverviewSettings.!error.staff_id.exists'] = "ID de Equipa inválido.";
$lang['BillingOverviewSettings.!error.company_id.exists'] = "ID de empresa inválido.";
$lang['BillingOverviewSettings.!error.settings[][key].empty'] = "Nenhuma chave de configuração, provavelmente está vaziu.";
?>