<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Plesk.!error.simplexml_required'] = "A extensão simplexml é necessária para este módulo.";
$lang['Plesk.!error.host_name.valid'] = "O IP parece ser inválido.";
$lang['Plesk.!error.port.format'] = "O número da porta tem de ser um número.";
$lang['Plesk.!error.username.empty'] = "Por favor introduza um nome de utilizador.";
$lang['Plesk.!error.password.empty'] = "Por favor introduza uma password.";
$lang['Plesk.!error.panel_version.valid'] = "Por favor escolha a versão do seu Painel Plesk.";
$lang['Plesk.!error.plesk_confirm_password.matches'] = "As palavras-passe não coincidem.";
$lang['Plesk.please_select'] = "-- Por favor escolha --";
$lang['Plesk.tab_stats'] = "Estatísticas";
$lang['Plesk.tab_client_stats'] = "Estatísticas";
$lang['Plesk.stats.unlimited'] = "Ilimitado";
$lang['Plesk.!bytes.value'] = "%1\$s %2\$s"; // %1$s is a number value, %2$s is the unit of that value (i.e., one of B, KB, MB, GB)
$lang['Plesk.tab_stats.info_title'] = "Informação";
$lang['Plesk.tab_stats.bandwidth_title'] = "Largura de Banda";
$lang['Plesk.tab_stats.disk_title'] = "Disco";
$lang['Plesk.tab_stats.info_heading.field'] = "Campo";
$lang['Plesk.tab_stats.info_heading.value'] = "Valor";
$lang['Plesk.tab_stats.bandwidth_heading.used'] = "Usado";
$lang['Plesk.tab_stats.disk_heading.limit'] = "Limite";
$lang['Plesk.tab_stats.info.domain'] = "Domínio";
$lang['Plesk.tab_stats.info.ip_address'] = "Endereço IP";
$lang['Plesk.tab_client_stats.info_title'] = "Informação";
$lang['Plesk.tab_client_stats.info_heading.field'] = "Campo";
$lang['Plesk.tab_client_stats.info_heading.value'] = "Valor";
$lang['Plesk.tab_client_stats.info.domain'] = "Domínio";
$lang['Plesk.tab_client_stats.info.ip_address'] = "Endereço IP";
$lang['Plesk.name'] = "Plesk";
$lang['Plesk.module_row'] = "Servidor";
$lang['Plesk.module_row_plural'] = "Servidores";
$lang['Plesk.module_group'] = "Grupo do Servidor";
$lang['Plesk.service_field.domain'] = "Domínio";
$lang['Plesk.service_field.username'] = "Nome de utilizador";
$lang['Plesk.service_field.password'] = "Password";
$lang['Plesk.service_field.confirm_password'] = "Confirmar Palavra-passe";
$lang['Plesk.service_field.tooltip.username'] = "Pode deixar o nome de utilizador em branco para gerar um automaticamente.";
$lang['Plesk.service_field.tooltip.password'] = "Você pode deixar a senha em branco para gerar automaticamente uma.
";
$lang['Plesk.service_field.tooltip.webspace_id_edit'] = "O ID de subscrição só será alterada localmente. Não vai ser alterado no Plesk.";
$lang['Plesk.package_fields.type'] = "Tipo de Conta";
$lang['Plesk.package_fields.type_standard'] = "Padrão";
$lang['Plesk.package_fields.type_reseller'] = "Revendedor";
$lang['Plesk.service_info.username'] = "Username";
$lang['Plesk.service_info.password'] = "Palavra-passe";
$lang['Plesk.service_info.server'] = "Servidor";
$lang['Plesk.add_row.basic_title'] = "Definições Básicas";
$lang['Plesk.add_row.add_btn'] = "Adicionar Servidor";
$lang['Plesk.edit_row.box_title'] = "Editar Servidor Plesk";
$lang['Plesk.edit_row.basic_title'] = "Definições Básicas";
$lang['Plesk.edit_row.add_btn'] = "Editar Servidor";
$lang['Plesk.row_meta.server_name'] = "Etiqueta do Servidor";
$lang['Plesk.row_meta.ip_address'] = "Endereço IP";
$lang['Plesk.row_meta.username'] = "Nome de utilizador";
$lang['Plesk.row_meta.password'] = "Password";
$lang['Plesk.row_meta.panel_version'] = "Versão do Plesk";
$lang['Plesk.add_module_group'] = "Adicionar Grupo de Servidores";
$lang['Plesk.manage.module_rows_title'] = "Servidores";
$lang['Plesk.manage.module_groups_title'] = "Grupos de Servidores";
$lang['Plesk.manage.module_rows_heading.ip_address'] = "Endereço IP";
$lang['Plesk.manage.module_rows_heading.options'] = "Opções";
$lang['Plesk.manage.module_groups_heading.name'] = "Nome do Grupo";
$lang['Plesk.manage.module_groups_heading.servers'] = "Contagem de Servidores";
$lang['Plesk.manage.module_groups_heading.options'] = "Opções";
$lang['Plesk.manage.module_rows.edit'] = "Editar";
$lang['Plesk.manage.module_groups.edit'] = "Editar";
$lang['Plesk.manage.module_rows.confirm_delete'] = "Tem a certeza de que quer apagar este servidor?";
$lang['Plesk.manage.module_rows_no_results'] = "Não existem servidores.";
$lang['Plesk.manage.module_groups_no_results'] = "Não existem grupos de servidores.";
$lang['Plesk.panel_version.windows'] = "Windows";
$lang['Plesk.panel_version.linux'] = "Linux/Unix";
$lang['Plesk.panel_version.plesk_type'] = "Plesk %1\$s para %1\$s"; // %1$s is the Plesk panel version number, %2$s is the OS type (i.e. Windows or Linux/Unix)
$lang['Plesk.panel_version.plesk'] = "Plesk %1\$s"; // %1$s is the Plesk panel version number
$lang['Plesk.!error.api.customer_delete_filter_missing'] = "Filtro em falta para excluir um cliente específico";
$lang['Plesk.service_info.options'] = "Opções";
$lang['Plesk.row_meta.reseller'] = "Conta de Revendedor";
$lang['Plesk.tab_client_stats.usage'] = "(%1\$s/%2\$s)"; // %1$s is the amount of resource usage, %2$s is the resource usage limit
$lang['Plesk.tab_client_stats.not_available'] = "N/D";
$lang['Plesk.tab_client_stats.disk_title'] = "Utilização do Disco";
?>