<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['InvoiceCreation.options.field_start_date'] = "Data de Início";
$lang['InvoiceCreation.options.field_end_date'] = "Data de Conclusão";
$lang['InvoiceCreation.options.field_status'] = "Estado";
$lang['InvoiceCreation.heading.id_code'] = "Fatura #";
$lang['InvoiceCreation.heading.client_id_code'] = "#Cliente";
$lang['InvoiceCreation.heading.total'] = "Total";
$lang['InvoiceCreation.heading.paid'] = "Pago";
$lang['InvoiceCreation.heading.currency'] = "Moeda";
$lang['InvoiceCreation.heading.status'] = "Estado";
$lang['InvoiceCreation.heading.date_billed'] = "Data de Faturação";
?>