<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['DownloadManagerFiles.!error.category_id.exists'] = "Por favor escolha uma categoria válida.";
$lang['DownloadManagerFiles.!error.company_id.exists'] = "ID de empresa inválido.";
$lang['DownloadManagerFiles.!error.name.empty'] = "Por favor introduza um nome para este ficheiro.";
?>