<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['DownloadManagerManagePlugin.!success.category_added'] = "A categoria foi criada com sucesso.";
$lang['DownloadManagerManagePlugin.!success.category_updated'] = "A categoria foi actualizada com sucesso.";
$lang['DownloadManagerManagePlugin.!success.category_deleted'] = "A categoria foi apagada com sucesso.";
$lang['DownloadManagerManagePlugin.!success.file_added'] = "O ficheiro foi adicionado com sucesso.";
$lang['DownloadManagerManagePlugin.!success.file_updated'] = "O ficheiro foi actualizado com sucesso.";
$lang['DownloadManagerManagePlugin.!success.file_deleted'] = "O ficheiro foi apagado com sucesso.";
$lang['DownloadManagerManagePlugin.!text.open_parenthesis'] = "(";
$lang['DownloadManagerManagePlugin.!text.forward_slash'] = "/";
$lang['DownloadManagerManagePlugin.!text.closed_parenthesis'] = ")";
$lang['DownloadManagerManagePlugin.modal.delete_file'] = "Tem a certeza que pretende apagar este ficheiro?";
$lang['DownloadManagerManagePlugin.index.boxtitle_downloadmanager'] = "Gestor de Downloads";
$lang['DownloadManagerManagePlugin.index.add_download'] = "Adicionar Download aqui";
$lang['DownloadManagerManagePlugin.index.add_category'] = "Adicionar Categoria aqui";
$lang['DownloadManagerManagePlugin.index.go_back'] = "Subir um nível";
$lang['DownloadManagerManagePlugin.index.edit'] = "Editar";
$lang['DownloadManagerManagePlugin.index.delete'] = "Apagar";
$lang['DownloadManagerManagePlugin.add.page_title'] = "Gestor de Downloads > Adicionar Download";
$lang['DownloadManagerManagePlugin.add.field_public'] = "Disponível Publicamente";
$lang['DownloadManagerManagePlugin.add.field_name'] = "Nome";
$lang['DownloadManagerManagePlugin.add.text_availableclientgroups'] = "Grupos de Clientes disponíveis";
$lang['DownloadManagerManagePlugin.add.text_availablepackages'] = "Pacotes Disponíveis";
$lang['DownloadManagerManagePlugin.add.field_path'] = "Especifique o caminho para o arquivo";
$lang['DownloadManagerManagePlugin.add.field_file'] = "Ficheiro";
$lang['DownloadManagerManagePlugin.add.field_file_name'] = "Caminho para o ficheiro";
$lang['DownloadManagerManagePlugin.add.submit_add'] = "Adicionar Download";
$lang['DownloadManagerManagePlugin.add.submit_cancel'] = "Cancelar";
$lang['DownloadManagerManagePlugin.edit.field_public'] = "Disponível publicamente";
$lang['DownloadManagerManagePlugin.edit.field_name'] = "Nome";
$lang['DownloadManagerManagePlugin.edit.field_available_to_client_groups'] = "Disponível para os grupos de clientes";
$lang['DownloadManagerManagePlugin.edit.field_available_to_packages'] = "Pacotes Disponíveis";
$lang['DownloadManagerManagePlugin.edit.text_clientgroups'] = "Grupos do cliente selecionado";
$lang['DownloadManagerManagePlugin.edit.text_packagegroups'] = "Pacotes Selecionados";
$lang['DownloadManagerManagePlugin.edit.text_availablepackages'] = "Pacotes Disponíveis";
$lang['DownloadManagerManagePlugin.edit.field_upload'] = "Carregar Ficheiro";
$lang['DownloadManagerManagePlugin.edit.field_file'] = "Ficheiro";
$lang['DownloadManagerManagePlugin.edit.submit_cancel'] = "Cancelar";
$lang['DownloadManagerManagePlugin.addcategory.boxtitle_root'] = "Adicionar Categoria a %1\$s"; // %1$s is the name of the root directory
$lang['DownloadManagerManagePlugin.addcategory.boxtitle_addcategory'] = "Adicionar Categoria à Categoria [%1\$s]"; // %1$s is the name of the category that this category is to be nested under
$lang['DownloadManagerManagePlugin.addcategory.submit_add'] = "Criar Categoria";
$lang['DownloadManagerManagePlugin.addcategory.submit_cancel'] = "Cancelar";
$lang['DownloadManagerManagePlugin.editcategory.page_title'] = "Gestor de Downloads > Atualizar Categoria";
$lang['DownloadManagerManagePlugin.editcategory.boxtitle_editcategory'] = "Atualizar Categoria [%1\$s]"; // %1$s is the name of the category
$lang['DownloadManagerManagePlugin.editcategory.field_name'] = "Nome";
$lang['DownloadManagerManagePlugin.editcategory.field_description'] = "Descrição";
$lang['DownloadManagerManagePlugin.editcategory.submit_edit'] = "Actualizar Categoria";
$lang['DownloadManagerManagePlugin.editcategory.submit_cancel'] = "Cancelar";
$lang['DownloadManagerManagePlugin.!text.root_directory'] = "Diretório inicial";
?>