<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['DownloadManagerCategories.!error.parent_id.exists'] = "A categoria pai selecionada não existe.";
$lang['DownloadManagerCategories.!error.name.empty'] = "Por favor introduza um nome de categoria.";
$lang['DownloadManagerCategories.!error.category_id.exists'] = "A categoria que está a ser atualizada não existe.";
?>