<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['DownloadManagerLogs.!error.file_id.exists'] = "O ficheiro não existe.";
$lang['DownloadManagerLogs.!error.client_id.exists'] = "O cliente não existe.";
$lang['DownloadManagerLogs.!error.contact_id.exists'] = "O contacto não existe.";
?>