<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ThesslstoreModule.add_credential_row'] = "Adicionar Credencial";
$lang['ThesslstoreModule.import_product_row'] = "Importar Pacotes";
$lang['ThesslstoreModule.add_row.box_title'] = "Definições";
$lang['ThesslstoreModule.setup_price.margin_percentage'] = "Margem de Lucro (em %)";
$lang['ThesslstoreModule.setup_price.update_success'] = "Preço atualizado com sucesso.";
$lang['ThesslstoreModule.credential_row.add_btn'] = "Gravar";
$lang['ThesslstoreModule.change_approver_email.save_btn'] = "Gravar";
$lang['ThesslstoreModule.tab_CertDetails'] = "Detalhes do Certificado";
$lang['ThesslstoreModule.tab_client_cert_details'] = "Detalhes de Certificado";
$lang['ThesslstoreModule.tab_client_cert_details.token'] = "Token";
$lang['ThesslstoreModule.tab_client_cert_details.admin_first_name'] = "Primeiro Nome";
$lang['ThesslstoreModule.tab_client_cert_details.admin_last_name'] = "Último Nome";
$lang['ThesslstoreModule.tab_client_cert_details.tech_details'] = "Detalhes Técnicos";
$lang['ThesslstoreModule.tab_client_cert_details.tech_first_name'] = "Primeiro Nome";
$lang['ThesslstoreModule.tab_client_cert_details.tech_email'] = "Email";
$lang['ThesslstoreModule.tab_client_cert_details.tech_phone'] = "Telefone";
$lang['ThesslstoreModule.tab_reissue_cert.heading'] = "Re-emitir Certificado";
$lang['ThesslstoreModule.tab_GenerateCert'] = "Gerar Certificado";
$lang['ThesslstoreModule.tab_generate_cert.heading_step3'] = "Configuração Completa";
$lang['ThesslstoreModule.tab_generate_cert.heading_server'] = "Informação do Servidor";
$lang['ThesslstoreModule.service_field.thesslstore_admin_title'] = "Título";
$lang['ThesslstoreModule.service_field.thesslstore_org_name'] = "Nome da Organização";
$lang['ThesslstoreModule.service_field.thesslstore_admin_state'] = "Estado/Região";
$lang['ThesslstoreModule.service_field.thesslstore_admin_country'] = "País";
$lang['ThesslstoreModule.service_field.thesslstore_admin_zip'] = "Código Postal";
$lang['ThesslstoreModule.service_field.thesslstore_tech_first_name'] = "Primeiro Nome";
$lang['ThesslstoreModule.service_field.thesslstore_tech_last_name'] = "Último Nome";
$lang['ThesslstoreModule.service_field.thesslstore_tech_title'] = "Título";
$lang['ThesslstoreModule.service_field.thesslstore_tech_email'] = "Endereço de Email";
$lang['ThesslstoreModule.tab_generate_cert_step1.submit'] = "Submeter";
$lang['ThesslstoreModule.!error.thesslstore_auth_method.empty'] = "Por favor escolha um Método de Autenticação";
$lang['ThesslstoreModule.!error.thesslstore_admin_first_name.empty'] = "Por favor introduza o Primeiro Nome do Admin";
$lang['ThesslstoreModule.!error.thesslstore_admin_last_name.empty'] = "Por favor introduza o Último Nome do Administrador";
$lang['ThesslstoreModule.!error.thesslstore_admin_address1.empty'] = "Por favor introduza um Endereço";
?>