<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMain.index.boxtitle_services'] = "Serviços do Cliente #%1\$s"; // %1$s is the client ID code
$lang['AdminMain.index.link_client'] = "Voltar ao Cliente #%1\$s"; // %1$s is the client ID code
$lang['AdminMain.index.heading_package'] = "Pacote";
$lang['AdminMain.index.heading_term'] = "Termo";
$lang['AdminMain.index.heading_date_created'] = "Data de Criação";
$lang['AdminMain.index.heading_date_renews'] = "Data de Renovação";
$lang['AdminMain.index.heading_options'] = "Opções";
$lang['AdminMain.index.recurring_term'] = "%1\$s %2\$s @ %3\$s"; // %1$s is the term, %2$s is the period, %3$s is the renewal price
$lang['AdminMain.index.text_never'] = "Nunca";
$lang['AdminMain.service.term'] = "%1\$s %2\$s - %3\$s"; // %1$s is the pricing term, %2$s is the pricing period, and %3$s is the formatted price
$lang['AdminMain.service.heading_information'] = "Informação do Serviço";
$lang['AdminMain.service.text_label'] = "Etiqueta:";
$lang['AdminMain.service.text_qty'] = "Quantidade:";
$lang['AdminMain.service.text_term'] = "Termo:";
$lang['AdminMain.service.text_status'] = "Nome do Pacote:";
$lang['AdminMain.service.text_date_added'] = "Data de Adição:";
$lang['AdminMain.service.text_date_renews'] = "Data de Renovação:";
$lang['AdminMain.service.text_renewal_price'] = "Preço de renovação:";
$lang['AdminMain.service.field_pricing'] = "Pacote/Termo";
$lang['AdminMain.service.field_submit'] = "Gravar";
?>