<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Quantum_gateway.restrict_key'] = "Chave Restrita";
$lang['Quantum_gateway.maxmind'] = "Usar Maxmind";
$lang['Quantum_gateway.tooltip_maxmind'] = "Seleccione a caixa para activar o Maxmind para controlo de fraude. Verifique o seu painel de controlo QuantumGateway , para opções Maxmind adicionais.";
?>