<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AgingInvoices.options.field_status'] = "Estado";
$lang['AgingInvoices.option.any'] = "Qualquer";
$lang['AgingInvoices.heading.id_code'] = "Fatura #";
$lang['AgingInvoices.heading.client_id_code'] = "Cliente #";
$lang['AgingInvoices.heading.subtotal'] = "Subtotal";
$lang['AgingInvoices.heading.paid'] = "Pago";
$lang['AgingInvoices.heading.currency'] = "Moeda";
$lang['AgingInvoices.heading.status'] = "Estado";
$lang['AgingInvoices.heading.date_due'] = "Data de Vencimento";
$lang['AgingInvoices.heading.past30'] = "30";
$lang['AgingInvoices.heading.past60'] = "60";
$lang['AgingInvoices.heading.past90'] = "90+";
$lang['AgingInvoices.heading.client_first_name'] = "Primeiro Nome do Cliente";
$lang['AgingInvoices.heading.client_last_name'] = "Último Nome do Cliente";
$lang['AgingInvoices.heading.client_email'] = "Email de Cliente";
?>