<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PaypalPaymentsStandard.account_id'] = "Email da Conta PayPal";
$lang['PaypalPaymentsStandard.dev_mode'] = "Modo de programador";
$lang['PaypalPaymentsStandard.dev_mode_note'] = "Ao ativar esta opção irá publicar as transações para o ambiente do Sandbox do PayPal. Apenas habilite esta opção se estiver a testar com uma conta da Sandbox do PayPal.";
$lang['PaypalPaymentsStandard.api_username'] = "Username da API";
$lang['PaypalPaymentsStandard.api_password'] = "Palavra-passe de API";
$lang['PaypalPaymentsStandard.api_signature'] = "Assinatura API";
$lang['PaypalPaymentsStandard.buildprocess.submit'] = "Pagar com PayPal";
$lang['PaypalPaymentsStandard.!error.account_id.valid'] = "Tem de introduzir um endereço email válido.";
$lang['PaypalPaymentsStandard.!error.dev_mode.valid'] = "O modo de desenvolvimento deve ser definido como \"Verdadeiro\" se questionado.";
?>