<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PayJunction.name'] = "PayJunction";
$lang['PayJunction.api_key'] = "Chave API";
$lang['PayJunction.user_name'] = "Nome de Utilizador";
$lang['PayJunction.password'] = "Password";
$lang['PayJunction.test_mode'] = "Modo de Desenvolvedor";
$lang['PayJunction.password_note'] = "Introduza a sua palavra-passe da conta PayJunction.";
$lang['PayJunction.!error.api_key.empty'] = "Por favor introduza uma Chave de API válida.";
$lang['PayJunction.!error.user_name.empty'] = "Por favor introduza o nome de utilizador da sua conta.";
$lang['PayJunction.!error.password.empty'] = "Por favor introduza a palavra-passe da sua conta.";
?>