<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Upload.!error.max_file_size'] = "O ficheiro excede o tamanho máximo de ficheiro permitido.";
$lang['Upload.!error.file_exists'] = "O ficheiro já existe.";
?>