<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['DirectAdmin.!error.password.format'] = "Tem de introduzir uma Palavra-passe.";
$lang['DirectAdmin.!error.account_limit.valid'] = "O Limite da conta deve ser deixado em branco (para contas ilimitadas) ou definida para algum valor inteiro.";
$lang['DirectAdmin.!error.name_servers.valid'] = "Um ou mais name servers introduzidos são inválidos.";
$lang['DirectAdmin.!error.name_servers.count'] = "Tem de definir pelo menos 2 name servers.";
$lang['DirectAdmin.!error.api.internal'] = "Ocorreu um erro interno ou o servidor não respondeu ao pedido.";
$lang['DirectAdmin.!error.meta[type].format'] = "O Tipo de Conta deve ser Utilizador ou Revendedor.";
$lang['DirectAdmin.!error.direct_admin_username.format'] = "O nome de utilizador deve conter apenas caracteres alfanuméricos.";
$lang['DirectAdmin.!error.direct_admin_password.format'] = "A palavra-passe só pode conter caracteres ASCII.";
$lang['DirectAdmin.!error.direct_admin_email.format'] = "Por favor introduza um endereço de email válido.";
$lang['DirectAdmin.name'] = "DirectAdmin";
$lang['DirectAdmin.module_row'] = "Servidor";
$lang['DirectAdmin.module_row_plural'] = "Servidores";
$lang['DirectAdmin.tab_stats'] = "Estatísticas";
$lang['DirectAdmin.servers.no_results'] = "Não existem servidores.";
$lang['DirectAdmin.server_groups.no_results'] = "Não existem grupos de servidores";
$lang['DirectAdmin.service_field.domain'] = "Domínio";
$lang['DirectAdmin.service_field.username'] = "Nome de utilizador";
$lang['DirectAdmin.service_field.password'] = "Palavra-passe";
$lang['DirectAdmin.service_field.email'] = "Email";
$lang['DirectAdmin.service_info.username'] = "Nome de utilizador";
$lang['DirectAdmin.service_info.password'] = "Palavra-passe";
$lang['DirectAdmin.service_info.server'] = "Servidor";
$lang['DirectAdmin.service_info.options'] = "Opções";
$lang['DirectAdmin.package_fields.type'] = "Tipo de conta";
$lang['DirectAdmin.package_fields.type_user'] = "Utilizador";
$lang['DirectAdmin.package_fields.type_reseller'] = "Revendedor";
$lang['DirectAdmin.package_fields.ip'] = "Endereço IP";
$lang['DirectAdmin.package_fields.ip_shared'] = "Partilhado";
$lang['DirectAdmin.add_module_row'] = "Adicionar Servidor";
$lang['DirectAdmin.add_module_group'] = "Adicionar Grupo de Servidores";
$lang['DirectAdmin.manage.module_rows_title'] = "Servidores";
$lang['DirectAdmin.manage.module_groups_title'] = "Grupos de servidores";
$lang['DirectAdmin.manage.module_rows_heading.name'] = "Etiqueta do Servidor";
$lang['DirectAdmin.manage.module_rows_heading.accounts'] = "Contas";
$lang['DirectAdmin.manage.module_rows_heading.options'] = "Opções";
$lang['DirectAdmin.manage.module_groups_heading.name'] = "Nome do Grupo";
$lang['DirectAdmin.manage.module_groups_heading.servers'] = "Contagem de Servidores";
$lang['DirectAdmin.manage.module_groups_heading.options'] = "Opções";
$lang['DirectAdmin.manage.module_rows.count'] = "%1\$s / %2\$s"; // %1$s is the current number of accounts, %2$s is the total number of accounts available
$lang['DirectAdmin.manage.module_rows.edit'] = "Editar";
$lang['DirectAdmin.manage.module_groups.edit'] = "Editar";
$lang['DirectAdmin.manage.module_rows.delete'] = "Apagar";
$lang['DirectAdmin.manage.module_rows.confirm_delete'] = "Tem a certeza de que quer apagar este servidor?";
$lang['DirectAdmin.manage.module_groups.confirm_delete'] = "Tem a certeza de que quer apagar este grupo de servidores?";
$lang['DirectAdmin.row_meta.server_name'] = "Nome do Servidor";
$lang['DirectAdmin.row_meta.user_name'] = "Nome de utilizador";
$lang['DirectAdmin.row_meta.password'] = "Palavra-Passe";
$lang['DirectAdmin.row_meta.account_limit'] = "Limite da conta";
$lang['DirectAdmin.add_row.box_title'] = "Adicionar Servidor DirectAdmin";
$lang['DirectAdmin.add_row.name_server_btn'] = "Adicionar Name Server Adicional";
$lang['DirectAdmin.add_row.name_server_col'] = "Name Server";
$lang['DirectAdmin.add_row.remove_name_server'] = "Remover";
$lang['DirectAdmin.add_row.notes_title'] = "Notas";
$lang['DirectAdmin.add_row.add_btn'] = "Adicionar Servidor";
$lang['DirectAdmin.edit_row.name_servers_title'] = "Name Servers";
$lang['DirectAdmin.edit_row.name_server_btn'] = "Adicionar um Nameserver adicional";
$lang['DirectAdmin.edit_row.name_server_host_col'] = "Hostname";
$lang['DirectAdmin.edit_row.remove_name_server'] = "Remover";
$lang['DirectAdmin.edit_row.notes_title'] = "Notas";
$lang['DirectAdmin.edit_row.add_btn'] = "Editar Servidor";
$lang['DirectAdmin.tab_client_stats'] = "Estatísticas";
$lang['DirectAdmin.tab_client_stats.info_title'] = "Informação";
$lang['DirectAdmin.tab_client_stats.info_heading.field'] = "Campo";
$lang['DirectAdmin.tab_client_stats.info_heading.value'] = "Valor";
$lang['DirectAdmin.tab_client_actions'] = "Ações";
$lang['DirectAdmin.order_options.first'] = "Primeiro Servidor Não Cheio";
$lang['DirectAdmin.tab_client_actions.change_password'] = "Alterar Password";
$lang['DirectAdmin.tab_client_actions.field_direct_admin_confirm_password'] = "Confirmar Password";
$lang['DirectAdmin.tab_client_actions.field_password_submit'] = "Atualizar Password";
?>