<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['CmsManagePlugin.!success.plugin_updated'] = "O Portal foi atualizado com sucesso.";
$lang['CmsManagePlugin.index.page_title'] = "Portal > Gerir";
$lang['CmsManagePlugin.index.boxtitle_portal'] = "Portal";
$lang['CmsManagePlugin.index.field_submit'] = "Atualizar Página";
?>