<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['_2Checkout.name'] = "2Checkout";
$lang['_2Checkout.vendor_id'] = "Número de Conta do Fornecedor";
$lang['_2Checkout.secret_word'] = "Secret Word";
$lang['_2Checkout.api_username'] = "API Username";
$lang['_2Checkout.api_username_note'] = "Assim como a password da API, são necessárias para processar reembolsos através do 2Checkout.";
$lang['_2Checkout.api_password'] = "API Password";
$lang['_2Checkout.test_mode'] = "Modo Teste";
$lang['2Checkout.refund.comment'] = "Iniciando um reembolso no valor de %1\$s."; // %1$s is the refund amount
$lang['_2Checkout.buildprocess.submit'] = "Pagar através do 2Checkout";
$lang['_2Checkout.!error.vendor_id.empty'] = "Por favor, insira o seu número de conta do fornecedor.";
$lang['_2Checkout.!error.secret_word.empty'] = "Introduza a Chave Secreta";
$lang['_2Checkout.!error.test_mode.valid'] = "O modo Teste tem deverá ser 'true' ou 'false'.";
$lang['_2Checkout.!error.key.valid'] = "A chave utilizada para verificar a compra originada pelo 2Checkout é inválida";
$lang['_2Checkout.!error.credit_card_processed.completed'] = "Ocorreu um erro ao executar a compra";
$lang['_2Checkout.!error.sid.valid'] = "O número da conta do fornecedor não coincide com o número da conta fornecido pela transação";
?>