<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Cpanel.name'] = "cPanel";
$lang['Cpanel.module_row'] = "Servidor";
$lang['Cpanel.module_group'] = "Grupo de Servidores";
$lang['Cpanel.add_module_row'] = "Adicionar Servidor";
$lang['Cpanel.add_module_group'] = "Adicionar Grupo de Servidor";
$lang['Cpanel.manage.module_rows_title'] = "Servidores";
$lang['Cpanel.manage.module_groups_title'] = "Grupo de Servidores";
$lang['Cpanel.manage.module_rows_heading.hostname'] = "Hostname";
$lang['Cpanel.manage.module_rows_heading.accounts'] = "Contas";
$lang['Cpanel.manage.module_rows_heading.options'] = "Opções";
$lang['Cpanel.manage.module_groups_heading.servers'] = "Contagem Servidor";
$lang['Cpanel.manage.module_groups_heading.options'] = "Opções";
$lang['Cpanel.manage.module_rows.edit'] = "Editar";
$lang['Cpanel.manage.module_groups.edit'] = "Editar";
$lang['Cpanel.manage.module_rows.delete'] = "Apagar";
$lang['Cpanel.manage.module_groups.delete'] = "Apagar";
$lang['Cpanel.manage.module_rows.confirm_delete'] = "Tem certeza de que deseja apagar este servidor?";
$lang['Cpanel.manage.module_groups.confirm_delete'] = "Tem a certeza de que quer apagar este grupo de servidores?";
$lang['Cpanel.package_fields.package'] = "Pacote cPanel";
$lang['Cpanel.add_row.box_title'] = "Adicionar Servidor cPanel";
$lang['Cpanel.add_row.basic_title'] = "Definições Básicas";
$lang['Cpanel.add_row.name_servers_title'] = "Name Servers";
$lang['Cpanel.add_row.notes_title'] = "Notas";
$lang['Cpanel.add_row.name_server_btn'] = "Adicionar Name Server adicional";
$lang['Cpanel.add_row.name_server_col'] = "Name Server";
$lang['Cpanel.add_row.name_server_host_col'] = "Hostname";
$lang['Cpanel.add_row.name_server'] = "Name server %1\$s"; // %1$s is the name server number (e.g. 3)
$lang['Cpanel.add_row.remove_name_server'] = "Remover";
$lang['Cpanel.edit_row.box_title'] = "Editar Servidor cPanel";
$lang['Cpanel.edit_row.basic_title'] = "Definições Básicas";
$lang['Cpanel.edit_row.notes_title'] = "Notas";
$lang['Cpanel.edit_row.name_server_btn'] = "Adicionar Name Server adicional";
$lang['Cpanel.edit_row.name_server_col'] = "Name Server";
$lang['Cpanel.edit_row.name_server_host_col'] = "Hostname";
$lang['Cpanel.edit_row.name_server'] = "Nome do Servidor %1\$s"; // %1$s is the name server number (e.g. 3)
$lang['Cpanel.edit_row.add_btn'] = "Editar Servidor";
$lang['Cpanel.row_meta.server_name'] = "Etiqueta do Servidor";
$lang['Cpanel.row_meta.host_name'] = "Hostname";
$lang['Cpanel.!error.name_servers_count'] = "Tem de definir pelo menos 2 Name Servers.";
$lang['Cpanel.tab_stats'] = "Estatísticas";
$lang['Cpanel.package_fields.type'] = "Tipo de Conta";
$lang['Cpanel.package_fields.type_standard'] = "Padrão";
$lang['Cpanel.package_fields.type_reseller'] = "Revendedor";
$lang['Cpanel.package_fields.acl'] = "Lista de Controlo de Acesso";
$lang['Cpanel.package_fields.acl_default'] = "Predefinido";
$lang['Cpanel.service_field.domain'] = "Domínio";
$lang['Cpanel.service_field.username'] = "Nome de utilizador";
$lang['Cpanel.service_field.password'] = "Password";
$lang['Cpanel.tab_stats.info_title'] = "Informação";
$lang['Cpanel.tab_stats.info_heading.value'] = "Valor";
$lang['Cpanel.tab_stats.info.domain'] = "Domínio";
$lang['Cpanel.tab_stats.bandwidth_heading.used'] = "Usado";
$lang['Cpanel.tab_stats.bandwidth_heading.limit'] = "Limite";
$lang['Cpanel.tab_stats.bandwidth_unlimited'] = "Ilimitado";
$lang['Cpanel.tab_stats.disk_title'] = "Disco";
$lang['Cpanel.tab_stats.disk_heading.limit'] = "Limite";
$lang['Cpanel.tab_stats.disk_value'] = "%1\$s MB"; // %1$s is the amount of disk in MB
$lang['Cpanel.tab_stats.disk_unlimited'] = "ilimitado";
$lang['Cpanel.service_info.username'] = "Username";
$lang['Cpanel.service_info.password'] = "Password";
$lang['Cpanel.service_info.server'] = "Servidor";
$lang['Cpanel.service_info.options'] = "Opções";
$lang['Cpanel.!error.meta[type].valid'] = "O tipo de conta tem de ser normal ou revendedor.";
$lang['Cpanel.!error.meta[package].empty'] = "Um Pacote cPanel é necessário.";
$lang['Cpanel.!error.api.internal'] = "Ocorreu um erro interno ou o servidor não responder ao pedido.";
$lang['Cpanel.tab_client_stats'] = "Estatísticas";
$lang['Cpanel.manage.module_rows_no_results'] = "Não existem servidores.";
$lang['Cpanel.manage.module_groups_no_results'] = "Não existem grupos de servidores.";
$lang['Cpanel.service_field.confirm_password'] = "Confirmar Palavra-passe";
$lang['Cpanel.tab_client_stats.info_title'] = "Informação";
$lang['Cpanel.tab_client_stats.info_heading.field'] = "Campos";
$lang['Cpanel.tab_client_stats.info_heading.value'] = "Valor";
$lang['Cpanel.tab_client_stats.info.domain'] = "Domínio";
$lang['Cpanel.tab_client_stats.info.ip'] = "Endereço IP";
$lang['Cpanel.!error.cpanel_domain.format'] = "Por favor introduza um nome de domínio válido, ex. dominio.com.";
$lang['Cpanel.!error.cpanel_domain.test'] = "O nome do domínio não pode começar por 'test'.";
$lang['Cpanel.!error.cpanel_username.length'] = "O nome de utilizador deve ter entre 1 e 16 caracteres de comprimento.";
$lang['Cpanel.!error.cpanel_password.valid'] = "A Palavra-passe deve ter pelo menos 8 caracteres de comprimento.";
$lang['Cpanel.!error.cpanel_password.matches'] = "A Password e a Confirmação da Password não coincidem.";
$lang['Cpanel.service_field.tooltip.password'] = "Pode deixar a palavra-passe em branco para gerar automaticamente uma.";
$lang['Cpanel.tab_client_stats.usage'] = "(%1\$s MB/%2\$s MB)"; // %1$s is the amount of resource usage, %2$s is the resource usage limit
$lang['Cpanel.tab_client_actions'] = "Ações";
$lang['Cpanel.tab_client_actions.change_password'] = "Alterar Palavra-passe";
$lang['Cpanel.tab_client_actions.field_cpanel_password'] = "Palavra-passe";
$lang['Cpanel.tab_client_actions.field_password_submit'] = "Atualizar Password";
$lang['Cpanel.tab_client_stats.usage_unlimited'] = "(%1\$s MB/?)"; // %1$s is the amount of resource usage
?>