<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PricingPresenter.nested_identifier'] = "?";
$lang['PricingPresenter.description.coupon.amount'] = "Cupão %1\$s (%2\$s)"; // %1$s is the coupon code, %2$s is the formatted coupon amount
$lang['PricingPresenter.description.coupon.percent'] = "Cupão %1\$s (%2\$s%%)"; // %1$s is the coupon code, %2$s is the coupon percentage amount
$lang['PricingPresenter.description.package'] = "%1\$s"; // %1$s is the name of the package
$lang['PricingPresenter.description.service'] = "%1\$s - %2\$s"; // %1$s is the name of the package, %2$s is the name of the service
$lang['PricingPresenter.description.service.option'] = "%1\$s - %2\$s"; // %1$s is the package option label, %2$s is the package option name
$lang['PricingPresenter.description.service.option.qty'] = "%1\$s - %1\$sx %1\$s"; // %1$s is the package option label, %2$s is the package option quantity, %3$s is the package option name
$lang['PricingPresenter.description.service.option.setup_fee'] = "%1\$s - %2\$s Taxa de Instalação"; // %1$s is the package option label, %2$s is the package option name
?>