<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Ccavenue.name'] = "Pagamento via CCAvenue";
$lang['Ccavenue.buildprocess.submit'] = "Pagar via CCAvenue";
$lang['Ccavenue.!error.security.response'] = "Erro de Segurança. Acesso ilegal detetado.";
$lang['Ccavenue.!error.authentication.log'] = "A transação foi recusada pelo banco.";
$lang['Ccavenue.encryption_key'] = "Chave de Encriptação";
$lang['Ccavenue.access_code'] = "Código de Acesso";
$lang['Ccavenue.test_mode'] = "Modo de Teste";
$lang['Ccavenue.!error.encryption_key.valid'] = "Por favor introduza uma chave de encriptação.";
$lang['Ccavenue.merchant_id'] = "ID de Mercador";
?>