<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMain.!success.document_uploaded'] = "O documento foi carregado.";
$lang['AdminMain.!success.document_deleted'] = "O documento foi apagado.";
$lang['AdminMain.index.page_title'] = "Codumentos";
$lang['AdminMain.add.page_title'] = "Documentos > Adicionar";
$lang['AdminMain.index.categorylink_adddocument'] = "Adicionar documento";
$lang['AdminMain.index.boxtitle_client'] = "Cliente #%1\$s - %2\$s %3\$s";
$lang['AdminMain.index.boxtitle_documents'] = "Documentos";
$lang['AdminMain.index.heading_name'] = "Nome";
$lang['AdminMain.index.heading_description'] = "Descrição";
$lang['AdminMain.index.heading_date_options'] = "Opções";
$lang['AdminMain.index.option_delete'] = "Apagar";
$lang['AdminMain.index.option_download'] = "Download";
$lang['AdminMain.modal.delete_document'] = "Apagar este documento?";
$lang['AdminMain.add.boxtitle_adddocument'] = "Upload de Documento";
$lang['AdminMain.add.field_name'] = "Nome";
$lang['AdminMain.add.field_document'] = "Documento";
$lang['AdminMain.add.field_description'] = "Descrição";
?>