<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientMain.index.page_title'] = "Documentos";
$lang['ClientMain.index.boxtitle_documents'] = "Documentos";
$lang['ClientMain.index.heading_description'] = "Descrição";
$lang['ClientMain.index.heading_date_added'] = "Data de Entrada";
$lang['ClientMain.index.heading_options'] = "Opções";
$lang['ClientMain.index.option_download'] = "Download";
?>