<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Checkout.ach_info.heading_ach'] = "Informações de Conta Bancária";
$lang['Checkout.complete.header_almost_complete'] = "Quase lá...";
?>