<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Domain.lookup.domains_header_unavailable'] = "Desculpe, esse domínio não está disponível.";
$lang['Domain.lookup.domains_domain_name'] = "Nome de Domínio";
$lang['Domain.lookup.domains_term'] = "Termo";
?>