<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Interworx.name'] = "Interworx";
$lang['Interworx.module_row'] = "Servidor";
$lang['Interworx.module_row_plural'] = "Servidores";
$lang['Interworx.tab_stats'] = "Estatísticas";
$lang['Interworx.add_module_row'] = "Adicionar Servidor";
$lang['Interworx.add_module_group'] = "Adicionar Grupo de Servidores";
$lang['Interworx.manage.module_rows_title'] = "Servidores";
$lang['Interworx.manage.module_groups_title'] = "Grupos de Servidores";
$lang['Interworx.manage.module_rows_heading.hostname'] = "Hostname";
$lang['Interworx.manage.module_rows_heading.accounts'] = "Contas";
$lang['Interworx.manage.module_rows_heading.options'] = "Opções";
$lang['Interworx.manage.module_groups_heading.servers'] = "Contagem de Servidores";
$lang['Interworx.manage.module_groups_heading.options'] = "Opções";
$lang['Interworx.manage.module_rows.count'] = "%1\$s / %2\$s"; // %1$s is the current number of accounts, %2$s is the total number of accounts available
$lang['Interworx.manage.module_rows.edit'] = "Editar";
$lang['Interworx.manage.module_groups.edit'] = "Editar";
$lang['Interworx.manage.module_rows.delete'] = "Apagar";
$lang['Interworx.manage.module_groups.delete'] = "Apagar";
$lang['Interworx.manage.module_groups.confirm_delete'] = "Tem a certeza que quer apagar este grupo de servidores?";
$lang['Interworx.manage.module_rows_no_results'] = "Não existem servidores.";
$lang['Interworx.manage.module_groups_no_results'] = "Não existem grupos de servidores.";
$lang['Interworx.add_row.basic_title'] = "Configurações Básicas";
$lang['Interworx.add_row.name_servers_title'] = "Nameservers";
$lang['Interworx.add_row.notes_title'] = "Notas";
$lang['Interworx.add_row.name_server_btn'] = "Adicionar Name Server Adicional";
$lang['Interworx.add_row.name_server_col'] = "Name Server";
$lang['Interworx.add_row.name_server_host_col'] = "Hostname";
$lang['Interworx.add_row.name_server'] = "Name server %1\$s"; // %1$s is the name server number (e.g. 3)
$lang['Interworx.add_row.remove_name_server'] = "Remover";
$lang['Interworx.add_row.add_btn'] = "Adicionar Servidor";
$lang['Interworx.edit_row.box_title'] = "Editar Servidor Interworx";
$lang['Interworx.edit_row.basic_title'] = "Definições Básicas";
$lang['Interworx.edit_row.name_servers_title'] = "Servidores de Domínio";
$lang['Interworx.edit_row.notes_title'] = "Notas";
$lang['Interworx.edit_row.name_server_btn'] = "Adicionar Name Server Adicional";
$lang['Interworx.edit_row.name_server_col'] = "Name Server";
$lang['Interworx.edit_row.name_server'] = "Name Server %1\$s"; // %1$s is the name server number (e.g. 3)
$lang['Interworx.edit_row.remove_name_server'] = "Remover";
$lang['Interworx.edit_row.add_btn'] = "Editar Servidor";
$lang['Interworx.row_meta.host_name'] = "Hostname";
$lang['Interworx.row_meta.port'] = "Numero da Porta";
$lang['Interworx.row_meta.default_port'] = "2443";
$lang['Interworx.row_meta.key'] = "Chave remota";
$lang['Interworx.row_meta.account_limit'] = "Limite de Conta";
$lang['Interworx.row_meta.debug'] = "Depuração";
$lang['Interworx.row_meta.debug.none'] = "Nenhum";
$lang['Interworx.row_meta.debug.log'] = "Registo";
$lang['Interworx.row_meta.debug.print'] = "Imprimir";
$lang['Interworx.package_fields.type'] = "Tipo de Conta";
$lang['Interworx.package_fields.type_standard'] = "Padrão";
$lang['Interworx.package_fields.type_reseller'] = "Revendedor";
$lang['Interworx.service_field.domain'] = "Domínio";
$lang['Interworx.service_field.username'] = "Username";
$lang['Interworx.service_field.email'] = "Email";
$lang['Interworx.service_field.password'] = "Palavra-passe";
$lang['Interworx.tab_stats.info_title'] = "Informação";
$lang['Interworx.tab_stats.info_heading.field'] = "Campo";
$lang['Interworx.tab_stats.info_heading.value'] = "Valor";
$lang['Interworx.tab_stats.info.server'] = "Servidor";
$lang['Interworx.tab_stats.info.domain'] = "Domínio";
$lang['Interworx.tab_stats.bandwidth_heading.used'] = "Usado";
$lang['Interworx.tab_stats.bandwidth_heading.limit'] = "Limite";
$lang['Interworx.tab_stats.bandwidth_unlimited'] = "Ilimitado";
$lang['Interworx.tab_stats.disk_title'] = "Disco";
$lang['Interworx.tab_stats.disk_heading.used'] = "Usado";
$lang['Interworx.tab_stats.disk_heading.limit'] = "Limite";
$lang['Interworx.tab_stats.disk_value'] = "%1\$s MB"; // %1$s is the amount of disk in MB
$lang['Interworx.tab_stats.disk_unlimited'] = "Ilimitado";
$lang['Interworx.tab_stats.package_title'] = "Informações do Pacote";
$lang['Interworx.tab_stats.package_info.id'] = "ID";
$lang['Interworx.tab_stats.package_info.name'] = "Nome";
$lang['Interworx.tab_stats.package_info.opt_storage'] = "Espaço de Disco";
$lang['Interworx.tab_stats.package_info.opt_email_boxes'] = "Contas de Email";
$lang['Interworx.tab_stats.package_info.opt_ftp_accounts'] = "Contas FTP";
$lang['Interworx.tab_stats.package_info.opt_mysql_dbs'] = "Bases de Dados MySQL";
$lang['Interworx.tab_stats.package_info.opt_mysql_db_users'] = "Utilizadores MySQL";
$lang['Interworx.tab_stats.package_info.opt_subdomains'] = "Sub-Domínios";
$lang['Interworx.tab_stats.package_info.opt_backup'] = "Cópias de Segurança Ativas";
$lang['Interworx.tab_stats.package_info.opt_cgi_access'] = "Acesso CGI";
$lang['Interworx.tab_stats.package_info.opt_dns_records'] = "Acesso DNS";
$lang['Interworx.tab_stats.package_info.opt_ssl'] = "SSL";
$lang['Interworx.tab_stats.package_info.opt_save_xfer_logs'] = "Salvar Logs XFER";
$lang['Interworx.tab_stats.package_info.opt_unlimited'] = "Ilimitado";
$lang['Interworx.service_info.email'] = "Email";
$lang['Interworx.service_info.password'] = "Palavra-passe";
$lang['Interworx.service_info.server'] = "Servidor";
$lang['Interworx.service_info.options'] = "Opções";
$lang['Interworx.service_info.option_login'] = "Entrar";
$lang['Interworx.!error.host_name_valid'] = "O Hostname parece ser inválido.";
$lang['Interworx.!error.remote_key_valid'] = "A chave remota parece estar inválida.";
$lang['Interworx.!error.meta[type].valid'] = "O tipo de conta tem de ser normal ou revendedor.";
$lang['Interworx.!error.meta[package].empty'] = "Um Pacote Interworx é necessário.";
$lang['Interworx.!error.interworx_password.format'] = "Por favor introduza uma palavra-passe.";
$lang['Interworx.!error.interworx_password.length'] = "A palavra-passe tem de ter pelo menos 6 caracteres de comprimentos.";
$lang['Interworx.!error.interworx_email.format'] = "Por favor introduza um endereço de email válido.";
$lang['Interworx.!error.api.create_account.missing_fields'] = "Crear Conta exige um nome de usuário, email, password, e um domínio.";
$lang['Interworx.!error.api.duplicate_username'] = "Nome de utilizador duplicado, esse nome de utilizador já existe. Por favor escolha outro nome de utilizador.";
$lang['Interworx.!error.api.no_reseller_access'] = "Esta chamada de API não está disponível para revendedores. Deve ser o administrador.";
$lang['Interworx.service_field.confirm_password'] = "Confirmar Palavra-passe";
$lang['Interworx.!error.interworx_confirm_password.matches'] = "As passwords não correspondem.";
$lang['Interworx.!error.libxml_required'] = "A extensão libxml é necessária para este módulo.";
$lang['Interworx.service_field.reseller_id'] = "ID de Revendedor";
$lang['Interworx.tab_unavailable.message'] = "Esta informação ainda não está disponível.";
$lang['Interworx.tab_client_actions.change_password'] = "Alterar Palavra-passe";
$lang['Interworx.tab_client_actions.field_interworx_password'] = "Palavra-passe";
$lang['Interworx.tab_client_actions.field_interworx_confirm_password'] = "Confirmar Password";
$lang['Interworx.tab_client_actions.field_password_submit'] = "Atualizar Palavra-passe";
$lang['Interworx.tab_stats.bandwidth_value'] = "%1\$s GB"; // %1$s is the amount of bandwidth in GB
?>