<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['MulticraftPackage.!error.meta[server_name].format'] = "Por favor defina um nome para o servidor.";
$lang['MulticraftPackage.package_fields.server_name'] = "Nome do Servidor";
$lang['MulticraftPackage.package_fields.players'] = "Slots de Jogadores";
$lang['MulticraftPackage.package_fields.jarfile'] = "Ficheiro JAR";
$lang['MulticraftPackage.package_fields.tooltip.jarfile'] = "Deixe em branco para usar o ficheiro JAR predefinido.";
$lang['MulticraftPackage.package_fields.jardir_server'] = "Pasta do JAR do Servidor";
$lang['MulticraftPackage.package_fields.tooltip.user_name'] = "Especifica se o proprietário pode definir ou mudar o nome do servidor.";
$lang['MulticraftPackage.package_fields.user_ftp'] = "Dono pode gerir FTP";
$lang['MulticraftPackage.package_fields.tooltip.user_ftp'] = "Define se o proprietário pode fornecer acesso FTP a outros utilizadores.";
$lang['MulticraftPackage.package_fields.default_level'] = "Regra Pré-Definida";
$lang['MulticraftPackage.package_fields.default_level_0'] = "Sem acesso";
$lang['MulticraftPackage.package_fields.default_level_20'] = "Utilizador";
$lang['MulticraftPackage.package_fields.default_level_30'] = "Moderador";
$lang['MulticraftPackage.package_fields.autostart'] = "Iniciar Servidor";
$lang['MulticraftPackage.package_fields.create_ftp'] = "Criar Conta FTP";
$lang['MulticraftPackage.package_fields.tooltip.create_ftp'] = "Cria uma conta FTP automaticamente.";
$lang['MulticraftPackage.package_fields.server_visibility'] = "Visibilidade do Servidor";
$lang['MulticraftPackage.package_fields.server_visibility_1'] = "Por função padrão";
?>