<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['MulticraftService.!error.server_id.format'] = "O ID do servidor deve ser um inteiro ou deixado em branco.";
$lang['MulticraftService.!error.ip.format'] = "Por favor introduza um endereço IP válido ou deixe em branco.";
$lang['MulticraftService.service_fields.server_id'] = "ID do Servidor";
$lang['MulticraftService.service_fields.user_id'] = "ID de Utilizador";
$lang['MulticraftService.service_fields.ip'] = "Endereço IP";
$lang['MulticraftService.service_fields.port'] = "Porta";
$lang['MulticraftService.service_fields.yes'] = "Sim";
$lang['MulticraftService.service_fields.no'] = "Não";
$lang['MulticraftService.!error.configoptions[memory].format'] = "Por favor defina uma quantidade de memória válida.";
?>