<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Multicraft.module_row.name'] = "Servidor";
$lang['Multicraft.module_rows.name'] = "Servidores";
$lang['Multicraft.manage.module_rows_title'] = "Servidores";
$lang['Multicraft.manage.module_rows_heading.username'] = "Nome de Utilizador";
$lang['Multicraft.manage.module_rows_heading.server_name'] = "Etiqueta do Servidor";
$lang['Multicraft.manage.module_rows_heading.options'] = "Opções";
$lang['Multicraft.manage.module_rows.delete'] = "Eliminar";
$lang['Multicraft.manage.module_rows.confirm_delete'] = "Tem a certeza que quer apagar este servidor?";
$lang['Multicraft.manage.module_rows_no_results'] = "Não há servidores.";
$lang['Multicraft.manage.module_rows_in_use_0'] = "Não";
$lang['Multicraft.manage.module_rows_in_use_1'] = "Sim";
$lang['Multicraft.tab_client_actions'] = "Acções";
$lang['Multicraft.tab_client_players'] = "Jogadores";
$lang['Multicraft.tab_client_console'] = "Consola";
$lang['Multicraft.tab_client_actions.address_ip'] = "Endereço IP";
$lang['Multicraft.tab_client_actions.heading_server_status'] = "Estado do Servidor";
$lang['Multicraft.tab_client_actions.action_stop'] = "Parar";
$lang['Multicraft.tab_client_actions.action_start'] = "Iniciar";
$lang['Multicraft.tab_client_actions.action_server_name'] = "Definir Nome de Servidor";
$lang['Multicraft.tab_client_actions.unknown'] = "Desconhecido";
$lang['Multicraft.tab_client_actions.status_online'] = "%1\$s/%2\$s jogadores online"; // %1$s is the number of players online, %2\$s is the maximum number of players
$lang['Multicraft.tab_client_actions.status_suspended'] = "Suspenso";
$lang['Multicraft.tab_client_players.heading_players'] = "Jogadores ligados";
$lang['Multicraft.tab_client_players.heading_player_name'] = "Nome do Jogador";
$lang['Multicraft.tab_client_players.heading_action'] = "Ação";
$lang['Multicraft.tab_client_players.no_results'] = "Não existem jogadores ligados.";
$lang['Multicraft.tab_client_players.heading_console'] = "Consola do servidor";
$lang['Multicraft.tab_client_console.submit_send'] = "Enviar";
$lang['Multicraft.tab_client_console.chat_entry'] = "[%1\$s] %2\$s: %3\$s"; // %1$s is the timestamp of the log entry, %2$s is the player name, %3$s is the message
$lang['Multicraft.tab_client_console.submit_clear_log'] = "Limpar Registo";
$lang['Multicraft.tab_client_players.heading_chat_tab'] = "Registos do Chat";
$lang['Multicraft.add_row.box_title'] = "Adicionar Servidor Multicraft";
$lang['Multicraft.add_row.add_btn'] = "Adicionar Servidor";
$lang['Multicraft.add_row.daemons_title'] = "Endereços IP Dedicados";
$lang['Multicraft.add_row.ip_btn'] = "Adicionar Endereço IP";
$lang['Multicraft.add_row.remove_ip'] = "Remover";
$lang['Multicraft.add_row.daemon_col'] = "ID de Daemon";
$lang['Multicraft.add_row.ip_col'] = "Endereço IP";
$lang['Multicraft.add_row.in_use_col'] = "Em Uso";
$lang['Multicraft.edit_row.box_title'] = "Editar Servidor Multicraft";
$lang['Multicraft.edit_row.basic_title'] = "Definições Básicas";
$lang['Multicraft.edit_row.add_btn'] = "Editar Servidor";
$lang['Multicraft.edit_row.daemons_title'] = "Endereço IP Dedicado";
$lang['Multicraft.edit_row.ip_btn'] = "Adicionar endereço IP";
$lang['Multicraft.edit_row.remove_ip'] = "Remover";
$lang['Multicraft.edit_row.daemon_col'] = "ID de Daemon";
$lang['Multicraft.edit_row.ip_col'] = "Endereço IP";
$lang['Multicraft.edit_row.in_use_col'] = "Em uso";
$lang['Multicraft.row_meta.username'] = "Nome de utilizador";
$lang['Multicraft.row_meta.key'] = "Chave da API";
$lang['Multicraft.row_meta.log_all'] = "Registar todos os pedidos da API";
$lang['Multicraft.add_row.port_col'] = "Porta";
?>