<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['MulticraftModule.!error.panel_url.empty'] = "Por favor introduza o URL do painel Multicraft.";
$lang['MulticraftModule.!error.panel_api_url.empty'] = "Por favor, digite o URL para o API do seu painel Multicraft.";
$lang['MulticraftModule.!error.ips_in_use.match'] = "Por favor, indique se o endereço IP está actualmente uso com 1 ou 0.";
?>