<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PerforatedInvoice.page_of'] = "Página %1\$s de %2\$s"; // %1$s is the current page number, %2$s is the total number of pages
$lang['PerforatedInvoice.terms_heading'] = "Termos";
$lang['PerforatedInvoice.type_draft'] = "FATURA - RASCUNHO";
$lang['PerforatedInvoice.type_void'] = "FATURA - ANULADA";
$lang['PerforatedInvoice.type_proforma'] = "FATURA PRÓ-FORMA";
$lang['PerforatedInvoice.invoice_id_code'] = "Número de Factura:";
$lang['PerforatedInvoice.client_id_code'] = "Número de Cliente:";
$lang['PerforatedInvoice.client_name'] = "Nome do Cliente:";
$lang['PerforatedInvoice.tax_id'] = "NIF/VATIN:";
$lang['PerforatedInvoice.date_billed'] = "Data de Faturação:";
$lang['PerforatedInvoice.notes_heading'] = "Notas";
$lang['PerforatedInvoice.tax_heading'] = "%1\$s (%2\$s%%)"; // %1$s is the tax name, %2$s is the tax rate, %% escapes the percent (%) sign so it can be displayed
$lang['PerforatedInvoice.total_heading'] = "Total";
$lang['PerforatedInvoice.lines_description'] = "Descrição";
$lang['PerforatedInvoice.lines_quantity'] = "Quantidade";
$lang['PerforatedInvoice.lines_unit_price'] = "Preço Unitário";
$lang['PerforatedInvoice.lines_cost'] = "Custo";
$lang['PerforatedInvoice.watermark_paid'] = "PAGO";
$lang['PerforatedInvoice.payments_heading'] = "Pagamentos";
$lang['PerforatedInvoice.payments_type_name'] = "Tipo";
$lang['PerforatedInvoice.payments_transaction_id'] = "Número de Transação";
$lang['PerforatedInvoice.payments_applied_amount'] = "Montante Aplicado";
$lang['PerforatedInvoice.balance_heading'] = "Balanço";
$lang['PerforatedInvoice.draft_id_code'] = "Número de Rascunho:";
?>