<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMain.index.health_excellent'] = "O sistema está de boa saúde e parece estar a funcionar normalmente.";
$lang['AdminMain.index.health_good'] = "Em geral o sistema está de boa saúde, mas existem alguns itens que podem exigir a sua atenção.";
$lang['AdminMain.index.cron_serious'] = "O Cron nunca foi executado.";
$lang['AdminMain.index.cron_configure'] = "Configurar?";
$lang['AdminMain.index.invoices_configure'] = "Configurar?";
$lang['AdminMain.index.backup_minor'] = "Não foram executados backups nos últimos 7 dias.";
$lang['AdminMain.index.trial_minor'] = "A sua licença experimental expira a %1\$s."; // %1$s is the date the trial license expires
$lang['AdminMain.index.trial_buy'] = "Comprar Agora?";
$lang['AdminMain.index.updates_serious'] = "O seu suporte e actualizações expiram a %1\$s."; // %1$s is the date support expired
$lang['AdminMain.index.updates_buy'] = "Adicionar suporte e atualizações?";
?>