<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Package.!error.meta[pricing_id].format'] = "Selecione uma licença válida.";
$lang['BlestaLicense.manage.module_rows_heading.username'] = "Username";
$lang['BlestaLicense.manage.module_rows_heading.options'] = "Opções";
$lang['BlestaLicense.manage.module_rows.edit'] = "Editar";
$lang['BlestaLicense.manage.module_rows.delete'] = "Apagar";
$lang['BlestaLicense.row_meta.username'] = "Username";
$lang['BlestaLicense.row_meta.password'] = "Password";
$lang['BlestaLicense.row_meta.test_mode'] = "Modo de Teste";
$lang['BlestaLicense.add_row.box_title'] = "Adicionar Revendedor";
$lang['BlestaLicense.add_row.basic_title'] = "Definições Básicas";
$lang['Package.package_fields.pricing_id'] = "Licença";
$lang['BlestaLicense.tab_reissue.description'] = "Re-emitir a licença permitirá que a licença seja instalada ou movida para uma localização diferente onde ela ficará bloqueada.";
$lang['BlestaLicense.tab_reissue.field_submit'] = "Reemitir";
?>