<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['TransactionsReceived.name'] = "Transações Recebidas";
$lang['TransactionsReceived.option.any'] = "Qualquer";
$lang['TransactionsReceived.options.field_start_date'] = "Data de Início";
$lang['TransactionsReceived.options.field_end_date'] = "Data de Fim";
$lang['TransactionsReceived.options.field_gateway'] = "Gateway";
$lang['TransactionsReceived.options.field_status'] = "Estado";
$lang['TransactionsReceived.options.field_payment_type'] = "Tipo de Pagamento";
$lang['TransactionsReceived.heading.id'] = "Transação #";
$lang['TransactionsReceived.heading.transaction_id'] = "ID da Transação";
$lang['TransactionsReceived.heading.client_id_code'] = "Cliente #";
$lang['TransactionsReceived.heading.type_name'] = "Forma de pagamento";
$lang['TransactionsReceived.heading.amount'] = "Montante do pagamento";
$lang['TransactionsReceived.heading.currency'] = "Moeda";
$lang['TransactionsReceived.heading.status'] = "Estado";
$lang['TransactionsReceived.heading.income_type'] = "Tipo de Transacção";
?>