<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Vpsdotnet.name'] = "VPS.NET";
$lang['Vpsdotnet.module_row_plural'] = "Servidores";
$lang['Vpsdotnet.order_options.first'] = "Primeiro servidor não cheio";
$lang['Vpsdotnet.please_wait'] = "Por favor espere...";
$lang['Vpsdotnet.add_module_row'] = "Adicionar Server";
$lang['Vpsdotnet.add_module_group'] = "Adicionar Grupo de Servidores";
$lang['Vpsdotnet.manage.module_rows_heading.email'] = "Email";
$lang['Vpsdotnet.manage.module_rows_heading.options'] = "Opções";
$lang['Vpsdotnet.manage.module_rows.edit'] = "Editar";
$lang['Vpsdotnet.manage.module_rows.delete'] = "Apagar";
$lang['Vpsdotnet.manage.module_rows.confirm_delete'] = "Tem a certeza que quer apagar este servidor?";
$lang['Vpsdotnet.manage.module_rows_no_results'] = "Não há servidores.";
$lang['Vpsdotnet.manage.module_groups_heading.name'] = "Nome do Grupo";
$lang['Vpsdotnet.manage.module_groups_heading.servers'] = "Contagem de Servidores";
$lang['Vpsdotnet.manage.module_groups_heading.options'] = "Opções";
$lang['Vpsdotnet.manage.module_groups.edit'] = "Editar";
$lang['Vpsdotnet.manage.module_groups.delete'] = "Apagar";
$lang['Vpsdotnet.manage.module_groups.confirm_delete'] = "Tem a certeza de que quer apagar este grupo de servidores?";
$lang['Vpsdotnet.service_info.vpsdotnet_primary_ip_address'] = "Endereço IP Primário";
$lang['Vpsdotnet.service_info.vpsdotnet_password'] = "Password";
$lang['Vpsdotnet.add_row.basic_title'] = "Definições Básicas";
$lang['Vpsdotnet.row_meta.server_name'] = "Etiqueta do Servidor";
$lang['Vpsdotnet.row_meta.email'] = "Email";
$lang['Vpsdotnet.row_meta.key'] = "Chave da API";
$lang['Vpsdotnet.add_row.add_btn'] = "Adicionar Servidor";
$lang['Vpsdotnet.edit_row.box_title'] = "Editar Servidor VPS.NET";
$lang['Vpsdotnet.edit_row.basic_title'] = "Configurações Básicas";
$lang['Vpsdotnet.edit_row.add_btn'] = "Atualizar Servidor";
$lang['Vpsdotnet.package_fields.admin_set_template_group'] = "Selecione o Sistema Operativo";
$lang['Vpsdotnet.package_fields.template_group'] = "Sistema Operativo";
$lang['Vpsdotnet.package_fields.admin_set_template'] = "Escolher Template";
$lang['Vpsdotnet.package_fields.template'] = "Modelo";
$lang['Vpsdotnet.service_field.vpsdotnet_hostname'] = "Hostname";
$lang['Vpsdotnet.tab_actions'] = "Acções de Servidor";
$lang['Vpsdotnet.tab_console'] = "Consola";
$lang['Vpsdotnet.tab_client_actions'] = "Ações do Servidor";
$lang['Vpsdotnet.tab_client_console'] = "Consola";
$lang['Vpsdotnet.!actions.reboot'] = "Reiniciar";
$lang['Vpsdotnet.!actions.shutdown'] = "Desligar";
$lang['Vpsdotnet.!actions.reinstall'] = "Reinstalar";
$lang['Vpsdotnet.tab_actions.status_online'] = "Online";
$lang['Vpsdotnet.tab_actions.status_offline'] = "Offline";
$lang['Vpsdotnet.tab_actions.status_unknown'] = "Desconhecido";
$lang['Vpsdotnet.tab_actions.heading_actions'] = "Ações";
$lang['Vpsdotnet.tab_actions.server_status'] = "Estado do Servidor";
$lang['Vpsdotnet.tab_actions.heading_reinstall'] = "Re-Instalar";
$lang['Vpsdotnet.tab_actions.field_vpsdotnet_template_group'] = "Sistema Operativo";
$lang['Vpsdotnet.tab_actions.field_vpsdotnet_template'] = "Template";
$lang['Vpsdotnet.tab_actions.field_reinstall_submit'] = "Reinstalar";
$lang['Vpsdotnet.tab_actions.heading_hostname'] = "Alterar Hostname";
$lang['Vpsdotnet.tab_actions.field_vpsdotnet_hostname'] = "Hostname";
$lang['Vpsdotnet.tab_actions.field_hostname_submit'] = "Alterar Hostname";
$lang['Vpsdotnet.tab_actions.heading_password'] = "Recuperar Palavra-passe";
$lang['Vpsdotnet.tab_client_actions.heading_server_status'] = "Estado do Servidor";
$lang['Vpsdotnet.tab_client_actions.status_online'] = "Online";
$lang['Vpsdotnet.tab_client_actions.status_unknown'] = "Desconhecido";
$lang['Vpsdotnet.tab_client_actions.heading_reinstall'] = "Reinstalar";
$lang['Vpsdotnet.tab_client_actions.field_vpsdotnet_template_group'] = "Sistema Operativo";
$lang['Vpsdotnet.tab_client_actions.field_vpsdotnet_template'] = "Template";
$lang['Vpsdotnet.tab_client_actions.field_reinstall_submit'] = "Reinstalar";
$lang['Vpsdotnet.tab_client_actions.heading_hostname'] = "Alterar Hostname";
$lang['Vpsdotnet.tab_client_actions.field_vpsdotnet_hostname'] = "Hostname";
$lang['Vpsdotnet.tab_client_actions.field_hostname_submit'] = "Alterar Hostname";
$lang['Vpsdotnet.tab_console.heading_console'] = "Consola";
$lang['Vpsdotnet.tab_console.root_password'] = "Palavra-passe:";
$lang['Vpsdotnet.tab_client_console.heading_console'] = "Consola";
$lang['Vpsdotnet.!error.vps.update_failed'] = "Ocorreu um erro e a Máquina Virtual não pôde ser atualizada.";
$lang['Vpsdotnet.!error.vpsdotnet_template.valid'] = "Seleccione um template válido.";
$lang['Vpsdotnet.!error.meta[template_group].format'] = "Por favor escolha um sistema operativo válido.";
$lang['Vpsdotnet.!error.meta[template].format'] = "Por favor seleccione uma template válida.";
$lang['Vpsdotnet.!error.vpsdotnet_template_group.format'] = "Por favor escolha um Sistema Operativo válido.";
$lang['Vpsdotnet.!error.vpsdotnet_template.format'] = "Por favor escolha uma template válida.";
$lang['Vpsdotnet.tab_client_console.root_password'] = "Password";
?>