<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMain.index.boxtitle_order'] = "Encomendas";
$lang['AdminMain.index.no_results'] = "Não existem encomendas deste tipo.";
$lang['AdminMain.index.category_fraud'] = "Fraude";
$lang['AdminMain.index.heading_order_number'] = "Encomenda #";
$lang['AdminMain.index.heading_client_id_code'] = "ID de Cliente";
$lang['AdminMain.index.heading_invoice_id_code'] = "Fatura #";
$lang['AdminMain.index.heading_paid'] = "Pago";
$lang['AdminMain.index.heading_date_added'] = "Data de Encomenda";
$lang['AdminMain.index.field_ordersubmit'] = "Atualizar Encomendas";
$lang['AdminMain.orderinfo.fraudreport_heading_key'] = "Chave";
$lang['AdminMain.orderinfo.fraudreport_heading_value'] = "Valor";
$lang['AdminMain.orderinfo.applied_heading_paymenttype'] = "Tipo de Pagamento";
$lang['AdminMain.orderinfo.applied_heading_applied'] = "Aplicado";
$lang['AdminMain.orderinfo.applied_heading_options'] = "Options";
$lang['AdminMain.orderinfo.applied_option_edit'] = "Editar";
$lang['AdminMain.orderinfo.applied_no_results'] = "Não existem transações aplicadas a esta encomenda.";
$lang['AdminMain.orderinfo.services_heading_package'] = "Pacote";
$lang['AdminMain.orderinfo.services_heading_term'] = "Termo";
$lang['AdminMain.orderinfo.services_heading_options'] = "Opções";
$lang['AdminMain.orderinfo.services_option_manage'] = "Gerir";
$lang['AdminMain.orderinfo.services_text_never'] = "Nunca";
$lang['AdminMain.settings.heading_notifications'] = "Notificações de Encomendas";
$lang['AdminMain.settings.field_email_notice'] = "Email";
$lang['AdminMain.settings.field_email_notice_never'] = "Não enviar";
$lang['AdminMain.settings.field_email_notice_always'] = "Enviar sempre";
$lang['AdminMain.settings.field_mobile_notice_never'] = "Não enviar";
$lang['AdminMain.settings.field_mobile_notice_always'] = "Enviar sempre";
$lang['AdminMain.settings.submit_settings'] = "Atualizar Definições";
$lang['AdminMain.index.category_canceled'] = "Cancelado";
$lang['AdminMain.index.field_markas'] = "Marcar como:";
$lang['AdminMain.index.category_pending'] = "Em Revisão";
?>