<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminForms.!success.form_edited'] = "O formulário foi atualizado com sucesso.";
$lang['AdminForms.index.page_title'] = "Sistema de Encomendas";
$lang['AdminForms.settings.page_title'] = "Sistema de Encomendas";
$lang['AdminForms.add.page_title'] = "Sistema de Encomendas";
$lang['AdminForms.index.boxtitle_order'] = "Sistema de encomendas";
$lang['AdminForms.index.tab_settings'] = "Definições";
$lang['AdminForms.index.heading_name'] = "Nome";
$lang['AdminForms.index.heading_label'] = "Etiqueta";
$lang['AdminForms.index.heading_template'] = "Template";
$lang['AdminForms.index.heading_type'] = "Tipo";
$lang['AdminForms.index.heading_date_added'] = "Data de Adição";
$lang['AdminForms.index.heading_status'] = "Estado";
$lang['AdminForms.index.heading_options'] = "Opções";
$lang['AdminForms.index.option_edit'] = "Editar";
$lang['AdminForms.index.field_status_inactive'] = "Inativo";
$lang['AdminForms.add.field_name'] = "Nome";
$lang['AdminForms.add.field_type'] = "Tipo";
$lang['AdminForms.add.field_allow_coupons'] = "Permitir Cupões";
$lang['AdminForms.add.field_require_ssl'] = "Forçar Conexão Segura (HTTPS)";
$lang['AdminForms.add.field_tos_url'] = "URL dos Termos de Serviço";
$lang['AdminForms.add.field_status'] = "Estado";
$lang['AdminForms.add.field_status_inactive'] = "Inativo";
$lang['AdminForms.add.field_template'] = "Template";
$lang['AdminForms.add.field_client_group_id'] = "Grupo de Cliente Padrão";
$lang['AdminForms.add.heading_basic'] = "Básico";
$lang['AdminForms.edit.field_name'] = "Nome";
$lang['AdminForms.edit.field_type'] = "Tipo";
$lang['AdminForms.edit.field_require_ssl'] = "Forçar uso de ligação segura (HTTPS)";
$lang['AdminForms.edit.field_require_tos'] = "Requer a concordação com os termos de serviço";
$lang['AdminForms.edit.field_status_active'] = "Ativo";
$lang['AdminForms.edit.field_status_inactive'] = "Inativo";
$lang['AdminForms.edit.field_addsubmit'] = "Editar Formulário";
$lang['AdminForms.edit.heading_basic'] = "Básico";
$lang['AdminForms.meta.text_membergroups'] = "Grupos atribuídos";
$lang['AdminForms.meta.heading_package_groups'] = "Grupos de Pacotes";
$lang['AdminForms.meta.heading_package_group'] = "Grupo de Pacotes";
$lang['AdminForms.meta.heading_gateways'] = "Gateways";
$lang['AdminForms.settings.boxtitle_order'] = "Sistema de Encomendas";
$lang['AdminForms.settings.basic_heading'] = "Opções Básicas";
$lang['AdminForms.settings.field_captcha'] = "Verificação Humana";
$lang['AdminForms.settings.field_captcha_none'] = "Nenhum";
$lang['AdminForms.settings.field_captcha_recaptcha'] = "reCaptcha";
$lang['AdminForms.settings.antifraud_heading'] = "Anti-Fraude";
$lang['AdminForms.settings.field_antifraud'] = "Tipo";
$lang['AdminForms.settings.field_antifraud.none'] = "Nenhum";
$lang['AdminForms.settings.field_save'] = "Guardar Definições";
$lang['AdminForms.add.field_visibility'] = "Visibilidade";
$lang['AdminForms.edit.field_visibility'] = "Visibilidade";
?>