<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Cart.!success.coupon_applied'] = "O cupão foi aplicado com sucesso.";
$lang['Cart.!success.item_removed'] = "O item foi removido do seu carrinho.";
$lang['Cart.!success.all_items_removed'] = "Todos os itens foram removidos do seu carrinho de compras.";
$lang['Cart.!error.coupon_applied'] = "O cupão não pôde ser aplicado.";
$lang['Cart.index.quantity'] = "%1\$s @"; // %1\$s is the quantity value being ordered
$lang['Cart.index.totals.setup_fee'] = "Taxa de Instalação:";
$lang['Cart.index.totals.discount'] = "Desconto:";
$lang['Cart.index.totals.subtotal'] = "Subtotal:";
$lang['Cart.index.totals.tax'] = "%1\$s (%2\$s%%):"; // %1$s is the tax name, %2$s is the tax percentage
$lang['Cart.index.totals.total'] = "Total Vencido:";
$lang['Cart.index.pro_rata_month'] = "Mês parcial";
$lang['Cart.index.date_range'] = "(%1\$s - %2\$s)"; // %1$s is the start date, %2$s is the end date
?>