<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Checkout.!error.invalid_agree_tos'] = "Tem de reconhecer que aceita os termos e condições.";
$lang['Checkout.!error.no_payment_info'] = "Tem de selecionar um método de pagamento para continuar.";
$lang['Checkout.index.description_invoice'] = "Fatura #%1\$s"; // %1$s is the invoice number
$lang['Checkout.setcontactview.text_none'] = "Nenhum";
$lang['Checkout.getpaymentaccounts.paymentaccount_cc'] = "Contas de Cartão de Crédito";
$lang['Checkout.getpaymentaccounts.paymentaccount_ach'] = "Contas ACH";
$lang['Checkout.getpaymentaccounts.account_name'] = "%1\$s %2\$s - %3\$s x%4\$s"; // %1$s is the account first name, %2$s is the account last name, %3$s is the account type (card type or bank account type), %4$s is the last 4 of the account
$lang['Checkout.index.totals.discount'] = "Desconto:";
$lang['Checkout.index.totals.subtotal'] = "Subtotal:";
$lang['Checkout.index.totals.tax'] = "%1\$s (%2\$s%%):"; // %1$s is the tax name, %2$s is the tax percentage
$lang['Checkout.index.totals.total'] = "Total Vencido:";
$lang['Checkout.contact_info.field_first_name'] = "Primeiro Nome";
$lang['Checkout.contact_info.field_last_name'] = "Último Nome";
$lang['Checkout.contact_info.field_address1'] = "Endereço 1";
$lang['Checkout.contact_info.field_address2'] = "Endereço 2";
$lang['Checkout.contact_info.field_city'] = "Cidade";
$lang['Checkout.contact_info.field_country'] = "País";
$lang['Checkout.contact_info.field_state'] = "Estado";
$lang['Checkout.contact_info.field_zip'] = "Código Postal";
$lang['Checkout.contact_info.field_email'] = "Email";
$lang['Checkout.cc_info.field_security'] = "Código de Segurança";
$lang['Checkout.cc_info.tooltip_code'] = "O código de segurança de 3 ou 4 dígitos, geralmente encontrado na parte de trás do cartão.";
$lang['Checkout.ach_info.field_type'] = "Tipo";
$lang['Checkout.ach_info.field_accountnum'] = "Número de Conta";
$lang['Checkout.ach_info.tooltip_savedetails'] = "Detalhes de pagamento guardados podem ser usados para fazer pagamentos no futuro, sem ter de os introduzir novamente.";
$lang['Checkout.complete.order_number'] = "Encomenda #%1\$s"; // %1$s is the order number
$lang['Checkout.complete.complete_description'] = "Obrigado pela sua encomenda! A sua encomenda está agora completa.";
$lang['Checkout.complete.table_description'] = "Descrição";
$lang['Checkout.complete.table_qty'] = "Quantidade";
$lang['Checkout.complete.table_price'] = "Preço";
$lang['Checkout.complete.quantity'] = "%1\$s @"; // %1\$s is the quantity value being ordered
$lang['Checkout.complete.totals.subtotal'] = "Subtotal:";
$lang['Checkout.complete.totals.tax'] = "%1\$s (%2\$s%%):"; // %1$s is the tax name, %2$s is the tax percentage
$lang['Checkout.complete.totals.total'] = "Total Vencido:";
$lang['Checkout.complete.totals.total_paid'] = "Total Pago:";
$lang['Checkout.index.totals.credit'] = "Crédito:";
$lang['Checkout.!error.not_client_owner'] = "Deve estar ligado como o proprietário do cliente, para continuar.";
?>