<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['OrderForms.!error.require_tos.valid'] = "Se os termos de acordo de serviço são requeridos, uma URL deve ser fornecida para os termos.";
$lang['OrderForms.getVisibilities.public'] = "Público";
$lang['OrderForms.getVisibilities.shared'] = "Partilhado";
?>