<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Signup.!error.captcha.invalid'] = "O captcha digitado é inválido. Por favor, tente novamente.";
$lang['Signup.index.field_firstname'] = "Primeiro Nome";
$lang['Signup.index.field_lastname'] = "Último Nome";
$lang['Signup.index.field_company'] = "Empresa/Org.";
$lang['Signup.index.field_address1'] = "Endereço 1";
$lang['Signup.index.field_address2'] = "Endereço 2";
$lang['Signup.index.field_city'] = "Cidade";
$lang['Signup.index.field_state'] = "Estado/Província";
$lang['Signup.index.field_zip'] = "Código Postal";
$lang['Signup.index.field_country'] = "País";
$lang['Signup.index.field_phone'] = "Telefone";
$lang['Signup.index.field_fax'] = "Fax";
$lang['Signup.index.field_email'] = "Email";
$lang['Signup.index.field_username_type_email'] = "Utilizar email como nome de utilizador";
$lang['Signup.index.field_action_continue'] = "Continuar como %1\$s %2\$s"; // %1$s is the first name of the client, %2$s is the last name of the client
$lang['Signup.index.field_action_login'] = "Entrar";
$lang['Signup.index.field_action_signup'] = "Criar uma Conta";
$lang['Signup.index.field_username'] = "Nome de Utilizador";
$lang['Signup.index.field_password'] = "Palavra-passe";
$lang['Signup.index.field_newpassword'] = "Palavra-passe";
$lang['Signup.index.field_confirmpassword'] = "Confirmar Password";
$lang['Signup.index.login_btn'] = "Entrar";
$lang['Signup.index.signup_btn'] = "Criar conta";
?>