<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Summary.index.item_option_price'] = "%1\$s %3\$s @ %2\$s"; // %1$s is the option, %2$s is the price per term, %3$s is the quantity being ordered
$lang['Summary.index.totals.setup_fee'] = "Taxa de Instalação:";
$lang['Summary.index.totals.discount'] = "Desconto:";
$lang['Summary.index.totals.subtotal'] = "Subtotal:";
$lang['Summary.index.totals.tax'] = "%1\$s (%2\$s%%):"; // %1$s is the tax name, %2$s is the tax percentage
$lang['Summary.index.totals.total'] = "Total devido:";
$lang['Summary.index.item_price_pro_rata'] = "%1\$s %4\$s para %3\$s @ %2\$s"; // %1$s is the term, %2$s is the price per term, %3$s is the quantity being ordered, %4$s is the date range
$lang['Summary.index.single_item_price_pro_rata'] = "%1\$s %3\$s @ %2\$s"; // %1$s is the term, %2$s is the price per term, %3$s is the date range
$lang['Summary.index.single_item_option_price'] = "%1\$s @ %2\$s"; // %1$s is the option, %2$s is the price per term
?>