<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Payza.name'] = "Payza";
$lang['Payza.api_security_code'] = "Password da API";
$lang['Payza.buildprocess.submit'] = "Pagar via Payza";
$lang['Payza.!error.invalid_token.response'] = "Payza respondeu com um token inválido.";
?>