<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMain.index.boxtitle_overview'] = "Vista Geral do Sistema";
$lang['AdminMain.overview.statistic.clients_active'] = "Clientes activos";
$lang['AdminMain.overview.statistic.services_active'] = "Serviços Ativos";
$lang['AdminMain.overview.statistic.active_users_today'] = "Utilizadores Ativos Hoje";
$lang['AdminMain.overview.statistic.pending_orders'] = "Encomendas Pendentes";
$lang['AdminMain.overview.statistic.open_tickets'] = "Tickets abertos";
$lang['AdminMain.overview.heading_users'] = "Utilizadores Recentes";
$lang['AdminMain.overview.tab_all'] = "Gráficos";
$lang['AdminMain.overview.tab_clients'] = "Clientes";
$lang['AdminMain.overview.tab_services'] = "Serviços";
$lang['AdminMain.overview.tooltip_activity'] = "Última actividade";
$lang['AdminMain.overview.tooltip_location'] = "Localização";
$lang['AdminMain.overview.tooltip_last_activity_now'] = "Agora Mesmo";
$lang['AdminMain.overview.tooltip_last_activity_minute'] = "1 minuto atrás";
$lang['AdminMain.date_range.days'] = "%1\$s Dias"; // %1$s is the number of days (more than 1)
$lang['AdminMain.settings.heading_statistics'] = "Estatísticas";
$lang['AdminMain.settings.clients_active'] = "Clientes Ativos";
$lang['AdminMain.settings.services_active'] = "Serviços Ativos";
$lang['AdminMain.settings.recurring_invoices'] = "Faturas Recorrentes";
$lang['AdminMain.settings.pending_orders'] = "Encomendas Pendentes";
$lang['AdminMain.settings.heading_clients'] = "Tab clientes";
$lang['AdminMain.settings.graph_clients'] = "Gráfico de clientes";
$lang['AdminMain.settings.graph_services'] = "Gráficos de Serviços";
$lang['AdminMain.settings.heading_settings'] = "Configurações";
$lang['AdminMain.settings.show_legend'] = "Mostrar Legenda";
$lang['AdminMain.settings.submit_settings'] = "Atualizar Definições";
$lang['AdminMain.graph_name.graph_services'] = "Serviços";
$lang['AdminMain.graph_name.graph_clients'] = "Clientes";
$lang['AdminMain.graph_line_name.active'] = "Ativo";
$lang['AdminMain.graph_line_name.canceled'] = "Cancelado";
$lang['AdminMain.graph_line_name.new'] = "Novo";
$lang['AdminMain.overview.statistic.services_scheduled_cancellation'] = "Serviços Agendados para Cancelamento";
$lang['AdminMain.settings.services_scheduled_cancellation'] = "Serviços Agendados para Cancelamento";
$lang['AdminMain.overview.tooltip_last_activity_minutes'] = "%1\$s minutos atrás"; // %1$s is the number of minutes since the user's last activity
$lang['AdminMain.graph_line_name.suspended'] = "Suspenso";
?>