<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Vesta.name'] = "Vesta";
$lang['Vesta.module_row'] = "Server";
$lang['Vesta.module_row_plural'] = "Servidores";
$lang['Vesta.tab_stats'] = "Estatísticas";
$lang['Vesta.tab_client_actions'] = "Ações";
$lang['Vesta.tab_stats.info.WEB_DOMAINS'] = "Domínios";
$lang['Vesta.tab_stats.info.DATABASES'] = "Bases de Dados";
$lang['Vesta.tab_stats.info.DISK_QUOTA'] = "Utilização de Disco";
$lang['Vesta.add_module_row'] = "Adicionar Servidor";
$lang['Vesta.manage.module_rows_title'] = "Servidores";
$lang['Vesta.manage.module_rows_heading.hostname'] = "Hostname";
$lang['Vesta.manage.module_rows_heading.port'] = "Porta";
$lang['Vesta.manage.module_rows_heading.accounts'] = "Contas";
$lang['Vesta.manage.module_rows_heading.options'] = "Opções";
$lang['Vesta.manage.module_groups_heading.options'] = "Opções";
$lang['Vesta.manage.module_rows.count'] = "%1\$s / %2\$s"; // %1$s is the current number of accounts, %2$s is the total number of accounts available
$lang['Vesta.manage.module_groups.edit'] = "Editar";
$lang['Vesta.manage.module_rows.confirm_delete'] = "Tem a certeza de que quer apagar este servidor?";
$lang['Vesta.manage.module_groups.confirm_delete'] = "Tem a certeza de que quer apagar este grupo de servidores?";
$lang['Vesta.add_row.box_title'] = "Adicionar Servidor Vesta";
$lang['Vesta.add_row.remove_name_server'] = "Remover";
$lang['Vesta.edit_row.box_title'] = "Editar Servidor Vesta";
$lang['Vesta.edit_row.basic_title'] = "Definições Básicas";
$lang['Vesta.edit_row.remove_name_server'] = "Remover";
$lang['Vesta.edit_row.add_btn'] = "Editar Servidor";
$lang['Vesta.row_meta.password'] = "Password";
$lang['Vesta.row_meta.port'] = "Porta";
$lang['Vesta.row_meta.use_ssl'] = "Utilizar SSL quanto se ligar à API (recomendado)";
$lang['Vesta.service_field.username'] = "Username";
$lang['Vesta.service_info.hostname'] = "Hostname";
$lang['Vesta.service_info.username'] = "Username";
$lang['Vesta.service_info.password'] = "Password";
$lang['Vesta.service_info.server'] = "Servidor";
$lang['Vesta.service_info.options'] = "Opções";
$lang['Vesta.tab_client_actions.change_password'] = "Alterar Password";
$lang['Vesta.tab_client_actions.password'] = "Password";
$lang['Vesta.tab_client_actions.confirm_password'] = "Confirmar Password";
$lang['Vesta.tab_stats.info_heading.field'] = "Campo";
$lang['Vesta.tab_stats.info_heading.value'] = "Valor";
$lang['Vesta.!error.port_valid'] = "A Porta aparenta ser inválida.";
?>