<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMain.add.boxtitle_feed'] = "Adicionar um Feed";
$lang['AdminMain.add.field_url'] = "URL";
$lang['AdminMain.add.submit_add'] = "Adicionar Feed";
$lang['AdminMain.add.submit_cancel'] = "Cancelar ";
$lang['AdminMain.settings.no_feeds'] = "Não há feeds.";
$lang['AdminMain.settings.add_feed'] = "Adicionar um Feed";
$lang['AdminMain.settings.heading_url'] = "URL";
$lang['AdminMain.settings.heading_lastupdated'] = "Última Atualização";
$lang['AdminMain.settings.heading_options'] = "Opções";
$lang['AdminMain.settings.option_refresh'] = "Atualizar";
$lang['AdminMain.settings.option_remove'] = "Remover";
?>