<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['FeedReaderManagePlugin.!success.feed_removed'] = "O feed foi removido com sucesso.";
$lang['FeedReaderManagePlugin.index.boxtitle_feedreader'] = "Leitor de Feeds";
$lang['FeedReaderManagePlugin.index.add_feed'] = "Adicionar Feed";
$lang['FeedReaderManagePlugin.index.heading_url'] = "URL";
$lang['FeedReaderManagePlugin.index.heading_options'] = "Opções";
$lang['FeedReaderManagePlugin.index.option_refresh'] = "Recarregar";
$lang['FeedReaderManagePlugin.index.option_remove'] = "Remover";
$lang['FeedReaderPlugin.add.field_url'] = "URL";
$lang['FeedReaderPlugin.add.submit_cancel'] = "Cancelar";
?>