<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['UniversalModule.name'] = "Módulo Universal";
$lang['UniversalModule.module_row'] = "Produto";
$lang['UniversalModule.module_row_plural'] = "Produtos";
$lang['UniversalModule.add_module_row'] = "Adicionar Produto";
$lang['UniversalModule.manage.module_rows_heading.options'] = "Opções";
$lang['UniversalModule.manage.module_rows.edit'] = "Editar";
$lang['UniversalModule.manage.module_rows.confirm_delete'] = "Tem a certeza que pretende apagar este produto?";
$lang['UniversalModule.add_row.box_title'] = "Adicionar Produto";
$lang['UniversalModule.add_row.module_title'] = "Opções de Módulo";
$lang['UniversalModule.add_row.name'] = "Nome";
$lang['UniversalModule.add_row.notice_code'] = "Código HTTP";
$lang['UniversalModule.add_row.package_title'] = "Opções dos Pacote";
$lang['UniversalModule.add_row.package_field_name'] = "Nome";
$lang['UniversalModule.add_row.package_field_type'] = "Tipo";
$lang['UniversalModule.add_row.package_field_values'] = "Valores";
$lang['UniversalModule.add_row.package_field_encrypt'] = "Ecriptar";
$lang['UniversalModule.add_row.remove_package_field'] = "Remover";
$lang['UniversalModule.add_row.package_email_from'] = "Email De";
$lang['UniversalModule.add_row.package_email_subject'] = "Assunto";
$lang['UniversalModule.add_row.package_email_html'] = "HTML";
$lang['UniversalModule.add_row.package_email_text'] = "Texto";
$lang['UniversalModule.add_row.service_title'] = "Opções do Serviço";
$lang['UniversalModule.add_row.service_field_name'] = "Nome";
$lang['UniversalModule.add_row.service_field_type'] = "Tipo";
$lang['UniversalModule.add_row.service_field_values'] = "Valores";
$lang['UniversalModule.add_row.service_field_required'] = "Necessário";
$lang['UniversalModule.add_row.service_field_encrypt'] = "Encriptar";
$lang['UniversalModule.add_row.remove_service_field'] = "Remover";
$lang['UniversalModule.add_row.service_email_subject'] = "Assunto";
$lang['UniversalModule.add_row.service_email_html'] = "HTML";
$lang['UniversalModule.add_row.service_email_text'] = "Texto";
$lang['UniversalModule.edit_row.box_title'] = "Editar Produto";
$lang['UniversalModule.edit_row.name'] = "Nome";
$lang['UniversalModule.edit_row.notice_code'] = "Código HTTP";
$lang['UniversalModule.edit_row.package_title'] = "Opções do Pacote";
$lang['UniversalModule.edit_row.package_field_btn'] = "Adicionar Opção de Pacote";
$lang['UniversalModule.edit_row.package_field_label'] = "Etiqueta";
$lang['UniversalModule.edit_row.package_field_name'] = "Nome";
$lang['UniversalModule.edit_row.package_field_type'] = "Tipo";
$lang['UniversalModule.edit_row.package_field_values'] = "Valores";
$lang['UniversalModule.edit_row.package_field_encrypt'] = "Encriptar";
$lang['UniversalModule.edit_row.remove_package_field'] = "Remover";
$lang['UniversalModule.edit_row.package_email_from'] = "De Email";
$lang['UniversalModule.edit_row.package_email_subject'] = "Assunto";
$lang['UniversalModule.edit_row.package_email_html'] = "HTML";
$lang['UniversalModule.edit_row.package_email_text'] = "Texto";
$lang['UniversalModule.edit_row.service_title'] = "Opções de Serviço";
$lang['UniversalModule.edit_row.service_field_type'] = "Tipo";
$lang['UniversalModule.edit_row.service_field_values'] = "Valores";
$lang['UniversalModule.edit_row.service_field_encrypt'] = "Encriptar";
$lang['UniversalModule.edit_row.remove_service_field'] = "Remover";
$lang['UniversalModule.edit_row.service_email_from'] = "Email De";
$lang['UniversalModule.edit_row.service_email_subject'] = "Assunto";
$lang['UniversalModule.edit_row.service_email_html'] = "HTML";
$lang['UniversalModule.edit_row.service_email_text'] = "Texto";
$lang['UniversalModule.getpackagenotices.add'] = "Adicionar";
$lang['UniversalModule.getpackagenotices.edit'] = "Editar";
$lang['UniversalModule.getservicenotices.add'] = "Adicionar";
$lang['UniversalModule.getservicenotices.edit'] = "Editar";
$lang['UniversalModule.getservicenotices.suspend'] = "Suspenso";
$lang['UniversalModule.getservicenotices.cancel'] = "Cancelar";
$lang['UniversalModule.getservicenotices.renew'] = "Renovar";
$lang['UniversalModule.getfieldtypes.text'] = "Texto";
$lang['UniversalModule.getfieldtypes.password'] = "Password";
$lang['UniversalModule.getfieldtypes.radio'] = "Rádio";
$lang['UniversalModule.getfieldtypes.hidden'] = "Escondido";
$lang['UniversalModule.getfieldtypes.secret'] = "Segredo";
$lang['UniversalModule.true'] = "Sim";
$lang['UniversalModule.false'] = "Não";
$lang['UniversalModule.!error.package_notice_edit.failed'] = "O módulo falhou a comunicação com o servidor remoto quando tentou atualizar o pacote.";
$lang['UniversalModule.!error.service_notice_edit.failed'] = "O módulo falhou a comunicação com o servidor remoto na tentativa de atualizar o serviço.";
$lang['UniversalModule.!error.service_notice_suspend.failed'] = "O módulo falhou a comunicação com o servidor remoto na tentativa de suspensão do serviço.";
$lang['UniversalModule.!error.service_field.required'] = "o campo %1\$s é obrigatório."; // %1$s is the label for the required service field
$lang['UniversalModule.manage.module_rows_no_results'] = "Não existem produtos.";
$lang['UniversalModule.!tooltip.option_heading_field_label'] = "Este é o texto que aparece diretamente acima do campo de formulário.";
$lang['UniversalModule.!tooltip.option_heading_field_type'] = "Este é o tipo de campo de formulário que será apresentado.";
?>