<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminManagePlugin.!success.settings_saved'] = "As definições foram gravadas.";
$lang['AdminManagePlugin.index.page_title'] = "Cancelamento Automático";
$lang['AdminManagePlugin.index.boxtitle_auto_cancel'] = "Cancelamento Automático";
$lang['AdminManagePlugin.index.heading_settings'] = "Definições";
$lang['AdminManagePlugin.index.field.submit'] = "Gravar";
$lang['AdminManagePlugin.getDays.never'] = "Nunca";
$lang['AdminManagePlugin.getDays.text_day'] = "%1\$s Dia";
$lang['AdminManagePlugin.getDays.text_days'] = "%1\$s Dias"; // %1$s is the number of days
?>