<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Proxmox.!actions.boot'] = "Iniciar";
$lang['Proxmox.!actions.shutdown'] = "Desligar";
$lang['Proxmox.!actions.mount_iso'] = "Montar ISO";
$lang['Proxmox.!actions.unmount_iso'] = "Desmontar o ISO";
$lang['Proxmox.!actions.reinstall'] = "Reinstalar";
$lang['Proxmox.!actions.hostname'] = "Alterar Hostname";
$lang['Proxmox.!actions.password'] = "Alterar Palavra-Passe";
$lang['Proxmox.!error.server_name.empty'] = "Por favor introduza uma etiqueta de servidor.";
$lang['Proxmox.!error.user.empty'] = "Por favor introduza um utilizador.";
$lang['Proxmox.!error.password.empty'] = "Por favor introduza a palavra-passe.";
$lang['Proxmox.!error.port.format'] = "Por favor introduza um número de porta válido.";
$lang['Proxmox.!error.vmid.format'] = "Por favor introduza um VMID válido.";
$lang['Proxmox.!error.ips.empty'] = "Por favor introduza IPs.";
$lang['Proxmox.!error.meta[memory].format'] = "Por favor defina a RAM.";
$lang['Proxmox.!error.meta[cpu].format'] = "Por favor defina a contagem de vCPU.";
$lang['Proxmox.!error.meta[netspeed].format'] = "Por favor, defina a velocidade da net.";
$lang['Proxmox.!error.meta[template].empty'] = "Por favor escolha uma template.";
$lang['Proxmox.!error.api.internal'] = "Ocorreu um erro interno ou o servidor não respondeu ao pedido.";
$lang['Proxmox.!error.proxmox_hostname.format'] = "O hostname parece ser inválido.";
$lang['Proxmox.!error.create_client.failed'] = "Ocorreu um erro interno e a conta de cliente não pôde ser criada.";
$lang['Proxmox.!bytes.value'] = "%1\$s%2\$s"; // %1$s is a number value, %2$s is the unit of that value (i.e., one of B, KB, MB, GB)
$lang['Proxmox.!percent.used'] = "%1\$s%"; // %1$s is a percentage value
$lang['Proxmox.name'] = "Proxmox";
$lang['Proxmox.module_row'] = "Servidor Mestre Proxmox";
$lang['Proxmox.module_row_plural'] = "Servidores";
$lang['Proxmox.add_module_row'] = "Adicionar Servidor";
$lang['Proxmox.manage.module_rows_title'] = "Servidores mestres Proxmox";
$lang['Proxmox.manage.module_rows_heading.host'] = "Hostname";
$lang['Proxmox.manage.module_rows_heading.options'] = "Opções";
$lang['Proxmox.manage.module_groups_heading.servers'] = "Contagem do Servidor";
$lang['Proxmox.manage.module_groups_heading.options'] = "Opções";
$lang['Proxmox.manage.module_rows.edit'] = "Editar";
$lang['Proxmox.manage.module_groups.edit'] = "Editar";
$lang['Proxmox.manage.module_groups.delete'] = "Apagar";
$lang['Proxmox.manage.module_rows.confirm_delete'] = "Tem a certeza de que deseja apagar este servidor?";
$lang['Proxmox.manage.module_groups.confirm_delete'] = "Tem a certeza de que quer apagar este grupo de servidores?";
$lang['Proxmox.manage.module_rows_no_results'] = "Não existem servidores.";
$lang['Proxmox.manage.module_groups_no_results'] = "Não há grupos de servidores.";
$lang['Proxmox.row_meta.server_name'] = "Etiqueta do Servidor";
$lang['Proxmox.row_meta.user'] = "Utilizador";
$lang['Proxmox.row_meta.password'] = "Palavra-passe";
$lang['Proxmox.row_meta.host'] = "Hostname";
$lang['Proxmox.row_meta.port'] = "Número de Porta SSL";
$lang['Proxmox.row_meta.default_storage'] = "local";
$lang['Proxmox.row_meta.default_vmid'] = "200";
$lang['Proxmox.row_meta.default_port'] = "8006";
$lang['Proxmox.row_meta.default_template'] = "Template por defeito";
$lang['Proxmox.row_meta.ips'] = "IPs (um por linha)";
$lang['Proxmox.types.openvz'] = "OpenVZ";
$lang['Proxmox.types.kvm'] = "KVM";
$lang['Proxmox.add_row.box_title'] = "Adicionar Servidor Proxmox";
$lang['Proxmox.add_row.basic_title'] = "Definições Básicas";
$lang['Proxmox.add_row.add_btn'] = "Adicionar Servidor";
$lang['Proxmox.edit_row.basic_title'] = "Definições Básicas";
$lang['Proxmox.edit_row.add_btn'] = "Actualizar Servidor";
$lang['Proxmox.package_fields.type'] = "Tipo";
$lang['Proxmox.package_fields.hdd'] = "Armazenamento (GB)";
$lang['Proxmox.package_fields.memory'] = "RAM (MB)";
$lang['Proxmox.service_field.proxmox_template'] = "Template";
$lang['Proxmox.service_info.proxmox_ip'] = "Endereço IP primário";
$lang['Proxmox.service_info.proxmox_username'] = "Nome de utilizador";
$lang['Proxmox.tab_actions'] = "Ações do Servidor";
$lang['Proxmox.tab_stats'] = "Estatísticas";
$lang['Proxmox.tab_console'] = "Consola";
$lang['Proxmox.tab_actions.heading_actions'] = "Ações";
$lang['Proxmox.tab_actions.status_running'] = "Online";
$lang['Proxmox.tab_actions.status_stopped'] = "Offline";
$lang['Proxmox.tab_actions.status_disabled'] = "Desactivado";
$lang['Proxmox.tab_actions.server_status'] = "Estado do Servidor";
$lang['Proxmox.tab_actions.heading_mount_iso'] = "Montar ISO";
$lang['Proxmox.tab_actions.heading_reinstall'] = "Reinstalar";
$lang['Proxmox.tab_actions.field_iso'] = "Imagem";
$lang['Proxmox.tab_actions.field_mount_submit'] = "Montar";
$lang['Proxmox.tab_actions.field_template'] = "Template";
$lang['Proxmox.tab_actions.field_reinstall_submit'] = "Reinstalar";
$lang['Proxmox.tab_client_actions.heading_server_status'] = "Estado do Servidor";
$lang['Proxmox.tab_client_actions.status_stopped'] = "Desligada";
$lang['Proxmox.tab_client_actions.status_disabled'] = "Desativado";
$lang['Proxmox.tab_client_actions.heading_mount_iso'] = "Montar ISO";
$lang['Proxmox.tab_client_actions.heading_reinstall'] = "Reinstalar";
$lang['Proxmox.tab_client_actions.field_iso'] = "Imagem";
$lang['Proxmox.tab_client_actions.field_mount_submit'] = "Montar";
$lang['Proxmox.tab_client_actions.field_template'] = "Template";
$lang['Proxmox.tab_client_actions.field_password'] = "Senha do root";
$lang['Proxmox.tab_client_actions.field_reinstall_submit'] = "Reinstalar";
$lang['Proxmox.tab_stats.heading_stats'] = "Estatísticas";
$lang['Proxmox.tab_stats.memory'] = "Memória:";
$lang['Proxmox.tab_stats.memory_stats'] = "%1\$s/%2\$s"; // %1$s is the memory used, %2$s is the total memory available
$lang['Proxmox.tab_stats.memory_percent_available'] = "(%1\$s%%)"; // %1$s is the percentage of memory used. You MUST use two % signs to represent a single percent (i.e. %%)
$lang['Proxmox.tab_stats.heading_graphs'] = "Gráficos";
$lang['Proxmox.tab_client_stats.heading_graphs'] = "Gráficos";
$lang['Proxmox.tab_console.heading_console'] = "Consola";
$lang['Proxmox.tab_console.vnc_port'] = "Porta VNC:";
$lang['Proxmox.tab_console.vnc_user'] = "Nome de utilizador VNC:";
$lang['Proxmox.tab_client_console.heading_console'] = "Consola";
$lang['Proxmox.tab_client_console.vnc_port'] = "Porta VNC";
?>