<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Skrill.name'] = "Skrill";
$lang['Skrill.user_email'] = "Endereço electrónico";
$lang['Skrill.secret_word'] = "Palavra Secreta";
$lang['Skrill.merchant_id'] = "ID de Mercador";
$lang['Skrill.merchant_id_note'] = "Introduza o seu ID Skrill.";
$lang['Skrill.buildprocess.submit'] = "Pagar com Skrill";
$lang['Skrill.invoice.description'] = "Faturas";
$lang['Skrill.!error.user_email.valid'] = "Por favor introduza um endereço de email válido.";
$lang['Skrill.!error.mqi.empty'] = "Por favor, digite a sua passowrd de MQI.";
$lang['Skrill.!error.merchant_id.empty'] = "Por favor introduza o seu ID de comerciante.";
?>