<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminFilter.text.all'] = "Todos";
$lang['AdminFilter.!tooltip.client_statuses'] = "Os cliente têm de pertencer a um dos estados selecionados.";
$lang['AdminFilter.index.form.contact_types'] = "Tipos de Contacto";
$lang['AdminFilter.index.form.service_renew_date'] = "Renvados por";
$lang['AdminFilter.index.form.service_parent_type'] = "Pacote/Módulo";
$lang['AdminFilter.index.form.service_parent_type_package'] = "Pacote";
$lang['AdminFilter.index.form.service_parent_type_module'] = "Módulo";
$lang['AdminFilter.index.form.module_id'] = "Módulo";
$lang['AdminFilter.index.form.continue'] = "Continuar";
?>