<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMain.index.page_title'] = "Correio em Massa";
$lang['AdminMain.index.job_task_total'] = "%1\$s / %2\$s"; // %1$s is the number of mailing tasks completed, %2$s is the total number of mailing tasks
$lang['AdminMain.index.heading_date'] = "data adicionada";
$lang['AdminMain.index.heading_status'] = "Estado";
$lang['AdminMain.index.heading_complete'] = "Completo";
$lang['AdminMain.index.type.email'] = "Email";
$lang['AdminMain.index.email_to'] = "Para";
$lang['AdminMain.index.email_from'] = "De";
$lang['AdminMain.index.email_subject'] = "Assunto";
?>