<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompose.index.page_title'] = "Envio Massivo de Mails > Escrever";
$lang['AdminCompose.index.boxtitle'] = "Compor Email";
$lang['AdminCompose.index.form.html'] = "HTML";
$lang['AdminCompose.index.form.text'] = "Texto";
$lang['AdminCompose.preview.heading.email_sample'] = "Email de Exemplo";
$lang['AdminCompose.preview.text_name'] = "De: %1\$s %2\$s"; // %1$s is the email's from name, %2$s is the email's from address
$lang['AdminCompose.preview.text_subject'] = "Assunto: %1\$s"; // %1$s
$lang['AdminCompose.preview.link_back'] = "Retroceder";
$lang['AdminCompose.preview.form.send'] = "Enviar";
?>