<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Config.export.first_name'] = "Primeiro Nome";
$lang['Config.export.last_name'] = "Último Nome";
$lang['Config.export.company'] = "Empresa";
$lang['Config.export.email'] = "Email";
$lang['Config.export.module_name'] = "Módulo";
?>