<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Tags.client.id_code'] = "ID";
$lang['Tags.client.status'] = "Estado";
$lang['Tags.contact.first_name'] = "Primeiro Nome";
$lang['Tags.contact.last_name'] = "Último Nome";
$lang['Tags.contact.address2'] = "Endereço 2";
$lang['Tags.contact.city'] = "Cidade";
$lang['Tags.contact.country'] = "País";
$lang['Tags.contact.zip'] = "Código Postal";
$lang['Tags.contact.email'] = "Email";
$lang['Tags.package.name'] = "Nome do Pacote";
$lang['Tags.service.status'] = "Estado";
$lang['Tags.module.name'] = "Nome do Módulo";
?>