<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['TaxLiability.options.field_cascade_true'] = "Sim";
$lang['TaxLiability.options.field_cascade_false'] = "Não";
$lang['TaxLiability.heading.id_code'] = "Fatura #";
$lang['TaxLiability.heading.client_id_code'] = "Cliente #";
$lang['TaxLiability.heading.subtotal'] = "Subtotal";
$lang['TaxLiability.heading.level1_tax_amount'] = "Taxa de imposto nível 1";
$lang['TaxLiability.heading.currency'] = "Moeda";
$lang['TaxLiability.heading.level1_tax_country'] = "País Nível 1";
?>