<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['404.heading_error'] = "404";
$lang['404.text_error'] = "Desculpe, a página que está a tentar aceder não existe ou pode ter sido movida.";
?>