<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Accounts.!error.contact_id.exists'] = "ID do Contacto inválido.";
$lang['Accounts.!error.first_name.empty'] = "Por favor, especifique um nome.";
$lang['Accounts.!error.last_name.empty'] = "Por favor, especifique um sobrenome.";
$lang['Accounts.!error.state.length'] = "Comprimento do Estado não pode ser superior a 3 caracteres.";
$lang['Accounts.!error.country.length'] = "O campo Pais deverá ter apenas 3 caracteres.";
$lang['Accounts.!error.state.country_exists'] = "Por favor, selecione o país que corresponde ao estado selecionado.";
$lang['Accounts.!error.account.length'] = "Por favor, especifique um número de conta.";
$lang['Accounts.!error.routing.empty'] = "Por favor, especifique um número de roteamento.";
$lang['Accounts.!error.last4.empty_ach'] = "Por favor insira os quatro últimos dígitos do número da conta.";
$lang['Accounts.!error.type.ach_format'] = "Tipo inválido.";
$lang['Accounts.!error.ach_account_id.exists'] = "Numero de conta inválido.";
$lang['Accounts.!error.number.valid'] = "O número do cartão é inválido.";
$lang['Accounts.!error.expiration.empty'] = "Por favor, introduza a data de fim do cartão de crédito";
$lang['Accounts.!error.expiration.valid'] = "A data de validade já expirou.";
$lang['Accounts.!error.last4.empty_cc'] = "Por favor insira os quatro últimos dígitos do número do cartão de crédito.";
$lang['Accounts.!error.type.cc_format'] = "O tipo de cartão é inválido ou não pôde ser determinado.";
$lang['Accounts.!error.cc_account_id.exists'] = "Numero de conta inválido.";
$lang['Accounts.getTypes.cc'] = "Cartão de crédito";
$lang['Accounts.getTypes.ach'] = "Automated Clearing House";
$lang['Accounts.getTypes.other'] = "Outro";
$lang['Accounts.getAchTypes.checking'] = "Verificar";
$lang['Accounts.getAchTypes.savings'] = "Poupança";
$lang['Accounts.getCcTypes.amex'] = "American Express";
$lang['Accounts.getCcTypes.bc'] = "Cartão bancário";
$lang['Accounts.getCcTypes.cup'] = "China Union Pay";
$lang['Accounts.getCcTypes.dc-cb'] = "Diners Club Carte Blanche";
$lang['Accounts.getCcTypes.dc-er'] = "Diners Club EnRoute";
$lang['Accounts.getCcTypes.dc-int'] = "Diners Club International";
$lang['Accounts.getCcTypes.dc-uc'] = "Diners Club US and Canada";
$lang['Accounts.getCcTypes.disc'] = "Discover";
$lang['Accounts.getCcTypes.ipi'] = "InstaPayment";
$lang['Accounts.getCcTypes.jcb'] = "Japan Credit Bureau";
$lang['Accounts.getCcTypes.lasr'] = "Laser";
$lang['Accounts.getCcTypes.maes'] = "Maestro";
$lang['Accounts.getCcTypes.mc'] = "Master Card";
$lang['Accounts.getCcTypes.solo'] = "Solo";
$lang['Accounts.getCcTypes.switch'] = "Switch";
$lang['Accounts.getCcTypes.visa'] = "Visa";
?>