<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyTaxes.!success.taxrule_updated'] = "A regra fiscal foi actualizada com sucesso!";
$lang['AdminCompanyTaxes.countries.all'] = "-- Todos --";
$lang['AdminCompanyTaxes.states.all'] = "-- Todos --";
$lang['AdminCompanyTaxes.basic.field_addsubmit'] = "Atualizar Definições";
$lang['AdminCompanyTaxes.rules.categorylink_addrule'] = "Adicionar Regra Fiscal";
$lang['AdminCompanyTaxes.rules.boxtitle_rules'] = "Regras de Imposto";
$lang['AdminCompanyTaxes.rules.heading_level1'] = "Regras do Nível 1";
$lang['AdminCompanyTaxes.rules.text_name'] = "Nome";
$lang['AdminCompanyTaxes.rules.text_type'] = "Tipo";
$lang['AdminCompanyTaxes.rules.text_amount'] = "Quantidade";
$lang['AdminCompanyTaxes.rules.text_country'] = "País";
$lang['AdminCompanyTaxes.rules.text_options'] = "Opções";
$lang['AdminCompanyTaxes.rules.option_edit'] = "Editar";
$lang['AdminCompanyTaxes.add.field_taxtype'] = "Tipo de Imposto";
$lang['AdminCompanyTaxes.add.field_level2'] = "Nível 2";
$lang['AdminCompanyTaxes.add.field_name'] = "Nome do Imposto";
$lang['AdminCompanyTaxes.add.field_amount'] = "Quantidade";
$lang['AdminCompanyTaxes.add.field_country'] = "País";
$lang['AdminCompanyTaxes.add.field_addsubmit'] = "Criar regra";
$lang['AdminCompanyTaxes.edit.boxtitle_edit'] = "Editar Regra Fiscal";
$lang['AdminCompanyTaxes.edit.field_taxtype'] = "Tipo de Taxa";
$lang['AdminCompanyTaxes.edit.field_level2'] = "Nível 2";
$lang['AdminCompanyTaxes.edit.field_name'] = "Nome do Imposto";
$lang['AdminCompanyTaxes.edit.field_country'] = "País";
$lang['AdminCompanyTaxes.edit.field_state'] = "Distrito";
$lang['AdminCompanyTaxes.basic.field_enable_tax'] = "Ativar Taxa";
$lang['AdminCompanyTaxes.basic.field_cancelation_fee_tax'] = "Tributar Taxas de Cancelamento";
$lang['AdminCompanyTaxes.rules.page_title'] = "Definições > Empresa > Impostos > Regras de Imposto";
$lang['AdminCompanyTaxes.add.page_title'] = "Definições > Empresa > Impostos > Adicionar Regra de Imposto";
$lang['AdminCompanyTaxes.rules.option_delete'] = "Apagar";
?>