<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminLogin.index.field_password'] = "Password";
$lang['AdminLogin.index.field_rememberme'] = "Lembrar-me neste computador.";
$lang['AdminLogin.index.field_loginsubmit'] = "Entrar";
$lang['AdminLogin.otp.link_login'] = "Cancel, Acesso";
$lang['AdminLogin.reset.field_resetsubmit'] = "Redefinir Password";
$lang['AdminLogin.confirmreset.field_new_password'] = "Nova Palavra-passe";
$lang['AdminLogin.confirmreset.field_confirm_password'] = "Confirme Nova Password";
$lang['AdminLogin.confirmreset.field_resetsubmit'] = "Definir Palavra-passe";
$lang['AdminLogin.!success.reset_sent'] = "Um email de confirmação foi enviado para o endereço em registo.";
$lang['AdminLogin.index.page_title'] = "Entrar";
$lang['AdminLogin.confirmreset.page_title'] = "Confirme reset de Password";
$lang['AdminLogin.setup.field_first_name'] = "Primeiro Nome";
$lang['AdminLogin.setup.field_last_name'] = "Último Nome";
$lang['AdminLogin.setup.field_username'] = "Nome de utilizador";
$lang['AdminLogin.setup.field_email'] = "Endereço Email";
$lang['AdminLogin.setup.field_password'] = "Password";
$lang['AdminLogin.setup.field_confirm_password'] = "Confirmar Palavra-Passe";
$lang['AdminLogin.setup.field_enter_key_true'] = "Eu tenho uma chave de licença para introduzir";
$lang['AdminLogin.setup.field_enter_key_false'] = "Eu quero começar uma avaliação gratuita de 30 dias";
$lang['AdminLogin.setup.field_submit'] = "Terminar";
$lang['AdminLogin.index.field_username'] = "Username";
$lang['AdminLogin.reset.field_username'] = "Nome de Utilizador";
?>