<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSystemAutomation.!error.empty_cron_key'] = "Por favor defina uma chave cron.";
$lang['AdminSystemAutomation.index.boxtitle_automation'] = "Automatização";
$lang['AdminSystemAutomation.index.heading_status'] = "Estado do Cron";
$lang['AdminSystemAutomation.index.field_croncommand'] = "Comando Cron";
$lang['AdminSystemAutomation.index.field_runcron'] = "Correr Cron manualmente";
$lang['AdminSystemAutomation.index.field_cron_key'] = "Chave Cron";
$lang['AdminSystemAutomation.index.text_cron_never_ran'] = "O cron nunca foi executado.";
$lang['AdminSystemAutomation.index.text_update_key'] = "Atualizar Chave Cron";
$lang['AdminSystemAutomation.index.text_generate_code'] = "Gerar Código";
$lang['AdminSystemAutomation.index.page_title'] = "Definições > Sistema > Automação";
?>