<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyEmails.!success.editsignature_updated'] = "A assinatura do email foi atualizada com sucesso!";
$lang['AdminCompanyEmails.!success.addsignature_created'] = "A assinatura de email foi criada com sucesso!";
$lang['AdminCompanyEmails.!success.deletesignature_deleted'] = "A assinatura de email foi apagada com sucesso!";
$lang['AdminCompanyEmails.!cancel.field_cancel'] = "Cancelar";
$lang['AdminCompanyEmails.templates.boxtitle_templates'] = "Templates de Email";
$lang['AdminCompanyEmails.templates.heading_client'] = "Email de Clientes";
$lang['AdminCompanyEmails.templates.heading_shared'] = "Emails Partilhados";
$lang['AdminCompanyEmails.templates.text_name'] = "Nome";
$lang['AdminCompanyEmails.templates.text_plugin'] = "Plugin";
$lang['AdminCompanyEmails.templates.text_description'] = "Descrição";
$lang['AdminCompanyEmails.templates.text_options'] = "Opções";
$lang['AdminCompanyEmails.templates.option_edit'] = "Editar";
$lang['AdminCompanyEmails.templates.payment_cc_approved_name'] = "Pagamento Aprovado (Cartão de Crédito)";
$lang['AdminCompanyEmails.templates.payment_cc_approved_desc'] = "Notificação enviada após um pagamento com cartão de crédito bem sucedido é aprovado.";
$lang['AdminCompanyEmails.templates.payment_cc_declined_name'] = "Pagamento Recusado (Cartão de Crédito)";
$lang['AdminCompanyEmails.templates.payment_cc_error_name'] = "Erro de Pagamento (Cartão de Crédito)";
$lang['AdminCompanyEmails.templates.payment_ach_declined_name'] = "Pagamento Recusado (ACH)";
$lang['AdminCompanyEmails.templates.payment_ach_error_name'] = "Erro de Pagamento (ACH)";
$lang['AdminCompanyEmails.templates.payment_ach_error_desc'] = "Aviso enviado após uma tentativa de pagamento ACH com resultados em erro.
";
$lang['AdminCompanyEmails.templates.payment_manual_approved_name'] = "Pagamento Recebido (Entrada Manual)";
$lang['AdminCompanyEmails.templates.invoice_notice_first_name'] = "Aviso de Fatura (1)";
$lang['AdminCompanyEmails.templates.invoice_notice_third_name'] = "Aviso de Fatura (3º)";
$lang['AdminCompanyEmails.templates.service_suspension_name'] = "Suspensão do Serviço";
$lang['AdminCompanyEmails.templates.service_suspension_error_name'] = "Erro de suspensão";
$lang['AdminCompanyEmails.templates.service_suspension_error_desc'] = "Notificação enviada após tentativa falhada de suspender um serviço.";
$lang['AdminCompanyEmails.templates.service_unsuspension_error_name'] = "Erro de Reativação";
$lang['AdminCompanyEmails.templates.service_cancel_error_name'] = "Erro de cancelamento";
$lang['AdminCompanyEmails.templates.staff_reset_password_name'] = "Resetar a senha";
$lang['AdminCompanyEmails.templates.service_creation_name'] = "Criação do Serviço";
$lang['AdminCompanyEmails.edittemplate.text_none'] = "Nenhum";
$lang['AdminCompanyEmails.edittemplate.field_status'] = "Ativado";
$lang['AdminCompanyEmails.edittemplate.field_from_name'] = "Nome De";
$lang['AdminCompanyEmails.edittemplate.field_from'] = "Email De";
$lang['AdminCompanyEmails.edittemplate.field_subject'] = "Assunto";
$lang['AdminCompanyEmails.edittemplate.field_tags'] = "Tags disponíveis";
$lang['AdminCompanyEmails.edittemplate.field_text'] = "Texto";
$lang['AdminCompanyEmails.edittemplate.field_html'] = "HTML";
$lang['AdminCompanyEmails.edittemplate.field_email_signature_id'] = "Assinatura";
$lang['AdminCompanyEmails.signatures.boxtitle_signatures'] = "Assinaturas";
$lang['AdminCompanyEmails.signatures.categorylink_newsignature'] = "Nova Assinatura";
$lang['AdminCompanyEmails.signatures.text_name'] = "Nome";
$lang['AdminCompanyEmails.signatures.text_description'] = "Descrição";
$lang['AdminCompanyEmails.signatures.text_options'] = "Opções";
$lang['AdminCompanyEmails.signatures.option_edit'] = "Editar";
$lang['AdminCompanyEmails.signatures.option_delete'] = "Apagar";
$lang['AdminCompanyEmails.addsignature.boxtitle_addsignature'] = "Adicionar Assinatura";
$lang['AdminCompanyEmails.addsignature.field_name'] = "Nome";
$lang['AdminCompanyEmails.addsignature.field_text'] = "Texto";
$lang['AdminCompanyEmails.addsignature.field_html'] = "HTML";
$lang['AdminCompanyEmails.addsignature.field_addsignaturesubmit'] = "Criar Assinatura";
$lang['AdminCompanyEmails.addsignature.text_signatures'] = "As assinaturas são utilizadas para templates de email, tornando assim mais fácil a modificação de email em massa.";
$lang['AdminCompanyEmails.editsignature.boxtitle_editsignature'] = "Editar Assinatura";
$lang['AdminCompanyEmails.editsignature.field_name'] = "Nome";
$lang['AdminCompanyEmails.editsignature.field_text'] = "Texto";
$lang['AdminCompanyEmails.editsignature.field_html'] = "HTML";
$lang['AdminCompanyEmails.mail.boxtitle_mail'] = "Definições de Email";
$lang['AdminCompanyEmails.mail.field_html_email'] = "Ativar HTML";
$lang['AdminCompanyEmails.mail.field_mail_delivery'] = "Método de Entrega";
$lang['AdminCompanyEmails.mail.field_smtp_port'] = "Porta SMTP";
$lang['AdminCompanyEmails.mail.field_smtp_user'] = "Utilizador SMTP";
$lang['AdminCompanyEmails.mail.field_smtp_password'] = "Password SMTP";
$lang['AdminCompanyEmails.mail.field_submitmail'] = "Atualizar configurações";
$lang['AdminCompanyEmails.getRequiredMethods.php'] = "PHP";
$lang['AdminCompanyEmails.getRequiredMethods.smtp'] = "SMTP";
$lang['AdminCompanyEmails.templates.page_title'] = "Definições > Empresa > Emails > Templates de Email";
$lang['AdminCompanyEmails.signatures.page_title'] = "Definições > Empresa > Emails > Assinaturas";
$lang['AdminCompanyEmails.addsignature.page_title'] = "Configurações > Empresa > E-mails > Adicionar assinatura";
$lang['AdminCompanyEmails.editsignature.page_title'] = "Definições -> Empresa -> Emails -> Editar Assinatura";
$lang['AdminCompanyEmails.mail.page_title'] = "Definições > Empresa > Emails > Definições de Email";
$lang['AdminCompanyEmails.mail.field_smtp_security'] = "Segurança SMTP";
$lang['AdminCompanyEmails.getsmtpsecurityoptions.none'] = "Nenhum";
$lang['AdminCompanyEmails.getsmtpsecurityoptions.ssl'] = "SSL";
$lang['AdminCompanyEmails.templates.service_unsuspension_name'] = "Reativação do Serviço";
$lang['AdminCompanyEmails.templates.service_creation_error_name'] = "Erro de Criação";
?>