<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminTools.getlognames.text_module'] = "Módulo";
$lang['AdminTools.getlognames.text_email'] = "Email";
$lang['AdminTools.getlognames.text_users'] = "Logins do Utilizador";
$lang['AdminTools.getlognames.text_accountaccess'] = "Acesso";
$lang['AdminTools.getlognames.text_cron'] = "Cron";
$lang['AdminTools.convertcurrency.boxtitle_currency'] = "Converter Moeda";
$lang['AdminTools.convertcurrency.field_amount'] = "Montante";
$lang['AdminTools.convertcurrency.field_from'] = "De";
$lang['AdminTools.convertcurrency.field_to'] = "Para";
$lang['AdminTools.convertcurrency.field_currencysubmit'] = "Converter Moeda";
$lang['AdminTools.logs.boxtitle_logs'] = "Registos";
$lang['AdminTools.logmodule.text_name'] = "Nome";
$lang['AdminTools.logmodule.text_staffname'] = "Equipa";
$lang['AdminTools.logmodule.text_date'] = "Data";
$lang['AdminTools.moduleloglist.text_date'] = "Data";
$lang['AdminTools.moduleloglist.text_error'] = "Erro";
$lang['AdminTools.moduleloglist.text_success'] = "Sucesso";
$lang['AdminTools.loggateway.text_name'] = "Nome";
$lang['AdminTools.loggateway.text_staffname'] = "Equipa";
$lang['AdminTools.loggateway.text_date'] = "Data";
$lang['AdminTools.gatewayloglist.text_date'] = "Data";
$lang['AdminTools.gatewayloglist.text_status'] = "Estado";
$lang['AdminTools.gatewayloglist.text_error'] = "Erro";
$lang['AdminTools.gatewayloglist.text_success'] = "Sucesso";
$lang['AdminTools.logemail.text_date'] = "Data";
$lang['AdminTools.logemail.text_subject'] = "Assunto";
$lang['AdminTools.logemail.text_summary'] = "Resumo";
$lang['AdminTools.logemail.text_status'] = "Estado";
$lang['AdminTools.logemail.text_to'] = "Para";
$lang['AdminTools.logemail.text_cc'] = "CC";
$lang['AdminTools.logemail.text_from'] = "De";
$lang['AdminTools.logemail.text_sent'] = "Enviado";
$lang['AdminTools.logusers.text_name'] = "Nome";
$lang['AdminTools.logusers.text_username'] = "Nome de Utilizador";
$lang['AdminTools.logusers.text_type'] = "Tipo";
$lang['AdminTools.logusers.text_ipaddress'] = "Endereço IP";
$lang['AdminTools.logusers.text_date'] = "Data";
$lang['AdminTools.logusers.text_client'] = "Cliente";
$lang['AdminTools.logaccountaccess.name'] = "Equipa";
$lang['AdminTools.logaccountaccess.date'] = "Data";
$lang['AdminTools.logaccountaccess.text_cc'] = "Cartão de Crédito";
$lang['AdminTools.logaccountaccess.text_ach'] = "ACH";
$lang['AdminTools.accountaccess.name'] = "Nome";
$lang['AdminTools.accountaccess.type'] = "Tipo";
$lang['AdminTools.accountaccess.type_cc'] = "%1\$s - %2\$s"; // %1$s is the account type (Credit Card) and %2$s is the type of account (MasterCard, Visa, etc.)
$lang['AdminTools.accountaccess.type_ach'] = "%1\$s - %2\$s"; // %1$s is the account type (ACH) and %2$s is the type of account (Checking or Savings)
$lang['AdminTools.accountaccess.no_results'] = "Não existem detalhes de conta para este registo.";
$lang['AdminTools.logcron.task'] = "Tarefa";
$lang['AdminTools.logcron.start_date'] = "Data de início";
$lang['AdminTools.!success.currency_converted'] = "%1\$s = %2\$s"; // %1$s is the from currency code and amount, %2$s is the to currency code and amount
$lang['AdminTools.getlognames.text_transactions'] = "Transações";
$lang['AdminTools.logemail.page_title'] = "Registos de Ferramentas";
$lang['AdminTools.logcontacts.page_title'] = "Registos de Ferramentas";
$lang['AdminTools.logcontacts.text_name'] = "Nome";
$lang['AdminTools.logcontacts.text_date'] = "Data";
$lang['AdminTools.logcontacts.text_field'] = "Campo";
$lang['AdminTools.logcontacts.text_previous'] = "Valor Anterior";
$lang['AdminTools.logcontacts.text_new'] = "Novo valor";
$lang['AdminTools.logtransactions.page_title'] = "Registos de Ferramentas";
$lang['AdminTools.logtransactions.text_client_name'] = "Cliente";
$lang['AdminTools.logtransactions.text_date'] = "Data";
$lang['AdminTools.logtransactions.text_field'] = "Campo";
$lang['AdminTools.logtransactions.text_previous'] = "Valor Anterior";
$lang['AdminTools.logtransactions.text_new'] = "Novo valor";
$lang['AdminTools.logtransactions.no_results'] = "Não há log de transações.";
$lang['AdminTools.loginvoicedelivery.invoice_id_code'] = "Factura #";
$lang['AdminTools.loginvoicedelivery.first_name'] = "Cliente";
$lang['AdminTools.loginvoicedelivery.method'] = "Método de Entrega";
$lang['AdminTools.loginvoicedelivery.date_sent'] = "Data de Envio";
$lang['AdminTools.loginvoicedelivery.no_results'] = "Não há registros de entrega da fatura.";
$lang['AdminTools.logusers.text_location'] = "Localização";
$lang['AdminTools.logusers.text_success'] = "Sucesso";
$lang['AdminTools.logusers.text_contact'] = "Contacto";
?>