<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSettings.company.category_company'] = "Empresa";
$lang['AdminSettings.company.category_system'] = "Sistema";
$lang['AdminSettings.company.boxtitle_settings'] = "Definições";
$lang['AdminSettings.company.heading_general'] = "Geral";
$lang['AdminSettings.company.heading_emails'] = "Emails";
$lang['AdminSettings.company.heading_currencies'] = "Moedas";
$lang['AdminSettings.company.heading_clientgroups'] = "Grupos de Clientes";
$lang['AdminSettings.company.heading_automation'] = "Automação";
$lang['AdminSettings.company.heading_modules'] = "Módulos";
$lang['AdminSettings.company.heading_gateways'] = "Gateways de Pagamento";
$lang['AdminSettings.company.heading_plugins'] = "Plugins";
$lang['AdminSettings.system.category_company'] = "Empresa";
$lang['AdminSettings.system.category_system'] = "Sistema";
$lang['AdminSettings.system.boxtitle_settings'] = "Definições";
$lang['AdminSettings.system.heading_general'] = "Geral";
$lang['AdminSettings.system.heading_companies'] = "Empresas";
$lang['AdminSettings.system.text_companies'] = "Adicionar ou actualizar Empresas.";
$lang['AdminSettings.system.heading_backup'] = "Cópia de Segurança";
$lang['AdminSettings.system.heading_marketplace'] = "Mercado";
$lang['AdminSettings.system.heading_automation'] = "Automatização";
$lang['AdminSettings.system.heading_staff'] = "Equipa";
$lang['AdminSettings.company.page_title'] = "Definições";
$lang['AdminSettings.system.page_title'] = "Definições";
$lang['AdminSettings.system.text_backup'] = "Configure backups automáticos utilizando SFTP, ou Amazon Se, ou faça download de um backup para o seu computador.";
?>