<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMyinfo.gettabnames.text_index'] = "Conta";
$lang['AdminMyinfo.gettabnames.text_notices'] = "Avisos";
$lang['AdminMyinfo.index.page_title'] = "Minha Informação";
$lang['AdminMyinfo.index.boxtitle_myinfo'] = "A Minha Informação";
$lang['AdminMyinfo.index.field_username'] = "Nome de Utilizador";
$lang['AdminMyinfo.index.field_firstname'] = "Primeiro Nome";
$lang['AdminMyinfo.index.field_lastname'] = "Último Nome";
$lang['AdminMyinfo.index.field_email'] = "Email";
$lang['AdminMyinfo.index.field_newpass'] = "Nova Password";
$lang['AdminMyinfo.index.field_confirmpass'] = "Confirmar Palavra-passe";
$lang['AdminMyinfo.index.field_twofactormode'] = "Autenticação de Dois Fatores";
$lang['AdminMyinfo.index.field_twofactorpin'] = "Pin de Dois Fatores";
$lang['AdminMyinfo.index.field_currentpass'] = "Palavra-passe atual";
$lang['AdminMyinfo.index.field_infosubmit'] = "Atualizar Conta";
?>