<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyPlugins.!success.uninstalled'] = "O plugin foi desinstalado com sucesso.";
$lang['AdminCompanyPlugins.available.text_author'] = "Autor:";
$lang['AdminCompanyPlugins.available.btn_install'] = "Instalar";
$lang['AdminCompanyPlugins.installed.btn_uninstall'] = "Desinstalar";
$lang['AdminCompanyPlugins.installed.btn_manage'] = "Gerir";
$lang['AdminCompanyPlugins.installed.text_none'] = "Não há plugins instalados.";
$lang['AdminCompanyPlugins.installed.page_title'] = "Definições > Empresa > Plugins > Instalados";
$lang['AdminCompanyPlugins.available.text_version'] = "(ver %1\$s)"; // %1$s is the version number of the plugin
$lang['AdminCompanyPlugins.installed.text_version'] = "(ver %1\$s)"; // %1$s is the version number of the plugin
$lang['AdminCompanyPlugins.!success.enabled'] = "O plugin foi ativado com sucesso.";
$lang['AdminCompanyPlugins.installed.confirm_disable'] = "Desativar este plugin?";
?>