<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyThemes.!error.import_file.missing'] = "Por favor, carregue um tema a ser importado";
$lang['AdminCompanyThemes.!success.theme_deleted'] = "O tema \"%1\$s\" foi apagado com sucesso."; // %1$s is the name of the theme
$lang['AdminCompanyThemes.!success.theme_updated'] = "O tema \"%1\$s\" foi atualizado com sucesso."; // %1$s is the name of the theme
$lang['AdminCompanyThemes.!success.theme_added'] = "O tema \"%1\$s\" foi adicionado com êxito."; // %1$s is the name of the theme
$lang['AdminCompanyThemes.index.boxtitle_themes'] = "Temas";
$lang['AdminCompanyThemes.index.categorylink_addtheme'] = "Adicionar Tema";
$lang['AdminCompanyThemes.index.field_themessubmit'] = "Escolher Tema";
$lang['AdminCompanyThemes.index.heading_color'] = "Esquema de Cores";
$lang['AdminCompanyThemes.index.heading_name'] = "Nome";
$lang['AdminCompanyThemes.index.heading_options'] = "Opções";
$lang['AdminCompanyThemes.index.option_edit'] = "Editar";
$lang['AdminCompanyThemes.index.option_delete'] = "Apagar";
$lang['AdminCompanyThemes.index.option_export'] = "Exportar";
$lang['AdminCompanyThemes.index.confirm_deletetheme'] = "Tem a certeza de que quer apagar este tema?";
$lang['AdminCompanyThemes.!theme.tooltip_theme_subnavigation_text_color'] = "Define a cor do texto da subnavegação do cabeçalho.";
$lang['AdminCompanyThemes.!theme.tooltip_theme_link_color'] = "Define a cor das hiperligações";
$lang['AdminCompanyThemes.add.boxtitle_addtheme'] = "Novo Tema";
$lang['AdminCompanyThemes.add.heading_options'] = "Criar Opções do Tema";
$lang['AdminCompanyThemes.add.heading_import'] = "Importar Tema";
$lang['AdminCompanyThemes.add.heading_manual'] = "Opções de Tema";
$lang['AdminCompanyThemes.add.add_type_import'] = "Importar um tema";
$lang['AdminCompanyThemes.add.field_import_file'] = "Importar Ficheiro de Team";
$lang['AdminCompanyThemes.add.field_name'] = "Nome";
$lang['AdminCompanyThemes.add.field_addthemesubmit'] = "Criar Tema";
$lang['AdminCompanyThemes.add.field_theme_link_color'] = "Cor de texto do Link";
$lang['AdminCompanyThemes.edit.boxtitle_edittheme'] = "Editar Tema";
$lang['AdminCompanyThemes.edit.field_name'] = "Nome";
$lang['AdminCompanyThemes.edit.field_editthemesubmit'] = "Atualizar tema";
$lang['AdminCompanyThemes.edit.field_theme_page_title_text_color'] = "Cor do Texto do Título da Página";
?>