<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyClientOptions.customfields.text_name'] = "Nome";
$lang['AdminCompanyClientOptions.customfields.text_type'] = "Tipo";
$lang['AdminCompanyClientOptions.customfields.text_read_only'] = "Somente leitura para clientes";
$lang['AdminCompanyClientOptions.customfields.text_yes'] = "Sim";
$lang['AdminCompanyClientOptions.customfields.text_no'] = "Não";
$lang['AdminCompanyClientOptions.customfields.option_edit'] = "Editar";
$lang['AdminCompanyClientOptions.customfields.option_delete'] = "Apagar";
$lang['AdminCompanyClientOptions.addcustomfield.field_client_group_id'] = "Grupo de Clientes";
$lang['AdminCompanyClientOptions.addcustomfield.field_addsubmit'] = "Adicionar Campo Personalizado";
$lang['AdminCompanyClientOptions.addcustomfield.field_checkbox_value'] = "Valor";
$lang['AdminCompanyClientOptions.addcustomfield.heading_select_value'] = "Valor";
$lang['AdminCompanyClientOptions.addcustomfield.text_remove'] = "Remover";
$lang['AdminCompanyClientOptions.editcustomfield.field_type'] = "Tipo";
$lang['AdminCompanyClientOptions.editcustomfield.field_encrypted'] = "Criptografar Valores";
$lang['AdminCompanyClientOptions.editcustomfield.field_editsubmit'] = "Editar Campo Personalizado";
$lang['AdminCompanyClientOptions.editcustomfield.text_remove'] = "Remover";
$lang['AdminCompanyClientOptions.getRequired.no'] = "Não";
$lang['AdminCompanyClientOptions.getRequired.yes'] = "Sim";
$lang['AdminCompanyClientOptions.requiredfields.field_title'] = "Título";
$lang['AdminCompanyClientOptions.requiredfields.field_address1'] = "Endereço 1";
$lang['AdminCompanyClientOptions.requiredfields.field_address2'] = "Endereço 2";
$lang['AdminCompanyClientOptions.requiredfields.field_city'] = "Cidade";
$lang['AdminCompanyClientOptions.requiredfields.field_country'] = "País";
$lang['AdminCompanyClientOptions.requiredfields.field_state'] = "Estado/Província";
$lang['AdminCompanyClientOptions.requiredfields.field_zip'] = "Código Postal";
$lang['AdminCompanyClientOptions.requiredfields.text_submit'] = "Atualizar Definições";
?>