<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyGateways.!success.manage_updated'] = "O gateway foi atualizado com sucesso.";
$lang['AdminCompanyGateways.!success.uninstalled'] = "O gateway foi desinstalado com sucesso.";
$lang['AdminCompanyGateways.available.heading_merchant'] = "Comerciante";
$lang['AdminCompanyGateways.available.text_author'] = "Autor:";
$lang['AdminCompanyGateways.available.text_author_url'] = "URL do Autor";
$lang['AdminCompanyGateways.available.text_merchantach'] = "ACH";
$lang['AdminCompanyGateways.available.text_merchantcc'] = "Cartão de Crédito";
$lang['AdminCompanyGateways.available.text_merchant_none'] = "Não existem Gateways de Mercador disponíveis.";
$lang['AdminCompanyGateways.available.btn_install'] = "Instalar";
$lang['AdminCompanyGateways.installed.heading_merchant'] = "Mercador";
$lang['AdminCompanyGateways.installed.text_author'] = "Autor:";
$lang['AdminCompanyGateways.installed.text_merchantach'] = "ACH";
$lang['AdminCompanyGateways.installed.text_merchantcc'] = "Cartão de Crédito";
$lang['AdminCompanyGateways.installed.text_merchantccoffsite'] = "Cartão de Crédito offsite";
$lang['AdminCompanyGateways.installed.btn_uninstall'] = "Desinstalar";
$lang['AdminCompanyGateways.installed.btn_manage'] = "Gerir";
$lang['AdminCompanyGateways.manage.boxtitle_manage'] = "Gerir %1\$s"; // %1$s is the name of the gateway
$lang['AdminCompanyGateways.manage.heading_gateway'] = "Opções de Gateway";
$lang['AdminCompanyGateways.available.signup_url'] = "Registar";
$lang['AdminCompanyGateways.installed.page_title'] = "Definições > Empresa > Gateways > Instalados";
$lang['AdminCompanyGateways.installed.signup_url'] = "Registar";
$lang['AdminCompanyGateways.available.text_version'] = "(ver %1\$s)"; // %1$s is the version number of this gateway
$lang['AdminCompanyGateways.installed.text_version'] = "(ver %1\$s)"; // %1$s is the version number of this gateway
$lang['AdminCompanyGateways.manage.text_in_use_by'] = "em uso por";
$lang['AdminCompanyGateways.!tab.available'] = "Disponível";
?>