<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyGeneral.!success.localization_updated'] = "A configuração da localização foi atualizada com sucesso.";
$lang['AdminCompanyGeneral.!success.contact_type_added'] = "O tipo de contacto \"%1\$s\" foi adicionado com sucesso."; // %1$s is the name of the contact type
$lang['AdminCompanyGeneral.!success.contact_type_deleted'] = "O tipo de contact \"%1\$s\" foi apagado com sucesso."; // %1$s is the name of the contact type
$lang['AdminCompanyGeneral.localization.tz_format'] = "(UTC %1\$s) %2\$s"; // %1$s is the UTC offset, %2$s is the timezone name
$lang['AdminCompanyGeneral.localization.text_language'] = "Linguagem predefinida";
$lang['AdminCompanyGeneral.localization.text_calendar'] = "Dia de Início de Calendário";
$lang['AdminCompanyGeneral.localization.text_sunday'] = "Domingo";
$lang['AdminCompanyGeneral.localization.text_monday'] = "Segunda-feira";
$lang['AdminCompanyGeneral.localization.text_dateformat'] = "Formato da data";
$lang['AdminCompanyGeneral.localization.text_localizationsubmit'] = "Atualizar Definições";
$lang['AdminCompanyGeneral.international.boxtitle_international'] = "Internacionalização";
$lang['AdminCompanyGeneral.international.text_language'] = "Idioma";
$lang['AdminCompanyGeneral.international.text_iso'] = "ISO 639-1, 3166-1";
$lang['AdminCompanyGeneral.international.text_options'] = "Opções";
$lang['AdminCompanyGeneral.international.option_install'] = "Instalar";
$lang['AdminCompanyGeneral.international.option_uninstall'] = "Desinstalar";
$lang['AdminCompanyGeneral.encryption.boxtitle_encryption'] = "Encriptação";
$lang['AdminCompanyGeneral.encryption.field_agree'] = "Guardei a Password num local seguro";
$lang['AdminCompanyGeneral.contacttypes.categorylink_addtype'] = "Criar Tipo de Contacto";
$lang['AdminCompanyGeneral.contacttypes.boxtitle_types'] = "Tipos de Contacto";
$lang['AdminCompanyGeneral.contacttypes.heading_name'] = "Nome";
$lang['AdminCompanyGeneral.contacttypes.text_yes'] = "Sim";
$lang['AdminCompanyGeneral.contacttypes.text_no'] = "Não";
$lang['AdminCompanyGeneral.contacttypes.option_edit'] = "Editar";
$lang['AdminCompanyGeneral.contacttypes.option_delete'] = "Apagar";
$lang['AdminCompanyGeneral.addcontacttype.boxtitle_addcontacttype'] = "Criar Tipo de Contacto";
$lang['AdminCompanyGeneral.addcontacttype.field_name'] = "Nome";
$lang['AdminCompanyGeneral.addcontacttype.field_contacttypesubmit'] = "Criar Tipo de Contacto";
$lang['AdminCompanyGeneral.editcontacttype.boxtitle_editcontacttype'] = "Editar Tipo de Contacto";
$lang['AdminCompanyGeneral.editcontacttype.field_name'] = "Nome";
$lang['AdminCompanyGeneral.editcontacttype.field_contacttypesubmit'] = "Editar Tipo de Contacto";
$lang['AdminCompanyGeneral.localization.page_title'] = "Definições > Empresa > Geral > Localização";
$lang['AdminCompanyGeneral.international.page_title'] = "Configurações > Empresa > Geral > Internacionalização";
$lang['AdminCompanyGeneral.encryption.page_title'] = "Definições > Empresa > Geral > Encriptação";
$lang['AdminCompanyGeneral.contacttypes.page_title'] = "Configurações > Empresa > Geral > Tipos de Contato
";
$lang['AdminCompanyGeneral.addcontacttype.page_title'] = "Definições > Empresa > Geral > Criar Tipo de Contacto";
$lang['AdminCompanyGeneral.editcontacttype.page_title'] = "Definições > Empresa > Geral > Editar Tipo de Contacto";
$lang['AdminCompanyGeneral.!success.language_installed'] = "A língua %1\$s foi instalada com sucesso."; // %1$s is the name of the language
$lang['AdminCompanyGeneral.international.confirm_install'] = "Tem a certeza de que quer instalar a linguagem %1\$s?"; // %1$s is the name of the language
$lang['AdminCompanyGeneral.contacttypes.no_results'] = "Não existem Tipos de Contactos.";
$lang['AdminCompanyGeneral.localization.boxtitle_localization'] = "Localização";
?>