<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyBilling.!success.invoices_updated'] = "As definições de Faturação e Cobrança foram atualizadas com sucesso!";
$lang['AdminCompanyBilling.!success.notices_updated'] = "Os Avisos de Pagamentos Vencidos foram atualizados com sucesso!";
$lang['AdminCompanyBilling.!success.coupon_created'] = "O cupão foi criado com sucesso!";
$lang['AdminCompanyBilling.!success.coupon_updated'] = "O cupão foi actualizado com sucesso!";
$lang['AdminCompanyBilling.!success.acceptedtypes_updated'] = "As definições do Tipo de Pagamentos Aceites foram atualizadas com sucesso!";
$lang['AdminCompanyBilling.!success.deliverymethods_updated'] = "As definições de Entrega de Faturas foram atualizadas com sucesso!";
$lang['AdminCompanyBilling.!success.customization_updated'] = "As definições de Personalização de Faturas foram atualizadas com sucesso!";
$lang['AdminCompanyBilling.invoices.field_suspend_services'] = "Faturar Serviços Suspensos";
$lang['AdminCompanyBilling.invoices.field_invoicessubmit'] = "Atualizar Definições";
$lang['AdminCompanyBilling.invoices.text_sameday'] = "Mesmo Dia";
$lang['AdminCompanyBilling.notices.text_notices'] = "Os avisos podem ser usados como avisos de atraso ou lembretes de pagamento.";
$lang['AdminCompanyBilling.notices.text_before'] = "Antes";
$lang['AdminCompanyBilling.notices.text_after'] = "Depois";
$lang['AdminCompanyBilling.notices.text_duedate'] = "Data de Vencimento";
$lang['AdminCompanyBilling.notices.text_disabled'] = "Desativado";
$lang['AdminCompanyBilling.notices.field_second_notice'] = "Segundo Aviso";
$lang['AdminCompanyBilling.coupons.no_results'] = "Não existem cupões.";
$lang['AdminCompanyBilling.coupons.categorylink_addcoupon'] = "Adicionar Rifa";
$lang['AdminCompanyBilling.coupons.boxtitle_coupons'] = "Cupões";
$lang['AdminCompanyBilling.coupons.text_code'] = "Código";
$lang['AdminCompanyBilling.coupons.text_discount'] = "Desconto";
$lang['AdminCompanyBilling.coupons.text_max'] = "Máx";
$lang['AdminCompanyBilling.coupons.text_start_date'] = "Data de início";
$lang['AdminCompanyBilling.coupons.text_end_date'] = "Data de Vencimento";
$lang['AdminCompanyBilling.coupons.text_options'] = "Opções";
$lang['AdminCompanyBilling.coupons.option_edit'] = "Editar";
$lang['AdminCompanyBilling.coupons.option_delete'] = "Apagar";
$lang['AdminCompanyBilling.coupons.confirm_delete'] = "Tem a certeza de que deseja apagar este cupão?";
$lang['AdminCompanyBilling.addcoupon.boxtitle_new'] = "Novo Cupão";
$lang['AdminCompanyBilling.addcoupon.heading_basic'] = "Básico";
$lang['AdminCompanyBilling.addcoupon.field_recurring_no'] = "Aplicar quando o serviço é apenas adicionado
";
$lang['AdminCompanyBilling.addcoupon.field_recurring_yes'] = "Aplicar quando o serviço é adicionado ou renovado";
$lang['AdminCompanyBilling.addcoupon.text_generate_code'] = "Gerar Código";
$lang['AdminCompanyBilling.addcoupon.heading_limitations'] = "Limitações";
$lang['AdminCompanyBilling.addcoupon.field_end_date'] = "Data de Fim";
$lang['AdminCompanyBilling.addcoupon.field_max_qty'] = "Quantidade";
$lang['AdminCompanyBilling.addcoupon.heading_discount'] = "Opções do Desconto";
$lang['AdminCompanyBilling.addcoupon.categorylink_addcurrency'] = "Adicionar Moeda Adicional";
$lang['AdminCompanyBilling.addcoupon.text_currency'] = "Moeda";
$lang['AdminCompanyBilling.addcoupon.text_type'] = "Tipo";
$lang['AdminCompanyBilling.addcoupon.text_value'] = "Valor";
$lang['AdminCompanyBilling.addcoupon.option_remove'] = "Remover";
$lang['AdminCompanyBilling.addcoupon.heading_packages'] = "Pacotes";
$lang['AdminCompanyBilling.addcoupon.field_couponsubmit'] = "Criar Cupão";
$lang['AdminCompanyBilling.addcoupon.text_assigned_packages'] = "Pacotes Alocados";
$lang['AdminCompanyBilling.addcoupon.text_available_packages'] = "Pacotes Disponíveis";
$lang['AdminCompanyBilling.editcoupon.boxtitle_edit'] = "Editar Cupão";
$lang['AdminCompanyBilling.editcoupon.heading_basic'] = "Básico";
$lang['AdminCompanyBilling.editcoupon.field_recurring_no'] = "Aplicar apenas quando o serviço é adicionado";
$lang['AdminCompanyBilling.editcoupon.field_code'] = "Código de Cupão";
$lang['AdminCompanyBilling.editcoupon.text_generate_code'] = "Gerar código";
$lang['AdminCompanyBilling.editcoupon.heading_limitations'] = "Limitações";
$lang['AdminCompanyBilling.editcoupon.heading_discount'] = "Opções de Desconto";
$lang['AdminCompanyBilling.editcoupon.text_currency'] = "Moeda";
$lang['AdminCompanyBilling.editcoupon.text_type'] = "Tipo";
$lang['AdminCompanyBilling.editcoupon.text_value'] = "Valor";
$lang['AdminCompanyBilling.editcoupon.option_remove'] = "Remover";
$lang['AdminCompanyBilling.editcoupon.heading_packages'] = "Pacotes";
$lang['AdminCompanyBilling.editcoupon.field_couponsubmit'] = "Editar Cupão";
$lang['AdminCompanyBilling.editcoupon.text_assigned_packages'] = "Pacotes Atribuídos";
$lang['AdminCompanyBilling.editcoupon.text_available_packages'] = "Pacotes Disponíveis";
$lang['AdminCompanyBilling.editcoupon.text_used_qty'] = "(%1\$s usado)"; // %1$s is the number of used coupons
$lang['AdminCompanyBilling.customization.boxtitle_customization'] = "Personalização da Fatura";
$lang['AdminCompanyBilling.customization.heading_general'] = "Opções Básicas";
$lang['AdminCompanyBilling.customization.field_inv_format'] = "Formato da Fatura";
$lang['AdminCompanyBilling.customization.field_inv_increment'] = "Valor Incremental da Fatura";
$lang['AdminCompanyBilling.customization.field_inv_logo'] = "Logótipo";
$lang['AdminCompanyBilling.customization.field_inv_terms'] = "Termos";
$lang['AdminCompanyBilling.customization.field_inv_template'] = "Template de Fatura";
$lang['AdminCompanyBilling.customization.field_inv_display_logo'] = "Logo";
$lang['AdminCompanyBilling.customization.field_inv_display_company'] = "Nome/Endereço da Empresa";
$lang['AdminCompanyBilling.customization.remove'] = "Remover";
$lang['AdminCompanyBilling.acceptedtypes.boxtitle_types'] = "Tipos de pagamento aceites";
$lang['AdminCompanyBilling.acceptedtypes.field_cc'] = "Cartão de Crédito";
$lang['AdminCompanyBilling.acceptedtypes.field_ach'] = "Automated Clearing House";
$lang['AdminCompanyBilling.acceptedtypes.field_typessubmit'] = "Atualizar Definições";
$lang['AdminCompanyBilling.acceptedtypes.text_description'] = "Apenas os tipos de pagamento selecionados estão disponíveis para processamento através de gateways ou pedem ser adicionados como contas de pagamento, mesmo que um gateway ativo suporte o tipo. Desselecionar o tipo que já é aceite irá fazer com que os pagamentos desse tipo não seja processados.";
$lang['AdminCompanyBilling.deliverymethods.heading_basic'] = "Opções Básicas";
$lang['AdminCompanyBilling.deliverymethods.heading_interfax'] = "InterFax";
$lang['AdminCompanyBilling.deliverymethods.interfax_desc'] = "Interfax permite o envio de faturas via fax através da internet. <a href=\"http://www.interfax.net/\" target=\"_blank\"> Registe-se </a> e comece a envia faturas via fax hoje.";
$lang['AdminCompanyBilling.deliverymethods.field_delivery_methods'] = "Métodos de Entrega de Faturas";
$lang['AdminCompanyBilling.deliverymethods.field_interfax_username'] = "Nome de Utilizador";
$lang['AdminCompanyBilling.deliverymethods.field_interfax_password'] = "Palavra-passe";
$lang['AdminCompanyBilling.deliverymethods.field_postalmethods_testmode'] = "Modo de Teste";
$lang['AdminCompanyBilling.deliverymethods.field_submit'] = "Actualizar Definições";
$lang['AdminCompanyBilling.!tooltip.coupon_quantity'] = "A quantidade representa o número máximo de vezes que este cupão pode ser utilizado antes de expirar.";
$lang['AdminCompanyBilling.invoices.text_never'] = "Nunca";
$lang['AdminCompanyBilling.addcoupon.field_limit_recurring_no'] = "As limitações não se aplicam à renovação de serviços";
$lang['AdminCompanyBilling.addcoupon.text_all'] = "Todos";
$lang['AdminCompanyBilling.editcoupon.page_title'] = "Definições > Empresa > Faturação/Pagamento > Editar Cupão";
$lang['AdminCompanyBilling.editcoupon.text_all'] = "Todos";
$lang['AdminCompanyBilling.customization.page_title'] = "Definições > Empresa > Faturação/Pagamento > Personalização de Fatura";
$lang['AdminCompanyBilling.customization.field_inv_display_paid_watermark'] = "Marca de Água PAGO";
$lang['AdminCompanyBilling.customization.note_inv_start'] = "Os números de fatura irão começar (e continuar) a partir deste valor inicial.";
$lang['AdminCompanyBilling.customization.note_inv_increment'] = "Os números de faturas subsequentes aumentarão por este valor.";
$lang['AdminCompanyBilling.acceptedtypes.page_title'] = "Definições > Empresa > Faturação/Pagamento > Tipos de Pagamento Aceites";
$lang['AdminCompanyBilling.deliverymethods.page_title'] = "Definições > Empresa > Facturação/Pagamento > Entrega de Factura";
$lang['AdminCompanyBilling.deliverymethods.field_postalmethods_apikey'] = "Chave API";
$lang['AdminCompanyBilling.!notice.group_settings'] = "NOTA: Estas definições apenas se aplicam aos Grupos de Clientes que herdam as suas definições da Empresa.";
$lang['AdminCompanyBilling.invoices.text_day'] = "%1\$s Dia"; // %1$s is the number 1
$lang['AdminCompanyBilling.invoices.text_days'] = "%1\$s Dias"; // %1$s is a number of days that is not 1
$lang['AdminCompanyBilling.notices.text_day'] = "%1\$s Dia"; // %1$s is the number 1
$lang['AdminCompanyBilling.notices.text_days'] = "%1\$s Dias"; // %1$s is a number of days that is not 1
$lang['AdminCompanyBilling.!success.coupon_deleted'] = "O cupão foi apagado com sucesso!";
$lang['AdminCompanyBilling.customization.field_inv_proforma_format'] = "Formato de Fatura Pró Forma";
$lang['AdminCompanyBilling.customization.field_inv_type'] = "Tipo de Fatura";
$lang['AdminCompanyBilling.!tooltip.send_payment_notices'] = "Esta opção define se os clientes podem receber algum dos avisos de pagamento disponíveis.";
$lang['AdminCompanyBilling.invoices.field_autodebit'] = "Ativar Débito Automático";
$lang['AdminCompanyBilling.invoices.field_client_prorate_credits'] = "Permitir que os créditos pré-emitidos sejam emitidos por baixas de serviço";
$lang['AdminCompanyBilling.addcoupon.field_apply_package_options'] = "Aplicar às opções configuráveis";
$lang['AdminCompanyBilling.invoices.field_inv_group_services'] = "Faturar serviços juntamente";
$lang['AdminCompanyBilling.addcoupon.text_enabled'] = "Ativado";
$lang['AdminCompanyBilling.editcoupon.text_enabled'] = "Ativado";
?>