<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSearch.!notice.results_truncated'] = "O número de resultados foi truncado. Deverá redefinir a sua pesquisa.";
$lang['AdminSearch.index.page_title'] = "Resultados da pesquisa para \"%1\$s\""; // %1$s is the criteria being searched for
$lang['AdminSearch.index.boxtitle_search'] = "Resultados da pesquisa por \"%1\$s\""; // %1$s is the criteria being searched for
$lang['AdminSearch.clients.heading'] = "Clientes";
$lang['AdminSearch.clients.heading_client_id'] = "ID de Cliente";
$lang['AdminSearch.clients.heading_group'] = "Grupo";
$lang['AdminSearch.clients.heading_name'] = "Nome";
$lang['AdminSearch.clients.heading_company'] = "Empresa";
$lang['AdminSearch.clients.heading_address'] = "Endereço";
$lang['AdminSearch.clients.heading_email'] = "Email";
$lang['AdminSearch.clients.no_results'] = "Não há clientes que correspondem aos critérios de pesquisa.";
$lang['AdminSearch.invoices.heading'] = "Faturas";
$lang['AdminSearch.invoice.heading_invoice'] = "Fatura #";
$lang['AdminSearch.invoice.heading_client_id'] = "ID de Cliente";
$lang['AdminSearch.invoice.heading_amount'] = "Opções";
$lang['AdminSearch.invoice.heading_paid'] = "Pago";
$lang['AdminSearch.invoice.heading_due'] = "Vencimento";
$lang['AdminSearch.invoice.heading_date_closed'] = "Data de Fecho";
$lang['AdminSearch.invoice.heading_date_due'] = "Data Limite";
$lang['AdminSearch.invoice.heading_sent'] = "Enviado";
$lang['AdminSearch.invoice.heading_status'] = "Estado";
$lang['AdminSearch.invoice.option_view'] = "Ver";
$lang['AdminSearch.invoices.status_open'] = "Aberto";
$lang['AdminSearch.invoices.status_closed'] = "Fechado";
$lang['AdminSearch.invoices.status_void'] = "Anulado";
$lang['AdminSearch.invoices.status_sent'] = "Enviada";
$lang['AdminSearch.invoices.status_unsent'] = "Não enviado";
$lang['AdminSearch.invoice.no_results'] = "Não há notas fiscais que correspondem aos critérios de procura.";
$lang['AdminSearch.transactions.heading'] = "Transações";
$lang['AdminSearch.transactions.heading_client_id'] = "ID de Cliente";
$lang['AdminSearch.transactions.heading_type'] = "Tipo";
$lang['AdminSearch.transactions.heading_amount'] = "Montante";
$lang['AdminSearch.transactions.heading_credited'] = "Creditado";
$lang['AdminSearch.transactions.heading_applied'] = "Aplicado";
$lang['AdminSearch.transactions.heading_number'] = "Número";
$lang['AdminSearch.transactions.heading_status'] = "Estado";
$lang['AdminSearch.transactions.heading_date'] = "Data";
$lang['AdminSearch.transactions.heading_options'] = "Opções";
$lang['AdminSearch.transactions.no_results'] = "Não existem transações que correspondam com o critério de pesquisa.";
$lang['AdminSearch.packages.heading'] = "Pacotes";
$lang['AdminSearch.packages.heading_package_id'] = "ID do Pacote";
$lang['AdminSearch.packages.heading_name'] = "Nome";
$lang['AdminSearch.packages.heading_module'] = "Módulo";
$lang['AdminSearch.packages.heading_quantity'] = "Quantidade";
$lang['AdminSearch.packages.heading_status'] = "Estado";
$lang['AdminSearch.services.heading'] = "Serviços";
$lang['AdminSearch.services.heading_client_id'] = "ID de Cliente";
$lang['AdminSearch.services.heading_package'] = "Pacote";
$lang['AdminSearch.services.heading_term'] = "Termo";
$lang['AdminSearch.services.heading_status'] = "Estado";
$lang['AdminSearch.services.text_never'] = "Nunca";
$lang['AdminSearch.services.no_results'] = "Não há serviços que correspondam aos critérios de procura.";
$lang['AdminSearch.services.heading_client'] = "Cliente";
?>