<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminReportsCustomize.index.box_title'] = "Relatórios";
$lang['AdminReportsCustomize.index.reports'] = "Gerar";
$lang['AdminReportsCustomize.index.table_options'] = "Opções";
$lang['AdminReportsCustomize.index.table_option_edit'] = "Editar";
$lang['AdminReportsCustomize.index.btn_add_report'] = "Adicionar Relatório";
$lang['AdminReportsCustomize.add.page_title'] = "Relatórios de Contabilidade";
$lang['AdminReportsCustomize.add.field_name'] = "Nome";
$lang['AdminReportsCustomize.add.heading_fields'] = "Campos";
$lang['AdminReportsCustomize.add.field_add_field'] = "Adicionar Campo";
$lang['AdminReportsCustomize.add.table_name'] = "Nome";
$lang['AdminReportsCustomize.add.table_label'] = "Etiqueta";
$lang['AdminReportsCustomize.add.table_type'] = "Tipo";
$lang['AdminReportsCustomize.add.table_options'] = "Opções";
$lang['AdminReportsCustomize.edit.page_title'] = "Relatórios de Faturação";
$lang['AdminReportsCustomize.edit.heading_fields'] = "Campos";
$lang['AdminReportsCustomize.edit.table_name'] = "Nome";
$lang['AdminReportsCustomize.edit.table_label'] = "Etiqueta";
$lang['AdminReportsCustomize.edit.table_type'] = "Tipo";
$lang['AdminReportsCustomize.edit.table_required'] = "Necessário";
$lang['AdminReportsCustomize.edit.table_options'] = "Opções";
$lang['AdminReportsCustomize.edit.text_remove'] = "Remover";
$lang['AdminReportsCustomize.edit.field_submit'] = "Guardar";
?>