<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyGroups.!success.add_created'] = "%1\$s foi criado com sucesso!"; // %1$s is the name of the client group
$lang['AdminCompanyGroups.!success.edit_updated'] = "%1\$s foi editar com sucesso!"; // %1$s is the name of the client group
$lang['AdminCompanyGroups.!success.delete_deleted'] = "%1\$s foi apagado com sucesso!"; // %1$s is the name of the client group
$lang['AdminCompanyGroups.!error.delete_failed'] = "%1\$s é o grupo por defeito e não pode ser apagado."; // %1$s is the name of the client group
$lang['AdminCompanyGroups.index.boxtitle_groups'] = "Grupos de Clientes";
$lang['AdminCompanyGroups.index.categorylink_addgroup'] = "Criar Grupo";
$lang['AdminCompanyGroups.index.text_name'] = "Nome";
$lang['AdminCompanyGroups.index.text_description'] = "Descrição";
$lang['AdminCompanyGroups.index.text_clients'] = "Numero de Clientes";
$lang['AdminCompanyGroups.index.text_options'] = "Opções";
$lang['AdminCompanyGroups.index.option_edit'] = "Editar";
$lang['AdminCompanyGroups.index.option_delete'] = "Apagar";
$lang['AdminCompanyGroups.index.no_results'] = "Não existem grupos de clientes.";
$lang['AdminCompanyGroups.add.boxtitle_addgroup'] = "Criar Grupo";
$lang['AdminCompanyGroups.add.heading_basic'] = "Opções Básicas";
$lang['AdminCompanyGroups.add.heading_delivery'] = "Entrega de Fatura";
$lang['AdminCompanyGroups.add.heading_payment'] = "Avisos de pagamento em atraso";
$lang['AdminCompanyGroups.add.field_name'] = "Nome";
$lang['AdminCompanyGroups.add.field_color'] = "Cor";
$lang['AdminCompanyGroups.add.field_description'] = "Descrição";
$lang['AdminCompanyGroups.add.field_delivery_methods'] = "Métodos de Entrega de Faturas";
$lang['AdminCompanyGroups.add.field_company_settings'] = "Use Configurações da empresa (desmarque para especificar abaixo)";
$lang['AdminCompanyGroups.add.text_addsubmit'] = "Criar Grupo";
$lang['AdminCompanyGroups.edit.boxtitle_editgroup'] = "Editar Grupo";
$lang['AdminCompanyGroups.edit.heading_basic'] = "Opções Básicas";
$lang['AdminCompanyGroups.edit.heading_invoice'] = "Fatura e Opções de Pagamento";
$lang['AdminCompanyGroups.edit.field_color'] = "Cor";
$lang['AdminCompanyGroups.edit.field_description'] = "Descrição";
$lang['AdminCompanyGroups.edit.field_delivery_methods'] = "Métodos de Entrega de Faturas";
$lang['AdminCompanyGroups.edit.text_editsubmit'] = "Editar Grupo";
$lang['AdminCompanyGroups.index.page_title'] = "Definições > Empresa > Grupos de Clientes";
$lang['AdminCompanyGroups.add.page_title'] = "Definições > Empresa > Grupos de Clientes > Criar Grupo";
?>