<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSystemBackup.!error.sftp_test'] = "A ligação SFTP falhou! Por facor verifique as definições e tente novamente.";
$lang['AdminSystemBackup.!error.amazons3_test'] = "A ligação ao AmazonS3 falhou! Por favor verifique as suas definições e tente novamente. Tenha atenção que os detalhes da ligação são sensíveis a maiúsculas e minúsculas.";
$lang['AdminSystemBackup.ftp.boxtitle_backup'] = "FTP Seguro";
$lang['AdminSystemBackup.ftp.field_host'] = "Hostname";
$lang['AdminSystemBackup.ftp.field_port'] = "Porta";
$lang['AdminSystemBackup.ftp.field_username'] = "Nome de utilizador";
$lang['AdminSystemBackup.ftp.field_password'] = "Palavra-passe";
$lang['AdminSystemBackup.ftp.field_path'] = "Caminho";
$lang['AdminSystemBackup.ftp.field_rate'] = "Efetuar Copia de Segurança a cada";
$lang['AdminSystemBackup.ftp.field_backupsubmit'] = "Atualizar Definições";
$lang['AdminSystemBackup.index.field_uploadbackup'] = "Forçar Backup Externo";
$lang['AdminSystemBackup.!error.backup_frequency'] = "Frequência da cópia de segurança inválida.";
$lang['AdminSystemBackup.ftp.page_title'] = "Definições > Sistema > Backup > FTP Seguro";
$lang['AdminSystemBackup.amazon.page_title'] = "Definições > Sistema > Cópias de Segurança> Amazon S3";
$lang['AdminSystemBackup.amazon.boxtitle_backup'] = "Amazon S3";
$lang['AdminSystemBackup.amazon.field_accesskey'] = "Chave de Acesso";
$lang['AdminSystemBackup.amazon.field_secretkey'] = "Chave Secreta";
$lang['AdminSystemBackup.amazon.field_bucket'] = "Balde";
$lang['AdminSystemBackup.amazon.field_backupsubmit'] = "Atualizar Definições";
$lang['AdminSystemBackup.index.field_downloadbackup'] = "Download Backup";
$lang['AdminSystemBackup.amazon.field_region'] = "Região";
?>