<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyCurrencies.!success.add_created'] = "A moeda %1\$s foi criada com sucesso!"; // %1$s is the currency code
$lang['AdminCompanyCurrencies.!success.edit_updated'] = "A moeda %1\$s foi actualizada com sucesso!"; // %1$s is the currency code
$lang['AdminCompanyCurrencies.!success.delete_deleted'] = "A moeda %1\$s foi apagada com sucesso!"; // %1$s is the currency code
$lang['AdminCompanyCurrencies.!success.rates_updated'] = "As taxas de câmbio foram atualizadas com sucesso.";
$lang['AdminCompanyCurrencies.setup.boxtitle_setup'] = "Configuração de moeda";
$lang['AdminCompanyCurrencies.setup.heading_general'] = "Geral";
$lang['AdminCompanyCurrencies.setup.field_default_currency'] = "Moeda predefinida";
$lang['AdminCompanyCurrencies.setup.field_show_currency_code'] = "Mostrar o código da moeda.";
$lang['AdminCompanyCurrencies.setup.heading_multicurrency'] = "Multi-Moeda";
$lang['AdminCompanyCurrencies.setup.field_setupsubmit'] = "Atualizar Definições";
$lang['AdminCompanyCurrencies.active.boxtitle_active'] = "Moedas ativas";
$lang['AdminCompanyCurrencies.active.categorylink_addcurrency'] = "Adicionar moeda";
$lang['AdminCompanyCurrencies.active.text_currency_code'] = "Código de Moeda (ISO 4217)";
$lang['AdminCompanyCurrencies.active.text_format'] = "Formato";
$lang['AdminCompanyCurrencies.active.text_exchange_rate'] = "Taxa de Câmbio";
$lang['AdminCompanyCurrencies.active.text_options'] = "Opções";
$lang['AdminCompanyCurrencies.active.option_edit'] = "Editar";
$lang['AdminCompanyCurrencies.active.option_delete'] = "Apagar";
$lang['AdminCompanyCurrencies.active.confirm_delete'] = "Tem a certeza que quer remover esta moeda?";
$lang['AdminCompanyCurrencies.add.field_format'] = "Formato";
$lang['AdminCompanyCurrencies.add.field_suffix'] = "Símbolo de sufixo";
$lang['AdminCompanyCurrencies.add.field_addsubmit'] = "Criar Moeda";
$lang['AdminCompanyCurrencies.edit.boxtitle_edit'] = "Editar Moeda";
$lang['AdminCompanyCurrencies.edit.field_format'] = "Formato";
$lang['AdminCompanyCurrencies.edit.field_exchange_rate'] = "Taxa de câmbio";
$lang['AdminCompanyCurrencies.edit.field_editsubmit'] = "Editar Moeda";
$lang['AdminCompanyCurrencies.!cancel.field_cancel'] = "Cancelar";
$lang['AdminCompanyCurrencies.setup.page_title'] = "Definições > Empresa > Moedas > Configuração de Moeda";
$lang['AdminCompanyCurrencies.setup.no_exchange_updated'] = "Nunca";
$lang['AdminCompanyCurrencies.setup.open_parenthesis'] = "(";
$lang['AdminCompanyCurrencies.setup.closed_parenthesis'] = ")";
$lang['AdminCompanyCurrencies.active.no_exchange_updated'] = "Nunca";
$lang['AdminCompanyCurrencies.add.page_title'] = "Definições > Empresa > Moedas > Adicionar Moeda";
$lang['AdminCompanyCurrencies.edit.page_title'] = "Definições > Empresa > Moedas > Editar Moeda";
$lang['AdminCompanyCurrencies.active.text_precision'] = "Precisão";
$lang['AdminCompanyCurrencies.edit.field_precision'] = "Precisão";
?>