<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSystemGeneral.!success.maintenance_updated'] = "As configurações de manutenção foram actualizadas com sucesso!";
$lang['AdminSystemGeneral.!success.license_updated'] = "A sua Chave de Licença foi actualizada com sucesso!";
$lang['AdminSystemGeneral.!success.edittype_updated'] = "O tipo de pagamento \"%1\$s\" foi atualizado com sucesso!"; // %1$s is the name of the payment type
$lang['AdminSystemGeneral.!success.deletetype_deleted'] = "O tipo de pagamento \"%1\$s\" foi removido com sucesso!"; // %1$s is the name of the payment type
$lang['AdminSystemGeneral.basic.boxtitle_basic'] = "Instalação Básica";
$lang['AdminSystemGeneral.basic.field_tempdir'] = "Pasta Temporária";
$lang['AdminSystemGeneral.basic.field_basicsubmit'] = "Atualizar Definições";
$lang['AdminSystemGeneral.basic.text_days'] = "Dias";
$lang['AdminSystemGeneral.geoip.boxtitle_geoip'] = "GeoIP";
$lang['AdminSystemGeneral.geoip.text_database_not_exists'] = "%1\$s não existe."; // %1$s is a file system path to the GeoIP database file
$lang['AdminSystemGeneral.geoip.field_geoip_enabled'] = "Ativar GeoIP";
$lang['AdminSystemGeneral.geoip.field_geoipsubmit'] = "Actualizar Definições";
$lang['AdminSystemGeneral.maintenance.boxtitle_maintenance'] = "Manutenção";
$lang['AdminSystemGeneral.maintenance.field_maintenancemode'] = "Ativar Modo de Manutenção";
$lang['AdminSystemGeneral.maintenance.field_maintenancesubmit'] = "Atualizar Definições";
$lang['AdminSystemGeneral.license.boxtitle_license'] = "Chave da Licença";
$lang['AdminSystemGeneral.license.field_licensesubmit'] = "Atualizar Definições";
$lang['AdminSystemGeneral.paymenttypes.categorylink_addtype'] = "Criar Tipo de Pagamento";
$lang['AdminSystemGeneral.paymenttypes.boxtitle_types'] = "Tipos de Pagamento";
$lang['AdminSystemGeneral.paymenttypes.heading_name'] = "Nome";
$lang['AdminSystemGeneral.paymenttypes.heading_options'] = "Opções";
$lang['AdminSystemGeneral.paymenttypes.option_edit'] = "Editar";
$lang['AdminSystemGeneral.paymenttypes.option_delete'] = "Apagar";
$lang['AdminSystemGeneral.paymenttypes.text_yes'] = "Sim";
$lang['AdminSystemGeneral.paymenttypes.text_no'] = "Não";
$lang['AdminSystemGeneral.addtype.boxtitle_addtype'] = "Criar Tipo de Pagamento";
$lang['AdminSystemGeneral.addtype.field_name'] = "Nome";
$lang['AdminSystemGeneral.addtype.field_typesubmit'] = "Criar tipo de pagamento";
$lang['AdminSystemGeneral.edittype.field_name'] = "Nome";
$lang['AdminSystemGeneral.edittype.field_is_lang'] = "Use a definição de idioma";
$lang['AdminSystemGeneral.edittype.field_typesubmit'] = "Editar Tipo de Pagamento";
$lang['AdminSystemGeneral.basic.page_title'] = "Definições > Sistema > Geral > Configuração Básica";
$lang['AdminSystemGeneral.geoip.page_title'] = "Configurações> Sistema> Configurações Gerais> GeoIP";
$lang['AdminSystemGeneral.maintenance.page_title'] = "Definições > Sistema > Geral > Manutenção";
$lang['AdminSystemGeneral.paymenttypes.page_title'] = "Definições > Sistema > Geral > Tipos de Pagamento";
$lang['AdminSystemGeneral.addtype.page_title'] = "Definições > Sistema > Geral > Criar Tipo de Pagamento";
$lang['AdminSystemGeneral.paymenttypes.heading_type'] = "Tipo";
$lang['AdminSystemGeneral.addtype.field_type'] = "Tipo";
$lang['AdminSystemGeneral.edittype.field_type'] = "Tipo";
?>