<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSystemCompanies.!success.company_added'] = "A empresa %1\$s foi criada com sucesso!"; // %1$s is the name of the company
$lang['AdminSystemCompanies.!success.company_edited'] = "A empresa %1\$s foi atualizada com sucesso!"; // %1$s is the name of the company
$lang['AdminSystemCompanies.index.boxtitle_companies'] = "Empresas";
$lang['AdminSystemCompanies.index.no_results'] = "Não existem empresas.";
$lang['AdminSystemCompanies.index.text_name'] = "Nome ";
$lang['AdminSystemCompanies.index.text_address'] = "Endereço";
$lang['AdminSystemCompanies.index.text_phone'] = "Telefone";
$lang['AdminSystemCompanies.index.text_options'] = "Opções";
$lang['AdminSystemCompanies.index.option_edit'] = "Editar";
$lang['AdminSystemCompanies.add.boxtitle_addcompany'] = "Adicionar Empresa";
$lang['AdminSystemCompanies.add.field_company'] = "Importar Definições de Empresa de";
$lang['AdminSystemCompanies.add.field_name'] = "Nome";
$lang['AdminSystemCompanies.add.field_address'] = "Endereço";
$lang['AdminSystemCompanies.add.field_phone'] = "Telefone";
$lang['AdminSystemCompanies.add.field_fax'] = "Fax";
$lang['AddSystemCompanies.add.field_companysubmit'] = "Criar Empresa";
$lang['AdminSystemCompanies.edit.boxtitle_editcompany'] = "Editar Empresa";
$lang['AdminSystemCompanies.edit.field_name'] = "Nome";
$lang['AdminSystemCompanies.edit.field_hostname'] = "Hostname";
$lang['AddSystemCompanies.edit.field_companysubmit'] = "Editar Empresa";
$lang['AdminSystemCompanies.index.page_title'] = "Definições > Sistema > Empresas";
$lang['AdminSystemCompanies.index.text_hostname'] = "Hostname";
$lang['AdminSystemCompanies.add.page_title'] = "Definições > Sistema > Empresas > Adicionar Empresa";
$lang['AdminSystemCompanies.edit.page_title'] = "Definições > Sistema > Empresas > Editar Empresa";
$lang['AdminSystemCompanies.!success.company_deleted'] = "A empresa %1\$s foi removida com sucesso!"; // %1$s is the name of the company
$lang['AdminSystemCompanies.index.option_delete'] = "Apagar";
?>