<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminPackageOptions.!success.option_updated'] = "A opção do pacote foi actualizada com sucesso.";
$lang['AdminPackageOptions.!success.option_deleted'] = "A opção do pacote foi apagada com sucesso.";
$lang['AdminPackageOptions.index.page_title'] = "Opções de pacote";
$lang['AdminPackageOptions.index.boxtitle_options'] = "Opções configuráveis";
$lang['AdminPackageOptions.index.category_groups'] = "Grupos";
$lang['AdminPackageOptions.index.category_options'] = "Opções";
$lang['AdminPackageOptions.index.categorylink_createoption'] = "Criar Opção";
$lang['AdminPackageOptions.index.categorylink_creategroup'] = "Criar Grupo";
$lang['AdminPackageOptions.index.heading_name'] = "Nome";
$lang['AdminPackageOptions.index.heading_options'] = "Opções";
$lang['AdminPackageOptions.index.option_edit'] = "Editar";
$lang['AdminPackageOptions.index.option_delete'] = "Apagar";
$lang['AdminPackageOptions.index.confirm_delete_group'] = "Tem a certeza que pretende apagar este grupo de opções de pacotes?";
$lang['AdminPackageOptions.index.confirm_delete_option'] = "Tem a certeza de que deseja apagar esta opção de pacotes?";
$lang['AdminPackageOptions.groupinfo.heading_options'] = "Opções";
$lang['AdminPackageOptions.groupinfo.option_edit'] = "Editar";
$lang['AdminPackageOptions.optioninfo.heading_name'] = "Nome";
$lang['AdminPackageOptions.optioninfo.heading_value'] = "Valor";
$lang['AdminPackageOptions.optioninfo.heading_min'] = "Min";
$lang['AdminPackageOptions.optioninfo.heading_max'] = "Máx";
$lang['AdminPackageOptions.optioninfo.heading_step'] = "Passo";
$lang['AdminPackageOptions.optioninfo.no_results'] = "Não existem valores atribuídos a esta opção.";
$lang['AdminPackageOptions.add.heading_basic'] = "Básico";
$lang['AdminPackageOptions.add.field_label'] = "Rótulo";
$lang['AdminPackageOptions.add.field_type'] = "Tipo";
$lang['AdminPackageOptions.add.heading_options'] = "Opções";
$lang['AdminPackageOptions.add.categorylink_addoption'] = "Adicionar Opção Adicional";
$lang['AdminPackageOptions.add.text_name'] = "Nome";
$lang['AdminPackageOptions.add.text_value'] = "Valor";
$lang['AdminPackageOptions.add.text_min'] = "Min";
$lang['AdminPackageOptions.add.text_step'] = "Passo";
$lang['AdminPackageOptions.add.text_options'] = "Opções";
$lang['AdminPackageOptions.add.text_delete'] = "Apagar";
$lang['AdminPackageOptions.add.heading_prices'] = "Preçário";
$lang['AdminPackageOptions.add.price_term'] = "Termo";
$lang['AdminPackageOptions.add.price_period'] = "Período";
$lang['AdminPackageOptions.add.price_currency'] = "Moeda";
$lang['AdminPackageOptions.add.price_setup'] = "Taxa de Instalação";
$lang['AdminPackageOptions.add.price_options'] = "Opções";
$lang['AdminPackageOptions.add.price_add'] = "Adicionar";
$lang['AdminPackageOptions.add.price_delete'] = "Eliminar";
$lang['AdminPackageOptions.add.text_membergroups'] = "Grupos de Membros";
$lang['AdminPackageOptions.add.text_availablegroups'] = "Grupos Disponíveis";
$lang['AdminPackageOptions.add.field_submit'] = "Criar Opção de Pacote";
$lang['AdminPackageOptions.edit.boxtitle_editoption'] = "Atualizar Opção de Pacote";
$lang['AdminPackageOptions.edit.heading_basic'] = "Básico";
$lang['AdminPackageOptions.edit.field_label'] = "Rótulo";
$lang['AdminPackageOptions.edit.field_name'] = "Nome";
$lang['AdminPackageOptions.edit.field_type'] = "Tipo";
$lang['AdminPackageOptions.edit.heading_options'] = "Opções";
$lang['AdminPackageOptions.edit.categorylink_editoption'] = "Adicionar Opção Adicional";
$lang['AdminPackageOptions.edit.text_name'] = "Nome";
$lang['AdminPackageOptions.edit.text_value'] = "Valor";
$lang['AdminPackageOptions.edit.text_min'] = "Min";
$lang['AdminPackageOptions.edit.text_max'] = "Máx";
$lang['AdminPackageOptions.edit.text_step'] = "Passo";
$lang['AdminPackageOptions.edit.text_options'] = "Opções";
$lang['AdminPackageOptions.edit.text_delete'] = "Apagar";
$lang['AdminPackageOptions.edit.price_term'] = "Termo";
$lang['AdminPackageOptions.edit.price_period'] = "Período";
$lang['AdminPackageOptions.edit.price_currency'] = "Moeda";
$lang['AdminPackageOptions.edit.price_price'] = "Preço";
$lang['AdminPackageOptions.edit.price_setup'] = "Taxa de Instalação";
$lang['AdminPackageOptions.edit.price_options'] = "Opções";
$lang['AdminPackageOptions.edit.price_add'] = "Adicionar";
$lang['AdminPackageOptions.edit.price_delete'] = "Apagar";
$lang['AdminPackageOptions.edit.heading_groups'] = "Associação de grupo";
$lang['AdminPackageOptions.edit.text_membergroups'] = "Grupos de Membros";
$lang['AdminPackageOptions.edit.text_availablegroups'] = "Grupos disponíveis";
$lang['AdminPackageOptions.addgroup.heading_basic'] = "Básico";
$lang['AdminPackageOptions.addgroup.field_name'] = "Nome";
$lang['AdminPackageOptions.addgroup.field_description'] = "Descrição";
$lang['AdminPackageOptions.addgroup.text_availablepackages'] = "Pacotes Disponíveis";
$lang['AdminPackageOptions.addgroup.field_addgroupsubmit'] = "Criar Grupo";
$lang['AdminPackageOptions.editgroup.heading_basic'] = "Básico";
$lang['AdminPackageOptions.editgroup.field_name'] = "Nome";
$lang['AdminPackageOptions.editgroup.text_availablepackages'] = "Pacotes Disponíveis";
$lang['AdminPackageOptions.editgroup.field_editgroupsubmit'] = "Atualizar Grupo";
$lang['AdminPackageOptions.add.field_addable'] = "O Cliente pode Adicionar";
$lang['AdminPackageOptions.add.field_editable'] = "O Cliente pode Editar";
$lang['AdminPackageOptions.edit.field_editable'] = "O Cliente pode Editar";
?>