<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSystemStaff.!success.staff_added'] = "O membro da equipa foi adicionado com sucesso!";
$lang['AdminSystemStaff.manage.boxtitle_manage'] = "Gerir Equipa";
$lang['AdminSystemStaff.manage.category_active'] = "Activo";
$lang['AdminSystemStaff.manage.category_inactive'] = "Inattivo";
$lang['AdminSystemStaff.manage.heading_name'] = "Nome";
$lang['AdminSystemStaff.manage.heading_email'] = "Email";
$lang['AdminSystemStaff.manage.option_edit'] = "Editar";
$lang['AdminSystemStaff.manage.option_deactivate'] = "Desactivar";
$lang['AdminSystemStaff.manage.option_reactivate'] = "Reativar";
$lang['AdminSystemStaff.groups.option_delete'] = "Apagar";
$lang['AdminSystemStaff.add.heading_contact'] = "Informações de Contacto";
$lang['AdminSystemStaff.add.heading_authentication'] = "Autenticação";
$lang['AdminSystemStaff.add.heading_groups'] = "Grupos";
$lang['AdminSystemStaff.add.field_firstname'] = "Primeiro Nome";
$lang['AdminSystemStaff.add.field_lastname'] = "Último Nome";
$lang['AdminSystemStaff.add.field_email'] = "Email";
$lang['AdminSystemStaff.add.field_username'] = "Nome de utilizador";
$lang['AdminSystemStaff.add.field_username_username'] = "Introduza um nome de utilizador";
$lang['AdminSystemStaff.add.field_username_email'] = "Usar o endereço email como nome de utilizador";
$lang['AdminSystemStaff.add.field_password'] = "Password";
$lang['AdminSystemStaff.add.field_confirmpass'] = "Confirmar Password";
$lang['AdminSystemStaff.add.field_twofactormode'] = "Autenticação de Dois Fatores";
$lang['AdminSystemStaff.add.text_availablegroups'] = "Grupos Disponíveis";
$lang['AdminSystemStaff.edit.boxtitle_editstaff'] = "Editar Equipa";
$lang['AdminSystemStaff.edit.heading_contact'] = "Informações de Contacto";
$lang['AdminSystemStaff.edit.heading_authentication'] = "Autenticação";
$lang['AdminSystemStaff.edit.heading_groups'] = "Grupos";
$lang['AdminSystemStaff.edit.field_firstname'] = "Primeiro Nome";
$lang['AdminSystemStaff.edit.field_lastname'] = "Último Nome";
$lang['AdminSystemStaff.edit.field_username'] = "Nome de utilizador";
$lang['AdminSystemStaff.edit.field_email'] = "Email";
$lang['AdminSystemStaff.edit.field_password'] = "Nova Palavra-passe";
$lang['AdminSystemStaff.edit.field_confirmpass'] = "Confirmar Palavra-passe";
$lang['AdminSystemStaff.edit.field_twofactormode'] = "Autenticação de Dois Fatores";
$lang['AdminSystemStaff.edit.text_availablegroups'] = "Grupos Disponíveis";
$lang['AdminSystemStaff.groups.boxtitle_groups'] = "Grupos de Staff";
$lang['AdminSystemStaff.groups.categorylink_addgroup'] = "Criar Grupo";
$lang['AdminSystemStaff.groups.heading_name'] = "Nome";
$lang['AdminSystemStaff.groups.heading_company_name'] = "Nome da empresa";
$lang['AdminSystemStaff.groups.heading_staff'] = "Número de funcionários";
$lang['AdminSystemStaff.groups.heading_options'] = "Opções";
$lang['AdminSystemStaff.groups.no_results'] = "Não existem Grupos de Equipa.";
$lang['AdminSystemStaff.groups.option_edit'] = "Editar";
$lang['AdminSystemStaff.groups.modal_delete'] = "Tem certeza que deseja excluir este grupo de funcionários?";
$lang['AdminSystemStaff.addgroup.boxtitle_addgroup'] = "Criar Grupo";
$lang['AdminSystemStaff.addgroup.field_name'] = "Nome";
$lang['AdminSystemStaff.addgroup.field_company'] = "Empresa";
$lang['AdminSystemStaff.addgroup.field_groupsubmit'] = "Criar Grupo";
$lang['AdminSystemStaff.addgroup.heading_general'] = "Geral";
$lang['AdminSystemStaff.editgroup.boxtitle_editgroup'] = "Editar Grupo";
$lang['AdminSystemStaff.editgroup.field_name'] = "Nome";
$lang['AdminSystemStaff.editgroup.field_groupsubmit'] = "Editar Grupo";
$lang['AdminSystemStaff.editgroup.heading_permissions'] = "Lista de Controlo de Acesso";
$lang['AdminSystemStaff.groups.page_title'] = "Definições > Sistema > Staff > Grupos de Staff";
$lang['AdminSystemStaff.!groups.text_separator'] = "/";
$lang['AdminSystemStaff.!groups.text_group_start'] = "(";
$lang['AdminSystemStaff.!groups.text_group_end'] = ")";
$lang['AdminSystemStaff.addgroup.heading_email_notices'] = "Avisos Email BBC";
$lang['AdminSystemStaff.editgroup.page_title'] = "Definições > Sistema > Equipa > Editar Grupo";
$lang['AdminSystemStaff.editgroup.heading_email_notices'] = "Avisos BCC de correio";
$lang['AdminSystemStaff.add.field_addsubmit'] = "Criar Equipa";
$lang['AdminSystemStaff.edit.field_editsubmit'] = "Editar Equipa";
?>