<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminPackages.index.boxtitle_packages'] = "Pacotes";
$lang['AdminPackages.index.categorylink_createpackage'] = "Criar Pacote";
$lang['AdminPackages.index.heading_name'] = "Nome";
$lang['AdminPackages.index.heading_module'] = "Módulo";
$lang['AdminPackages.index.heading_options'] = "Opções";
$lang['AdminPackages.index.category_inactive'] = "Inativo";
$lang['AdminPackages.index.option_edit'] = "Editar";
$lang['AdminPackages.index.no_results'] = "Não existem pacotes com esse estado.";
$lang['AdminPackages.add.boxtitle_newpackage'] = "Novo Pacote";
$lang['AdminPackages.add.heading_basic'] = "Básico";
$lang['AdminPackages.add.heading_module'] = "Opções do Módulo";
$lang['AdminPackages.add.heading_email'] = "Email de Boas-Vindas";
$lang['AdminPackages.add.field_module'] = "Módulo";
$lang['AdminPackages.add.field_status'] = "Estado";
$lang['AdminPackages.add.field_activation'] = "Ativação Instantânea";
$lang['AdminPackages.add.field_description'] = "Descrição";
$lang['AdminPackages.add.field_description_text'] = "Texto";
$lang['AdminPackages.add.field_description_html'] = "HTML";
$lang['AdminPackages.add.field_modulegroup_any'] = "Qualquer";
$lang['AdminPackages.add.text_term'] = "Termo";
$lang['AdminPackages.add.text_period'] = "Período";
$lang['AdminPackages.add.text_currency'] = "Moeda";
$lang['AdminPackages.add.text_price'] = "Preço";
$lang['AdminPackages.add.text_setup'] = "Setup Grátis";
$lang['AdminPackages.add.text_cancellation'] = "Taxa de cancelamento";
$lang['AdminPackages.add.text_options'] = "Opções";
$lang['AdminPackages.add.text_remove'] = "Remover";
$lang['AdminPackages.add.text_tags'] = "Tags:";
$lang['AdminPackages.add.text_availablegroups'] = "Grupos disponíveis";
$lang['AdminPackages.add.field_email'] = "Email de boas vindas";
$lang['AdminPackages.add.field_packagesubmit'] = "Criar Pacote";
$lang['AdminPackages.add.categorylink_addprice'] = "Adicionar Preço Adicional";
$lang['AdminPackages.edit.field_module'] = "Módulo";
$lang['AdminPackages.edit.field_status'] = "Estado";
$lang['AdminPackages.edit.field_description'] = "Descrição";
$lang['AdminPackages.edit.field_setupfee'] = "Taxa de Instalação";
$lang['AdminPackages.edit.field_cancelfee'] = "Taxa de Cancelamento";
$lang['AdminPackages.edit.field_email'] = "Email de boas-vindas";
$lang['AdminPackages.edit.field_packagesubmit'] = "Atualizar Pacote";
$lang['AdminPackages.groups.categorylink_creategroup'] = "Criar Grupo";
$lang['AdminPackages.addgroup.boxtitle_addgroup'] = "Novo Grupo de Pacote";
$lang['AdminPackages.addgroup.field_name'] = "Nome";
$lang['AdminPackages.addgroup.field_type'] = "Tipo";
$lang['AdminPackages.addgroup.text_availablegroups'] = "Grupos Disponíveis";
$lang['AdminPackages.addgroup.field_addgroupsubmit'] = "Criar Grupo";
$lang['AdminPackages.!success.package_updated'] = "O pacote foi atualizado com sucesso.";
$lang['AdminPackages.!success.package_deleted'] = "O pacote foi apagado com sucesso.";
$lang['AdminPackages.index.page_title'] = "Pacotes";
$lang['AdminPackages.index.heading_qty'] = "Quantidade";
$lang['AdminPackages.index.option_delete'] = "Apagar";
$lang['AdminPackages.index.qty_unlimited'] = "Ilimitado";
$lang['AdminPackages.index.confirm_delete'] = "Tem a certeza de que deseja apagar este pacote?";
$lang['AdminPackages.packagepricing.heading_term'] = "Termo";
$lang['AdminPackages.packagepricing.heading_price'] = "Preço";
$lang['AdminPackages.packagepricing.heading_cancellation_fee'] = "Taxa de Cancelamento";
$lang['AdminPackages.packagepricing.pricing_no_results'] = "Este pacote não tem detalhes de preçário.";
$lang['AdminPackages.add.page_title'] = "Novo pacote";
$lang['AdminPackages.add.field_qty'] = "Quantidade disponível";
$lang['AdminPackages.add.field_qty_unlimited'] = "Ilimitado";
$lang['AdminPackages.add.field_taxable'] = "Taxável";
$lang['AdminPackages.add.field_select_group_type_new'] = "Criar um Novo Grupo";
$lang['AdminPackages.edit.page_title'] = "Atualizar Pacote";
$lang['AdminPackages.edit.boxtitle_updatepackage'] = "Actualizar pacote";
$lang['AdminPackages.edit.heading_basic'] = "Básico";
$lang['AdminPackages.edit.heading_module'] = "Opções do Módulo";
$lang['AdminPackages.edit.field_qty'] = "Quantidade Disponível";
$lang['AdminPackages.edit.field_qty_unlimited'] = "Ilimitado";
$lang['AdminPackages.edit.field_description_text'] = "Texto";
$lang['AdminPackages.edit.field_description_html'] = "HTML";
$lang['AdminPackages.edit.field_modulegroup_any'] = "Qualquer";
$lang['AdminPackages.edit.text_term'] = "Termo";
$lang['AdminPackages.edit.text_period'] = "Período";
$lang['AdminPackages.edit.text_currency'] = "Moeda";
$lang['AdminPackages.edit.text_price'] = "Preço";
$lang['AdminPackages.edit.text_setup'] = "Taxa de Instalação";
$lang['AdminPackages.edit.text_cancellation'] = "Taxa de cancelamento";
$lang['AdminPackages.edit.text_options'] = "Opções";
$lang['AdminPackages.edit.text_remove'] = "Remover";
$lang['AdminPackages.edit.text_tags'] = "Tags:";
$lang['AdminPackages.edit.text_group'] = "Um pacote deve pertencer a pelo menos um grupo para ser utilizável.";
$lang['AdminPackages.edit.text_availablegroups'] = "Grupos Disponíveis";
$lang['AdminPackages.edit.categorylink_addprice'] = "Adicionar Preço Adicional";
$lang['AdminPackages.groups.page_title'] = "Grupos de Pacotes";
$lang['AdminPackages.groups.boxtitle_packagegroups'] = "Grupos de Pacotes";
$lang['AdminPackages.addgroup.page_title'] = "Novo Grupo de Pacotes";
$lang['AdminPackages.editgroup.field_name'] = "Nome";
$lang['AdminPackages.editgroup.field_type'] = "Tipo";
$lang['AdminPackages.editgroup.text_availablegroups'] = "Grupos disponíveis";
$lang['AdminPackages.editgroup.field_editgroupsubmit'] = "Atualizar Grupo";
$lang['AdminPackages.!success.group_added'] = "O grupo de pacotes \"%1\$s\" foi criado com sucesso."; // %1$s is the package group name
$lang['AdminPackages.index.heading_package'] = "ID do Pacote";
$lang['AdminPackages.packagepricing.heading_pricing'] = "Preços";
$lang['AdminPackages.groups.heading_name'] = "Nome";
$lang['AdminPackages.groups.heading_type'] = "Tipo";
$lang['AdminPackages.groups.heading_options'] = "Opções";
$lang['AdminPackages.groups.option_edit'] = "Editar";
$lang['AdminPackages.groups.heading_parent_groups'] = "Grupos Pais";
$lang['AdminPackages.!success.group_deleted'] = "O grupo de pacotes \"%1\$s\" foi apagado com sucesso."; // %1$s is the package group name
$lang['AdminPackages.groups.confirm_delete'] = "Tem a certeza de que quer apagar este grupo de pacotes? Todos os pacotes atribuídos a este grupo irão deixar de o ser e poderão ficar inutilizáveis.";
$lang['AdminPackages.add.field_single_term'] = "Cancelar no fim do termo";
$lang['AdminPackages.edit.field_configurable_options'] = "Opções configuráveis";
$lang['AdminPackages.index.option_copy'] = "Copiar";
$lang['AdminPackages.add.text_none'] = "Nenhum";
$lang['AdminPackages.edit.field_prorata'] = "Ativar Pró rata";
$lang['AdminPackages.edit.text_none'] = "Nenhum";
$lang['AdminPackages.addgroup.field_description'] = "Descrição";
$lang['AdminPackages.editgroup.field_description'] = "Descrição";
$lang['AdminPackages.moduleoptions.not_applicable'] = "Grupo";
?>