<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyAutomation.!success.automation_updated'] = "As definições de Automação foram atualizadas com sucesso!";
$lang['AdminCompanyAutomation.index.boxtitle_automation'] = "Automação";
$lang['AdminCompanyAutomation.index.heading_automation'] = "Configurar Automação";
$lang['AdminCompanyAutomation.index.field_automationsubmit'] = "Actualizar definições";
$lang['AdminCompanyAutomation.index.field_enabled'] = "Ativo";
$lang['AdminCompanyAutomation.index.text_interval'] = "Intervalo";
$lang['AdminCompanyAutomation.index.text_starttime'] = "Hora de Início";
$lang['AdminCompanyAutomation.index.text_task_lastran'] = "Última Execução:";
$lang['AdminCompanyAutomation.index.no_results'] = "Não existem tarefas cron.";
$lang['AdminCompanyAutomation.index.no_cron_lastran'] = "Nunca";
$lang['AdminCompanyAutomation.index.text_cron_last_ran'] = "O cron foi executado pelo última vez a %1\$s."; // %1$s is the date that the cron last ran
$lang['AdminCompanyAutomation.index.text_cron_never_ran'] = "O cron nunca foi executado.";
$lang['AdminCompanyAutomation.getintervals.text_minutes'] = "minutos";
$lang['AdminCompanyAutomation.getintervals.text_hour'] = "hora";
$lang['AdminCompanyAutomation.getintervals.text_hours'] = "horas";
$lang['AdminCompanyAutomation.index.page_title'] = "Configurações > Empresa > Automatização";
$lang['AdminCompanyAutomation.!success.task_cleared'] = "A tarefa cron foi limpa.";
$lang['AdminCompanyAutomation.index.option_clear_task'] = "Limpar Bloqueio de Tarefas";
$lang['AdminCompanyAutomation.index.confirm_clear_task'] = "Tem a certeza de que deseja limpar este bloqueio da tarefa cron? Se esta tarefa parar continuamente, pode haver um problema mais sério. Tente correr o cron manualmente, ou verificar o registo do crom por erros para determinar a causa.";
?>