<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminMain.index.heading_quicklinks'] = "Links rápidos";
$lang['AdminMain.index.manage_widgets'] = "Gerir Widgets";
$lang['AdminMain.managewidgets.text_version'] = "versão %1\$s"; // %1$s is the version number of the plugin
$lang['AdminMain.managewidgets.text_author'] = "Autor:";
$lang['AdminMain.!success.event_added'] = "O evento foi adicionado com sucesso!";
$lang['AdminMain.!success.event_edited'] = "O evento foi actualizado com sucesso!";
$lang['AdminMain.!success.event_deleted'] = "O evento foi apagado com sucesso!";
$lang['AdminMain.index.page_title'] = "Painel";
$lang['AdminMain.calendar.page_title'] = "Calendário";
$lang['AdminMain.calendar.boxtitle_calendar'] = "Calendário";
$lang['AdminMain.calendar.categorylink_addevent'] = "Criar Evento";
$lang['AdminMain.calendar.category_month'] = "Mês";
$lang['AdminMain.calendar.category_week'] = "Semana";
$lang['AdminMain.calendar.category_day'] = "Dia";
$lang['AdminMain.getEvents.shared_event_title'] = "%2\$s %3\$s: %1\$s"; // %1$s is the event title, %2$s is the staff's first name, %3$s is the staff's last name
$lang['AdminMain.addevent.boxtitle_addevent'] = "Criar Evento";
$lang['AdminMain.addevent.field_title'] = "Título";
$lang['AdminMain.addevent.field_start_date'] = "Data de Início";
$lang['AdminMain.addevent.field_end_date'] = "Data de Fim";
$lang['AdminMain.addevent.field_all_day'] = "Todo o Dia";
$lang['AdminMain.addevent.field_addeventsubmit'] = "Criar Evento";
$lang['AdminMain.editevent.boxtitle_editevent'] = "Editar evento";
$lang['AdminMain.editevent.field_title'] = "Título";
$lang['AdminMain.editevent.field_end_date'] = "Data de Fim";
$lang['AdminMain.editevent.field_all_day'] = "Todo o dia";
$lang['AdminMain.editevent.field_editeventsubmit'] = "Atualizar Evento";
$lang['AdminMain.editevent.field_deleteeventsubmit'] = "Apagar Evento";
$lang['AdminMain.editevent.confirm_delete'] = "Apagar este evento?";
?>