<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminReports.index.page_title'] = "Relatórios de Faturação";
$lang['AdminReports.index.box_title'] = "Relatórios";
$lang['AdminReports.index.field_format'] = "Formato";
$lang['AdminReports.index.field_report_type'] = "Tipo de Relatório";
$lang['AdminReports.index.field_submit'] = "Exportar";
$lang['AdminReports.index.reports'] = "Gerar";
?>