<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminCompanyModules.!success.upgraded'] = "O módulo foi actualizado com sucesso.";
$lang['AdminCompanyModules.!success.installed'] = "O módulo foi instalado com sucesso.";
$lang['AdminCompanyModules.!success.uninstalled'] = "O módulo foi desinstalado com sucesso.";
$lang['AdminCompanyModules.!success.module_updated'] = "O módulo foi atualizado com sucesso.";
$lang['AdminCompanyModules.!success.group_added'] = "O grupo foi adicionado com sucesso.";
$lang['AdminCompanyModules.!success.group_updated'] = "O grupo foi atualizado com sucesso.";
$lang['AdminCompanyModules.!success.group_deleted'] = "O grupo foi apagado com sucesso.";
$lang['AdminCompanyModules.!success.row_added'] = "O %1\$s foi adicionado com sucesso."; // %1$s is the module row noun (e.g. Server)
$lang['AdminCompanyModules.!success.row_updated'] = "O %1\$s foi actualizado com sucesso."; // %1$s is the module row noun (e.g. Server)
$lang['AdminCompanyModules.!success.row_deleted'] = "O %1\$s foi apagado com sucesso."; // %1$s is the module row noun (e.g. Server)
$lang['AdminCompanyModules.available.text_author'] = "Autor:";
$lang['AdminCompanyModules.available.text_author_url'] = "URL do Autor";
$lang['AdminCompanyModules.available.text_none'] = "Não existem módulos disponíveis.";
$lang['AdminCompanyModules.available.btn_install'] = "Instalar";
$lang['AdminCompanyModules.installed.text_author'] = "Autor:";
$lang['AdminCompanyModules.installed.text_author_url'] = "URL do autor";
$lang['AdminCompanyModules.installed.text_none'] = "Não existem módulos instalados.";
$lang['AdminCompanyModules.installed.btn_uninstall'] = "Desinstalar";
$lang['AdminCompanyModules.installed.btn_manage'] = "Gerir";
$lang['AdminCompanyModules.installed.confirm_uninstall'] = "Tem a certeza de que quer desinstalar este módulo?";
$lang['AdminCompanyModules.manage.boxtitle_manage'] = "Gerir %1\$s"; // %1$s is the name of the module
$lang['AdminCompanyModules.addgroup.btn_add'] = "Adicionar grupo";
$lang['AdminCompanyModules.addgroup.available'] = "%1\$s disponíveis"; // %1$s is the module row noun in plural form (e.g. Servers)
$lang['AdminCompanyModules.editgroup.btn_edit'] = "Actualizar Grupo";
$lang['AdminCompanyModules.editgroup.available'] = "%1\$s disponíveis"; // %1$s is the module row noun in plural form (e.g. Servers)
$lang['AdminCompanyModules.editgroup.text_order'] = "Adicionar Compra";
$lang['AdminCompanyModules.installed.page_title'] = "Configurações > Empresa > Módulos > Instalado";
$lang['AdminCompanyModules.manage.page_title'] = "Definições > Empresa > Módulos > Gerir %1\$s"; // %1$s is the name of the module
$lang['AdminCompanyModules.available.text_version'] = "(ver %1\$s)"; // %1$s is the module's version number
$lang['AdminCompanyModules.installed.text_version'] = "(ver %1\$s)"; // %1$s is the module's version number
$lang['AdminCompanyModules.!tab.installed'] = "Instalado";
$lang['AdminCompanyModules.!tab.available'] = "Disponível";
$lang['AdminCompanyModules.available.boxtitle_module'] = "Módulos";
$lang['AdminCompanyModules.installed.boxtitle_installed'] = "Módulos";
?>