<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSystemHelp.index.heading_forums'] = "Fórum";
$lang['AdminSystemHelp.index.page_title'] = "Definições > Sistema > Ajuda > Recursos";
?>