<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSystemMarketplace.index.boxtitle_marketplace'] = "Mercado";
$lang['AdminSystemMarketplace.index.text_unavailable'] = "O Mercado está indisponível de momento.";
$lang['AdminSystemMarketplace.index.page_title'] = "Definições > Sistema > Mercado";
$lang['AdminSystem.marketplace.category_all'] = "Todos";
$lang['AdminSystemMarketplace.listing.boxtitle_listing'] = "Extensão %1\$s"; // %1$s is the name of the extension
?>