<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AdminSystemApi.!notice.api_not_restrictive'] = "ATENÇÃO! Empresa é a empresa com quem o utilizador autentica quando se liga. O acesso a dados de outra empresa não é restrito pelas solicitações de API que oferecem suporte a esse acesso.";
$lang['AdminSystemApi.!success.key_added'] = "O utilizador do API foi adicionado com sucesso.";
$lang['AdminSystemApi.!success.key_deleted'] = "O utilizador da API foi apagado com sucesso.";
$lang['AdminSystemApi.!success.key_updated'] = "O utilizador do API foi actualizado com sucesso.";
$lang['AdminSystemApi.index.heading_user'] = "Utilizador";
$lang['AdminSystemApi.index.heading_key'] = "Chave";
$lang['AdminSystemApi.index.heading_company'] = "Empresa";
$lang['AdminSystemApi.index.heading_options'] = "Opções";
$lang['AdminSystemApi.index.option_delete'] = "Excluir";
$lang['AdminSystemApi.index.no_results'] = "Não existem utilizadores de API.";
$lang['AdminSystemApi.add.field_company'] = "Empresa";
$lang['AdminSystemApi.add.field_user'] = "Utilizador";
$lang['AdminSystemApi.add.field_notes'] = "Notas";
$lang['AdminSystemApi.add.field_apisubmit'] = "Adicionar Utilizador";
$lang['AdminSystemApi.edit.boxtitle_edit'] = "Editar Utilizador da API";
$lang['AdminSystemApi.edit.field_company'] = "Empresa";
$lang['AdminSystemApi.edit.field_user'] = "Utilizador";
$lang['AdminSystemApi.edit.field_notes'] = "Notas";
$lang['AdminSystemApi.edit.field_apisubmit'] = "Actualizar utilizador";
$lang['AdminSystemApi.index.page_title'] = "Definições > Sistema > Acesso API";
?>