<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['AppController.lang.dir'] = "ltr";
$lang['AppController.!error.unauthorized_access'] = "Não está autorizado a aceder a esse recurso";
$lang['AppController.modal.text_close'] = "Fechar";
$lang['AppController.tooltip.text'] = "?";
$lang['AppController.structure.text_myinfo'] = "Minha Informação";
$lang['AppController.message.close'] = "×";
$lang['AppController.structure.text_maintenance'] = "O Modo de manutenção está ativo e os clientes não podem aceder. Clique aqui para alterar.";
$lang['AppController.structure.text_search_placeholder'] = "%1\$s..."; // %1$s is the search type
$lang['AppController.client_structure.default_title'] = "Minha Conta";
$lang['AppController.client_structure.text_return_to_portal'] = "Voltar ao Portal";
$lang['AppController.client_structure.text_logout'] = "Sair";
$lang['AppController.dates.day_sun'] = "Domingo";
$lang['AppController.dates.day_mon'] = "Segunda-feira";
$lang['AppController.dates.day_tue'] = "Terça-feira";
$lang['AppController.dates.day_wed'] = "Quarta-feira";
$lang['AppController.dates.day_fri'] = "Sexta-feira";
$lang['AppController.dates.day_sat'] = "Sábado";
$lang['AppController.dates.dayabbr_sun'] = "Dom";
$lang['AppController.dates.dayabbr_mon'] = "Seg";
$lang['AppController.dates.dayabbr_wed'] = "Qua";
$lang['AppController.dates.dayabbr_thur'] = "Quinta-feira";
$lang['AppController.dates.dayabbr_fri'] = "Sex";
$lang['AppController.dates.dayabbr_sat'] = "Sab";
$lang['AppController.dates.month_jan'] = "Janeiro";
$lang['AppController.dates.month_feb'] = "Fevereiro";
$lang['AppController.dates.month_mar'] = "Março";
$lang['AppController.dates.month_apr'] = "Abril";
$lang['AppController.dates.month_jun'] = "Junho";
$lang['AppController.dates.month_jul'] = "Julho";
$lang['AppController.dates.month_aug'] = "Agosto";
$lang['AppController.dates.month_sep'] = "Setembro";
$lang['AppController.dates.month_oct'] = "Outubro";
$lang['AppController.dates.month_nov'] = "Novembro";
$lang['AppController.dates.month_dec'] = "Dezembro";
$lang['AppController.dates.monthabbr_jan'] = "Jan";
$lang['AppController.dates.monthabbr_feb'] = "Fev";
$lang['AppController.dates.monthabbr_mar'] = "Mar";
$lang['AppController.dates.monthabbr_apr'] = "Abr";
$lang['AppController.dates.monthabbr_may'] = "Maio";
$lang['AppController.dates.monthabbr_jun'] = "Jun";
$lang['AppController.dates.monthabbr_jul'] = "Jul";
$lang['AppController.dates.monthabbr_oct'] = "Out";
$lang['AppController.dates.monthabbr_nov'] = "Nov";
$lang['AppController.dates.monthabbr_dec'] = "Dez";
$lang['AppController.modal.text_confirm'] = "Por favor confirme";
$lang['AppController.client_structure.staff_as_client_note'] = "Voltar para o Portal do Staff";
$lang['AppController.tooltip.markdown_supported'] = "Este campo oferece suporte à sintaxe do Markdown.";
$lang['AppController.graphs.label.total'] = "Total";
?>