<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Backup.!error.driver.support'] = "O driver da base de dados não é suportado.";
$lang['Backup.frequencies.hour'] = "Hora";
$lang['Backup.frequencies.day'] = "Dia";
$lang['Backup.frequencies.days'] = "%1\$s Dias"; // %1$s is the number of days
$lang['Backup.frequencies.never'] = "Nunca";
$lang['Backup.!error.ftp_failed'] = "O backup SFTP falhou.";
?>