<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['CalendarEvents.!error.company_id.exists'] = "ID de empresa inválido.";
$lang['CalendarEvents.!error.staff_id.exists'] = "ID de Equipa inválido.";
$lang['CalendarEvents.!error.title.empty'] = "Por favor introduza um título.";
$lang['CalendarEvents.!error.start_date.format'] = "A data de início é em um formato de data inválido.";
$lang['CalendarEvents.!error.start_date.order'] = "A data de início tem de ser antes da data do fim.";
?>