<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Clients.!error.client_id.exists'] = "ID de cliente inválido.";
$lang['Clients.!error.account_id.exists'] = "ID da conta inválido.";
$lang['Clients.!error.type.exists'] = "Tipo inválido.";
$lang['Clients.!error.user_id.exists'] = "ID de utilizador inválido.";
$lang['Clients.!error.name.empty'] = "Por favor introduza um nome.";
$lang['Clients.!error.is_lang.format'] = "is_lang tem de ser um número.";
$lang['Clients.!error.title.empty'] = "Por favor introduza um título.";
$lang['Clients.getCustomFieldTypes.textbox'] = "Caixa de Texto";
$lang['Clients.getCustomFieldTypes.textarea'] = "Área de texto";
$lang['Clients.getStatusTypes.active'] = "Ativo";
$lang['Clients.getStatusTypes.inactive'] = "Inativo";
$lang['Clients.getStatusTypes.fraud'] = "Fraude";
$lang['Clients.customfield.cf2'] = "Campo Personalizado";
$lang['Clients.!error.inv_address_to.exists'] = "Por favor especifique um contacto válido para endereçar as faturas.";
$lang['Clients.!error.default_currency.valid'] = "Moeda inválida.";
$lang['Clients.!error.default_currency.editable'] = "A moeda pode não ter sido actualizada.";
$lang['Clients.!error.inv_method.valid'] = "Método de entrega da fatura inválido.";
$lang['Clients.!error.language.valid'] = "Idioma inválido.";
$lang['Clients.!error.language.editable'] = "A linguagem pode não estar actualizada.";
$lang['Clients.!error.values.format'] = "Os valores estão num formato inválido.";
$lang['Clients.!error.client_field_id.matches'] = "O campo personalizado é inválido.";
$lang['Clients.!error.regex.valid'] = "A expressão regular é inválida.";
$lang['Clients.!error.read_only.format'] = "O campo de só leitura deve ser numérico.";
?>