<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientGroups.!error.name.empty'] = "Por favor, especifique um nome de grupo.";
$lang['ClientGroups.!error.company_id.exists'] = "ID de Empresa inválido.";
$lang['ClientGroups.!error.color.length'] = "O tamanho da Cor não pode exceder os 16 caracteres.";
$lang['ClientGroups.!error.group_id.exists'] = "ID do grupo de clientes inválido.";
?>