<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientLogin.index.field_username'] = "Nome de utilizador";
$lang['ClientLogin.index.field_password'] = "Password";
$lang['ClientLogin.index.field_rememberme'] = "Lembrar-me neste computador";
$lang['ClientLogin.index.link_resetpassword'] = "Reiniciar a Minha Password";
$lang['ClientLogin.reset.page_title'] = "Recuperar Palavra-passe";
$lang['ClientLogin.reset.reset_heading'] = "Alterar password";
$lang['ClientLogin.reset.field_username'] = "Nome de Utilizador";
$lang['ClientLogin.confirmreset.field_new_password'] = "Nova Palavra-Passe";
$lang['ClientLogin.confirmreset.field_confirm_password'] = "Confirmar Nova Palavra-passe";
$lang['ClientLogin.confirmreset.field_resetsubmit'] = "Definir Password";
$lang['ClientLogin.confirmreset.description'] = "Por favor introduza a sua nova password.";
$lang['ClientLogin.index.field_loginsubmit'] = "Entrar";
$lang['ClientLogin.otp.page_title'] = "Entrar";
?>