<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientContacts.!success.contact_deleted'] = "O contacto %1\$s %2\$s foi apagado com sucesso!"; // %1$s is the contact's first name, %2$s is the contact's last name
$lang['ClientContacts.!success.contact_updated'] = "O contacto foi atualizado com sucesso!";
$lang['ClientContacts.!success.contact_added'] = "O contacto foi criado com sucesso!";
$lang['ClientContacts.index.page_title'] = "Contactos do Cliente #%1\$s"; // %1$s is the client ID number
$lang['ClientContacts.index.create_contact'] = "Adicionar Contacto";
$lang['ClientContacts.index.boxtitle_contacts'] = "Contactos";
$lang['ClientContacts.index.heading_name'] = "Nome";
$lang['ClientContacts.index.heading_email'] = "Email";
$lang['ClientContacts.index.heading_type'] = "Tipo";
$lang['ClientContacts.index.heading_options'] = "Opções";
$lang['ClientContacts.index.option_edit'] = "Editar";
$lang['ClientContacts.index.option_delete'] = "Apagar";
$lang['ClientContacts.index.confirm_delete'] = "Tem certeza de que deseja eliminar este contato?";
$lang['ClientContacts.add.page_title'] = "Cliente #%1\$s Adicionar Contacto"; // %1$s is the client ID number
$lang['ClientContacts.add.boxtitle_create'] = "Adicionar Contacto";
$lang['ClientContacts.add.heading_settings'] = "Configurações adicionais";
$lang['ClientContacts.add.field_contact_type'] = "Tipo de Contacto";
$lang['ClientContacts.add.field_addsubmit'] = "Criar Contacto";
$lang['ClientContacts.edit.page_title'] = "Cliente #%1\$s Editar Contacto"; // %1$s is the client ID number
$lang['ClientContacts.edit.boxtitle_edit'] = "Editar Contacto";
$lang['ClientContacts.edit.heading_settings'] = "Configurações Adicionais";
$lang['ClientContacts.edit.field_editsubmit'] = "Atualizar Contacto";
$lang['ClientContacts.setcontactview.text_none'] = "Nenhum";
$lang['ClientContacts.contact_info.heading_contact'] = "Informação de Contacto";
$lang['ClientContacts.contact_info.field_first_name'] = "Nome Prórpio";
$lang['ClientContacts.contact_info.field_last_name'] = "Apelido";
$lang['ClientContacts.contact_info.field_company'] = "Empresa";
$lang['ClientContacts.contact_info.field_address1'] = "Endereço 1";
$lang['ClientContacts.contact_info.field_address2'] = "Endereço 2";
$lang['ClientContacts.contact_info.field_city'] = "Localdiade";
$lang['ClientContacts.contact_info.field_state'] = "Estado";
$lang['ClientContacts.contact_info.field_zip'] = "ZIP/Código Postal";
$lang['ClientContacts.contact_info.field_email'] = "Email";
$lang['ClientContacts.phone_numbers.field_phonetype'] = "Tipo";
$lang['ClientContacts.phone_numbers.field_phonelocation'] = "Localização";
$lang['ClientContacts.phone_numbers.field_phonenumber'] = "Número";
$lang['ClientContacts.index.no_results'] = "Não tem contactos. Para adicionar o seu primeiro contacto, clique no botão Adicionar Contacto acima.";
$lang['ClientContacts.phone_numbers.field_phoneoptions'] = "Opções";
$lang['ClientContacts.phone_numbers.categorylink_number'] = "Adicionar adicional";
$lang['ClientContacts.add.heading_contact'] = "Informações de contacto.";
$lang['ClientContacts.add.heading_authentication'] = "Autenticação";
$lang['ClientContacts.add.field_username'] = "Nome de Utilizador";
$lang['ClientContacts.add.field_new_password'] = "Nova Password";
$lang['ClientContacts.add.field_confirm_password'] = "Confirmar Palavra-passe";
$lang['ClientContacts.add.heading_permissions'] = "Permissões";
$lang['ClientContacts.edit.heading_contact'] = "Informações de Contacto";
$lang['ClientContacts.edit.heading_authentication'] = "Autenticação";
$lang['ClientContacts.edit.field_enable_login'] = "Ativar Login";
$lang['ClientContacts.edit.field_username'] = "Username";
$lang['ClientContacts.edit.field_new_password'] = "Nova Palavra-passe";
$lang['ClientContacts.edit.field_confirm_password'] = "Confirmar Palavra-passe";
$lang['ClientContacts.tooltip.client_contacts'] = "Permitir que os Contactos sejam geridos.";
$lang['ClientContacts.tooltip.client_accounts'] = "Permitir que as Contas de Pagamento sejam geridas.";
?>