<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientAccounts.!success.defaultaccount_updated'] = "A conta de pagamento padrão foi atualizada.";
$lang['ClientAccounts.!success.defaultaccount_deleted'] = "A conta de pagamento padrão foi removida.";
$lang['ClientAccounts.!success.ccaccount_deleted'] = "A conta de pagamento foi apagada com sucesso.";
$lang['ClientAccounts.!success.achaccount_deleted'] = "A conta de pagamento foi apagada com sucesso.";
$lang['ClientAccounts.!success.achaccount_updated'] = "A conta de pagamento foi actualizada com sucesso.";
$lang['ClientAccounts.!error.account_invalid'] = "O tipo de conta de pagamento fornecido está desativado ou é inválido.";
$lang['ClientAccounts.!notice.cc_disabled'] = "As Contas de Pagamento de Cartões de Crédito estão de momento desativadas e podem não ser atualizadas.";
$lang['ClientAccounts.!info.account_info'] = "As Contas de Pagamento permitem-lhe guardar informações de pagamento em arquivo e podem ser usadas para pagar facturas. Uma Conta de Pagamento que está selecionada como predefinida será usada para pagamentos automáticos.";
$lang['ClientAccounts.index.create_account'] = "Adicionar Conta de Pagamento";
$lang['ClientAccounts.index.boxtitle_accounts'] = "Contas de Pagamento";
$lang['ClientAccounts.index.heading_type'] = "Tipo";
$lang['ClientAccounts.index.heading_options'] = "Opções";
$lang['ClientAccounts.index.option_edit'] = "Editar";
$lang['ClientAccounts.index.option_delete'] = "Apagar";
$lang['ClientAccounts.index.type_cc'] = "%1\$s - %2\$s"; // %1$s is the account type (Credit Card) and %2$s is the type of account (MasterCard, Visa, etc.)
$lang['ClientAccounts.index.type_ach'] = "%1\$s - %2\$s"; // %1$s is the account type (ACH) and %2$s is the type of account (Checking or Savings)
$lang['ClientAccounts.index.confirm_delete'] = "Tem certeza de que deseja excluir esta conta de pagamento?
";
$lang['ClientAccounts.index.field_accountsubmit'] = "Definir como conta de pagamento padrão";
$lang['ClientAccounts.index.no_results'] = "Não tem contas de pagamento.";
$lang['ClientAccounts.add.page_title'] = "Cliente #%1\$s Adicionar Conta de Pagamento"; // %1$s is the client ID number
$lang['ClientAccounts.add.heading_account_type'] = "Tipo de conta";
$lang['ClientAccounts.add.field_cc_type'] = "Cartão Crédito";
$lang['ClientAccounts.add.field_ach_type'] = "ACH";
$lang['ClientAccounts.add.boxtitle_create'] = "Adicionar Conta de Pagamento";
$lang['ClientAccounts.add.field_nextsubmit'] = "Continuar";
$lang['ClientAccounts.editach.field_accountsubmit'] = "Editar Conta";
$lang['ClientAccounts.editcc.boxtitle_editcc'] = "Editar Conta de Cartão de Crédito";
$lang['ClientAccounts.editcc.field_accountsubmit'] = "Editar Conta";
$lang['ClientAccounts.setcontactview.text_none'] = "Nenhum";
$lang['ClientAccounts.cc_info.heading_cc'] = "Informação de Cartão de Crédito";
$lang['ClientAccounts.cc_info.field_number'] = "Numero";
$lang['ClientAccounts.cc_info.field_security'] = "Código de Segurança";
$lang['ClientAccounts.cc_info.field_savedetails'] = "Gravar Conta";
$lang['ClientAccounts.cc_info.tooltip_code'] = "O código de segurança de 3 ou 4 dígitos, geralmente encontram-se na parte de trás do cartão.";
$lang['ClientAccounts.ach_info.heading_ach'] = "Informações da conta bancária";
$lang['ClientAccounts.ach_info.field_accountnum'] = "Número de conta";
?>