<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientMain.!success.client_updated'] = "As informações da suas conta foram atualizadas com sucesso.";
$lang['ClientMain.!success.invoice_method_updated'] = "O seu método de faturação foi atualizado com sucesso. Todas a faturas futuras serão entregues via %1\$s."; // %1$s is the clients invoice method (e.g. Email, Paper, etc.)
$lang['ClientMain.!info.invoice_due_button'] = "Efetuar Pagamento";
$lang['ClientMain.!info.invoice_due_text'] = "A sua conta tem um balanço negativo de %1\$s. Por favor faça um pagamento assim que possível."; // %1$s is the total amount due for this client
$lang['ClientMain.!info.invoice_due_other_currencies'] = "Também possui saldo pendente noutras moedas.";
$lang['ClientMain.myinfo.setting_autodebit_enabled'] = "A sua conta está definida para pagamento automático.";
$lang['ClientMain.myinfo.setting_autodebit_cc_zero_days'] = "Iremos cobrar o seu %1\$s terminado em x%2\$s no dia do vencimento do pagamento."; // %1$s is the type of credit card (e.g. "Visa"), %2$s is the last 4 of the credit card number
$lang['ClientMain.myinfo.setting_change'] = "Alterar isto?";
$lang['ClientMain.myinfo.link_editclient'] = "Alterar";
$lang['ClientMain.edit.heading_billing'] = "Informação de Faturação";
$lang['ClientMain.edit.heading_settings'] = "Definições Adicionais";
$lang['ClientMain.edit.field_language'] = "Linguagem";
$lang['ClientMain.edit.field_username'] = "Nome de Utilizador";
$lang['ClientMain.edit.field_new_password'] = "Nova Palavra-passe";
$lang['ClientMain.edit.field_confirm_password'] = "Confirmar Palavra-passe";
$lang['ClientMain.edit.field_current_password'] = "Password Atual";
$lang['ClientMain.edit.field_editsubmit'] = "Atualizar a Minha Informação";
$lang['ClientMain.invoicemethod.boxtitle_inv_method'] = "Método de Faturação";
$lang['ClientMain.!tooltip.invoice_method_email'] = "As Faturas serão enviadas por email para o endereço que temos registado.";
$lang['ClientMain.getcurrencyamounts.text_total_credits'] = "Créditos:";
$lang['ClientMain.edit.field_two_factor_mode'] = "Ativar Autenticação de Dois Passos";
$lang['ClientMain.edit.text_android'] = "Android";
$lang['ClientMain.edit.text_ios'] = "iOS";
$lang['ClientMain.edit.text_windows'] = "Windows";
$lang['ClientMain.index.page_title'] = "Cliente #%1\$s"; // %1$s is the client ID number
$lang['ClientMain.myinfo.page_title'] = "Cliente #%1\$s"; // %1$s is the client ID number
$lang['ClientMain.invoicemethod.page_title'] = "Cliente #%1\$s Método de Faturação"; // %1$s is the client ID number
$lang['ClientMain.!info.service_name'] = "%1\$s - %2\$s"; // %1$s is the package name, %2$s is the service name
$lang['ClientMain.!info.additional_service'] = "...e 1 serviço adicional.";
?>