<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientServices.index.boxtitle_services'] = "Serviços";
$lang['ClientServices.index.category_active'] = "Ativo";
$lang['ClientServices.index.category_suspended'] = "Suspenso";
$lang['ClientServices.index.category_canceled'] = "Cancelado";
$lang['ClientServices.index.heading_package'] = "Pacote";
$lang['ClientServices.index.heading_term'] = "Termo";
$lang['ClientServices.index.heading_daterenews'] = "Data de Renovação";
$lang['ClientServices.index.heading_options'] = "Opções";
$lang['ClientServices.index.option_manage'] = "Gerir";
$lang['ClientServices.index.text_never'] = "Nunca";
$lang['ClientServices.index.no_results'] = "Não tem Serviços %1\$s."; // %1$s is the language for the services category type (e.g. Active, Pending)
$lang['ClientServices.serviceinfo.no_results'] = "Este serviço não tem detalhes.";
$lang['ClientServices.!success.manage.tab_updated'] = "Os dados foram atualizados com sucesso.";
$lang['ClientServices.index.heading_addons'] = "Add-ons";
$lang['ClientServices.index.heading_status'] = "Estado";
$lang['ClientServices.index.heading_datesuspended'] = "Data de Suspensão";
$lang['ClientServices.manage.page_title'] = "Cliente #%1\$s Gerir Serviços"; // %1$s is the client ID number
$lang['ClientServices.manage.tab_service_info'] = "Informação";
$lang['ClientServices.!success.service_canceled'] = "O serviço foi cancelado com sucesso.";
$lang['ClientServices.cancel.page_title'] = "Cliente #%1\$s Cancelar Serviço"; // %1$s is the client ID number
$lang['ClientServices.cancel.heading_cancel'] = "Cancelar Serviço";
$lang['ClientServices.cancel.field_now'] = "Imediatamente";
$lang['ClientServices.cancel.confirm_cancel_now'] = "Tem a certeza de que quer cancelar este serviço?";
$lang['ClientServices.!success.service_not_canceled'] = "O serviço não será cancelado.";
$lang['ClientServices.manage.tab_addons'] = "Addons";
$lang['ClientServices.manage.button_active'] = "Ativo";
$lang['ClientServices.manage.button_pending'] = "Pendente";
$lang['ClientServices.manage.button_suspended'] = "Suspenso";
$lang['ClientServices.manage.button_canceled'] = "Cancelado";
$lang['ClientServices.manage.heading_package'] = "Pacote";
$lang['ClientServices.manage.heading_date_next_invoice'] = "Próxima Fatura";
$lang['ClientServices.manage.heading_price'] = "Montante recorrente";
$lang['ClientServices.manage.text_date_never'] = "Nunca";
$lang['ClientServices.manage.heading_config_options'] = "Opções configuráveis";
$lang['ClientServices.cancel.field_do_not'] = "Não cancelar";
$lang['ClientServices.addons.create_addon'] = "Adicionar Addon";
$lang['ClientServices.!error.addon_invalid'] = "Por favor escolha um addon válido.";
$lang['ClientServices.addaddon.page_title'] = "Cliente #%1\$s Adicionar Addon"; // %1$s is the client ID number
$lang['ClientServices.addaddon.boxtitle_addons'] = "Adicionar Addon para %1\$s - %2\$s"; // %1$s is the package name, %2$s is the service name
$lang['ClientServices.addaddon.term'] = "%1\$s %2\$s"; // %1$s is the package term (e.g. 1), %2$s is the package period (e.g. Month)
$lang['ClientServices.addaddon.term_price'] = "%1\$s - %2\$s"; // %1$s is the package term, (e.g. 1 Month), %2$s is the formatted package price
$lang['ClientServices.addaddon.term_price_setupfee'] = "%1\$s - %2\$s + %3\$s instalação"; // %1$s is the package term, (e.g. 1 Month), %2$s is the formatted package price, %3$s is the formatted setup fee price
$lang['ClientServices.addaddon.submit_add'] = "Criar";
$lang['ClientServices.configure_addon.header_options'] = "Opções Configuráveis"; // %1$s is the module name
$lang['ClientServices.!success.service_package_updated'] = "O pacote de serviço foi atualizado.";
$lang['ClientServices.manage.boxtitle_manage'] = "Gerir %1\$s - %2\$s"; // %1$s is the package name, %2$s is the service name
$lang['ClientServices.manage.button_change_service_term'] = "Alterar Termo";
$lang['ClientServices.manage.button_change_service_package'] = "Mudar Pacote";
$lang['ClientServices.manage.text_price'] = "%1\$sx %2\$s"; // %1$s is the service quantity, %2$s is the package price
$lang['ClientServices.manage.text_date_suspended'] = "Este serviço foi suspenso a %1\$s."; // %1$s is the date the service was suspended
$lang['ClientServices.manage.text_date_canceled'] = "Este serviço foi cancelado a %1\$s."; // %1$s is the date the service was canceled
$lang['ClientServices.manage.heading_options'] = "Ações";
$lang['ClientServices.cancel.field_cancel_submit'] = "Guardar";
$lang['ClientServices.change_term.field_pricing_id'] = "Novo Termo";
$lang['ClientServices.get_package_terms.term'] = "%1\$s %2\$s - %3\$s"; // %1$s is the pricing term, %2$s is the pricing period, and %3$s is the formatted price
$lang['ClientServices.get_package_terms.term_onetime'] = "%1\$s - %2\$s"; // %1$s is the pricing period, and %2$s is the formatted price
$lang['ClientServices.upgrade.btn_make_payment'] = "Efetuar Pagamento";
$lang['ClientServices.upgrade.field_pricing_id'] = "Novo Pacote";
$lang['ClientServices.upgrade.field_cancel'] = "Cancelar";
$lang['ClientServices.upgrade.current_package_onetime'] = "%1\$s (%2\$s - %3\$s)"; // %1$s is the package name, %2$s is the pricing period, and %3$s is the formatted price
$lang['ClientServices.!notice.queued_service_change'] = "Este serviço tem alterações pendentes. Alterações adicionais não devem ser feitas até as alterações pendentes serem processadas.";
$lang['ClientServices.index.recurring_term'] = "%1\$s %2\$s @ %3\$s"; // %1$s is the service term length (number), %2$s is the service period, %3$s is the formatted service renewal price
$lang['ClientServices.manage.heading_price_onetime'] = "Montante";
$lang['ClientServices.manage.text_coupon_percent'] = "%1\$s (%2\$s%%)"; // %1$s is the coupon code, %2$s is the coupon discount percentage. You MUST use two % signs to represent a single percent (i.e. %%)
$lang['ClientServices.manage.text_coupon_amount'] = "%1\$s (%2\$s)"; // %1$s is the coupon code, %2$s is the formatted coupon amount
$lang['ClientServices.change_term.cancel'] = "Cancelar";
$lang['ClientServices.change_term.review'] = "Rever";
$lang['ClientServices.upgrade.page_title'] = "Cliente #%1\$s Alterar Pacote"; // %1$s is the client ID number
$lang['ClientServices.manageoptions.heading_current'] = "Opções actuais";
$lang['ClientServices.manageoptions.cancel'] = "Cancelar";
$lang['ClientServices.manageoptions.review'] = "Rever";
$lang['ClientServices.review.heading_label'] = "Opção";
$lang['ClientServices.review.heading_old_value'] = "Valor atual";
$lang['ClientServices.review.heading_new_value'] = "Novo Valor";
$lang['ClientServices.review.none'] = "-";
$lang['ClientServices.review.cancel'] = "Cancelar";
$lang['ClientServices.review.update'] = "Guardar";
$lang['ClientServices.totals.subtotal'] = "Subtotal:";
$lang['ClientServices.totals.total'] = "Total:";
?>