<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientInvoices.index.page_title'] = "Cliente #%1\$s Faturas"; // %1$s is the client ID number
$lang['ClientInvoices.index.category_closed'] = "Fechadas";
$lang['ClientInvoices.index.categorylink_make_payment'] = "Efetuar Pagamento";
$lang['ClientInvoices.index.boxtitle_invoices'] = "Faturas";
$lang['ClientInvoices.index.heading_invoice'] = "Fatura #";
$lang['ClientInvoices.index.heading_amount'] = "Quantidade";
$lang['ClientInvoices.index.heading_paid'] = "Pago";
$lang['ClientInvoices.index.heading_datedue'] = "Data de Vencimento";
$lang['ClientInvoices.index.heading_options'] = "Opções";
$lang['ClientInvoices.index.option_view'] = "Ver";
$lang['ClientInvoices.index.option_pay'] = "Pagar";
$lang['ClientInvoices.index.no_results'] = "Você não tem Faturas %1\$s."; // %1$s is the language for the invoice category type (e.g. Open, Closed)
$lang['ClientInvoices.applied.heading_paymenttype'] = "Tipo de Pagamento";
$lang['ClientInvoices.applied.heading_applied'] = "Aplicado";
$lang['ClientInvoices.applied.heading_appliedon'] = "Aplicado a";
$lang['ClientInvoices.applied.no_results'] = "Esta factura não possui transações aplicadas a ela.
";
?>