<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientPay.index.boxtitle_pay'] = "Efetuar Pagamento";
$lang['ClientPay.index.field_submit'] = "Continuar";
$lang['ClientPay.multipleinvoices.text_amount'] = "Montante a Pagar";
$lang['ClientPay.multipleinvoices.text_due'] = "Montante Vencido";
$lang['ClientPay.multipleinvoices.text_invoice'] = "Fatura #";
$lang['ClientPay.multipleinvoices.text_datedue'] = "Data de vencimento";
$lang['ClientPay.multipleinvoices.no_results'] = "Não há facturas nesta moeda.";
$lang['ClientPay.received.page_title'] = "Pagamento do Cliente %1\$s recebido"; // %1$s is the client ID
$lang['ClientPay.received.boxtitle_received'] = "Obrigado!";
$lang['ClientPay.received.statement'] = "O seu pagamento está a ser processado.";
$lang['ClientPay.setcontactview.text_none'] = "Nenhum";
$lang['ClientPay.index.field_credit'] = "Outra quantia de pagamento";
$lang['ClientPay.method.page_title'] = "Cliente %1\$s Método de Pagamento"; // %1$s is the client ID
$lang['ClientPay.method.field_useaccount'] = "Usar Conta de Pagamento";
$lang['ClientPay.method.field_newdetails'] = "Novos Detalhes de Pagamento";
$lang['ClientPay.method.field_paymentaccount'] = "%1\$s %2\$s - %3\$s x%4\$s"; // %1$s is the account first name, %2$s is the account last name, %3$s is the account type (card type or bank account type), %4$s is the last 4 of the account
$lang['ClientPay.confirm.boxtitle_confirm'] = "Confirmar Pagamento";
$lang['ClientPay.confirm.payment_details'] = "Detalhes do Pagamento";
$lang['ClientPay.confirm.account_exp'] = "expira a %1\$s"; // %1$s is the date the credit card expires
$lang['ClientPay.confirm.total'] = "Total:";
$lang['ClientPay.confirm.field_submit'] = "Submeter Pagamento";
$lang['ClientPay.confirm.field_edit'] = "Editar Pagamento";
$lang['ClientPay.confirm.description_invoice'] = "FATURA #%1\$s"; // %1$s is the invoice number
$lang['ClientPay.confirm.description_invoice_separator'] = ",";
$lang['ClientPay.confirm.description_invoice_number'] = "#%1\$s"; // %1$s is the invoice number
$lang['ClientPay.!error.invalid_details'] = "Por favor escolha uma opção de pagamento.";
$lang['ClientPay.method.heading_other_payment_options'] = "Outras Opções de Pagamento";
$lang['ClientPay.method.no_options'] = "Não existem opções de pagamento disponíveis.";
$lang['ClientPay.method.field_apply_credit'] = "Aplicar Crédito (%1\$s Disponível)"; // %1$s is the amount of available credit that may be used
$lang['ClientPay.method.field_credit_submit'] = "Aplicar Crédito e Continuar";
$lang['ClientPay.method.heading_invoice'] = "Fatura #%1\$s"; // %1$s is the invoice ID code
$lang['ClientPay.method.invoice_description'] = "Descrição";
$lang['ClientPay.method.invoice_quantity'] = "Quantidade";
$lang['ClientPay.method.invoice_amount'] = "Quantia";
$lang['ClientPay.!error.invoice_voided'] = "Esta fatura foi anulada e não pode ser paga.";
$lang['ClientPay.received.transaction_id'] = "ID da Transacção";
$lang['ClientPay.received.invoices'] = "Fatura #";
?>