<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ClientTransactions.index.boxtitle_transactions'] = "Transações";
$lang['ClientTransactions.index.category_approved'] = "Aprovado";
$lang['ClientTransactions.index.category_declined'] = "Rejeitado";
$lang['ClientTransactions.index.heading_type'] = "Tipo";
$lang['ClientTransactions.index.heading_amount'] = "Montante";
$lang['ClientTransactions.index.heading_credited'] = "Creditado";
$lang['ClientTransactions.index.heading_applied'] = "Aplicado";
$lang['ClientTransactions.index.heading_number'] = "Número";
$lang['ClientTransactions.index.heading_date'] = "Data";
$lang['ClientTransactions.index.no_results'] = "Você não tem Transações %1\$s"; // %1$s is the language for the transaction category type (e.g. Approved, Declined)
$lang['ClientTransactions.applied.heading_invoice'] = "Fatura";
$lang['ClientTransactions.applied.heading_amount'] = "Quantia";
?>