<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Companies.!error.company_id.exists'] = "ID Empresa inválido";
$lang['Companies.!error.name.empty'] = "Por favor introduza um nome.";
$lang['Companies.!error.inv_start.number'] = "O valor inicial da fatura tem que ser numérico.";
$lang['Companies.!error.hostname.valid'] = "Por favor introduza um hostname válido.";
$lang['Companies.!error.hostname.length'] = "O nome da máquina não pode ser superior a 255 caracteres.";
?>