<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Contacts.!error.client_id.exists'] = "ID do cliente inválido.";
$lang['Contacts.!error.contact_type.format'] = "Tipo de contacto inválido";
$lang['Contacts.!error.contact_type_id.format'] = "ID de tipo de contacto inválido.";
$lang['Contacts.!error.first_name.empty'] = "Por favor introduza um primeiro nome.";
$lang['Contacts.!error.last_name.empty'] = "Por favor introduza um último nome.";
$lang['Contacts.!error.email.format'] = "Endereço Email inválido.";
$lang['Contacts.!error.contact_id.exists'] = "ID de contacto inválido.";
$lang['Contacts.!error.number.empty'] = "Por favor introduza um número de contacto.";
$lang['Contacts.!error.location.format'] = "Localização inválida.";
$lang['Contacts.!error.id.exists'] = "ID do número de contacto inválido.";
$lang['Contacts.!error.name.empty'] = "Por favor introduza um nome.";
$lang['Contacts.getcontacttypes.primary'] = "Primário";
$lang['Contacts.getcontacttypes.other'] = "Outro";
$lang['Contacts.getnumbertypes.phone'] = "Telefone";
$lang['Contacts.getnumbertypes.fax'] = "Fax";
$lang['Contacts.getnumberlocations.home'] = "Início";
$lang['Contacts.getnumberlocations.work'] = "Trabalho";
$lang['Contacts.getnumberlocations.mobile'] = "Móvel";
$lang['Contacts.getPermissionOptions.client_invoices'] = "Faturas";
$lang['Contacts.getPermissionOptions.client_services'] = "Serviços";
$lang['Contacts.getPermissionOptions.client_transactions'] = "Transações";
$lang['Contacts.getPermissionOptions.client_contacts'] = "Contactos";
$lang['Contacts.getPermissionOptions.client_accounts'] = "Contas de Pagamento";
$lang['Contacts.getPermissionOptions._credits'] = "Créditos";
$lang['Contacts.!error.company.empty'] = "Por favor introduza uma empresa.";
$lang['Contacts.!error.city.empty'] = "Por favor introduza uma cidade.";
$lang['Contacts.!error.country.empty'] = "Por favor escolha um país.";
?>