<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Countries.!error.alpha2.format'] = "Código do país Alpha2 deve conter 2 caracteres alfabéticos.";
$lang['Countries.!error.name.format'] = "Por favor introduza um nome.";
?>