<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Coupons.getAmountTypes.amount'] = "Montante";
$lang['Coupons.!error.code.empty'] = "Por favor introduza um código de cupão.";
$lang['Coupons.!error.code.length'] = "O comprimentos do código do Cupão não deve exceder os 64 caracteres.";
$lang['Coupons.!error.start_date.format'] = "Formato de data de início inválido.";
$lang['Coupons.!error.status.format'] = "Estado inválido.";
$lang['Coupons.!error.coupon_id.exists'] = "ID de Cupão inválido.";
$lang['Coupons.!error.max_qty.exceeded'] = "A quantidade usada não pode exceder a quantidade máxima.";
?>