<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Cron.index.attempt_all'] = "A tentar correr todas as tarefas de %1\$s."; // %1$s is the company name
$lang['Cron.index.completed_all_system'] = "Todas as tarefas do sistema foram completas.";
$lang['Cron.createinvoices.recurring_invoice_failed'] = "Não foi possível criar uma nova fatura a partir da factura #%1\$s para o cliente #%2\$s."; // %1$s is the recurring invoic enumber, %2$s is the client ID
$lang['Cron.autodebitinvoices.charge_failed'] = "Não foi possível processar o pagamento.";
$lang['Cron.autodebitinvoices.charge_success'] = "Pagamento processado com sucesso.";
$lang['Cron.cardexpirationreminders.completed'] = "A tarefa de lembretes da expiração dos cartões foi concluída.";
$lang['Cron.deliverinvoices.method_email'] = "email";
$lang['Cron.deliverinvoices.method_interfax'] = "InterFax";
$lang['Cron.suspendservices.suspend_success'] = "O serviço #%1\$s do cliente %2\$s foi suspenso."; // %1$s is the service ID, %2$s is the client ID
$lang['Cron.cancelscheduledservices.cancel_error'] = "O serviço #%1\$s do cliente #%2\$s não pôde ser cancelado."; // %1$s is the service ID, %2$s is the client ID
$lang['Cron.addpaidpendingservices.service_success'] = "O serviço pendente #%1\$s, do cliente #%2\$s está agora activo."; // %1$s is the service ID, %2$s is the client ID
$lang['Cron.updateexchangerates.failed'] = "As Taxas de Câmbio não puderam ser actualizadas.";
$lang['Cron.cleanlogs.attempt'] = "A tentar limpar registos antigos.";
$lang['Cron.cleanlogs.logs_contact_deleted'] = " Os logs de contactos antigos de %1\$s foram apagados."; // %1$s is the number of logs deleted
$lang['Cron.cleanlogs.logs_email_deleted'] = "%1\$s registos antigos de transações de correio foram apagados."; // %1$s is the number of logs deleted
$lang['Cron.backups_amazons3.success'] = "A cópia de segurança foi concluída com êxito.";
$lang['Cron.backups_sftp.success'] = "A cópia de segurança foi completa com sucesso.";
$lang['Cron.deliverreports.aging_invoices.email_error'] = "Não foi possível enviar as Faturas antigas por email.";
$lang['Cron.applycredits.apply_success'] = "Aplicados com sucesso créditos pendentes da transação %1\$s do cliente #%2\$s para a factura #%3\$s no valor de %4\$s."; // %1$s is the transaction number, %2$s is the client ID, %3$s is the invoice ID, and %4$s is the amount applied
?>