<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['CronTasks.!error.id.exists'] = "ID de tarefa cron inválido.";
$lang['CronTasks.!error.is_lang.format'] = "is_lang deve ser um número.";
$lang['CronTasks.!error.is_lang.length'] = "O comprimento de is_lang não deve exceder 1 caracter.";
$lang['CronTasks.!error.type.format'] = "Tipo de tarefa cron inválido.";
$lang['CronTasks.crontask.name.create_invoice'] = "Criar Fatura";
$lang['CronTasks.crontask.name.autodebit'] = "Débito automático";
$lang['CronTasks.crontask.name.apply_payments'] = "Aplicar Pagamentos a Faturas Abertas";
$lang['CronTasks.crontask.name.deliver_invoices'] = "Entragar Faturas";
$lang['CronTasks.crontask.description.deliver_invoices'] = "As faturas que estão planeadas para entrega, serão enviadas no intervalo selecionado";
$lang['CronTasks.crontask.name.suspend_services'] = "Suspender serviços";
$lang['CronTasks.crontask.name.cleanup_logs'] = "Limpar os Logs";
$lang['CronTasks.crontask.name.backups_amazons3'] = "Backups Amazon S3";
$lang['CronTasks.crontask.name.unsuspend_services'] = "Retirar Suspensão de Serviços";
$lang['CronTasks.crontask.name.license_validation'] = "Validação de Licença";
?>