<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Currencies.!error.company_id.exists'] = "ID de empresa inválido.";
$lang['Currencies.!error.format.format'] = "Formato de moeda inválido.";
$lang['Currencies.!error.currency_code.is_default'] = "A moeda %1\$s é a moeda pré-definida e não pode ser apagada."; // %1$s is the currency code
?>