<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Emails.!error.text.empty'] = "Por favor introduza uma assinatura só em texto.";
$lang['Emails.!error.lang.empty'] = "Por favor introduza uma linguagem.";
$lang['Emails.!error.from.format'] = "Por favor introduza um endereço de email válido.";
$lang['Emails.!error.subject.empty'] = "Por favor insira um assunto.";
$lang['Emails.!error.status.format'] = "Estado Inválido.";
$lang['Emails.!error.email_id.exists'] = "ID do email inválido.";
$lang['Emails.getStatusTypes.active'] = "Não";
$lang['Emails.getStatusTypes.inactive'] = "Sim";
$lang['Emails.!error.email.failed_to_send'] = "A entrega do email falhou devido a um problema nas configurações.";
$lang['Emails.!error.reply_to.format'] = "Por favor introduza um email válido para resposta.";
?>