<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['EmailGroups.!error.action.empty'] = "Por favor introduza uma ação.";
$lang['EmailGroups.!error.action.length'] = "O campo não pode exceder os 64 caracteres.";
$lang['EmailGroups.!error.type.format'] = "Tipo inválido.";
?>