<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Encryption.!error.current_passphrase.empty'] = "Por favor, indique o atual senha de chave privada.";
$lang['Encryption.!error.confirm_new_passphrase.matches'] = "A nova senha não corresponde.";
?>