<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['GatewayPayments.!error.gateway.exists'] = "O gateway não existe ou não está ativo.";
$lang['GatewayPayments.!error.transaction_id.exists'] = "A transação não pôde ser encontrada para esse cliente.";
$lang['GatewayPayments.!error.account_id.exists'] = "A conta de pagamento poderá não ser encontrada para esse cliente.";
$lang['GatewayPayments.!error.type.valid'] = "O tipo de pagamento não é suportado por este gateway.";
$lang['GatewayPayments.!error.type.instance'] = "O gateway não suporta os pagamentos dessa maneira.";
$lang['GatewayPayments.!error.reference_id.update'] = "O gateway de pagamento não conseguiu actualizar a conta de pagamento.";
$lang['GatewayPayments.!error.gateway.declined'] = "O pagamento foi rejeitado.";
?>