<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Invoices.getPricingPeriods.week'] = "Semana";
$lang['Invoices.getPricingPeriods.month'] = "Mês";
$lang['Invoices.getPricingPeriods.year'] = "Ano";
$lang['Invoices.getDeliveryMethods.email'] = "Email";
$lang['Invoices.getDeliveryMethods.paper'] = "Papel";
$lang['Invoices.getDeliveryMethods.interfax'] = "InterFax";
$lang['Invoices.!error.invoice_id.exists'] = "ID de fatura inválido.";
$lang['Invoices.!error.method.exists'] = "Tem de definir pelo menos um método de entrega.";
$lang['Invoices.!error.delivery.empty'] = "Por favor introduza um método de entrega de Faturas.";
$lang['Invoices.!error.id_format.length'] = "O formato do campo ID para as Faturas não pode exceder os 64 caracteres";
$lang['Invoices.!error.client_id.exists'] = "ID de cliente inválido.";
$lang['Invoices.!error.status.format'] = "Estado inválido.";
$lang['Invoices.!error.currency.length'] = "O código da moeda tem de ter 3 caracteres de cumprimento.";
$lang['Invoices.!error.delivery.exists'] = "O método de entrega dado não existe.";
$lang['Invoices.!error.term.format'] = "O termo deve ser numérico.";
$lang['Invoices.!error.term.bounds'] = "O termo deve ser entre 1 e 65535.";
$lang['Invoices.!error.period.format'] = "O período é inválido.";
$lang['Invoices.!error.duration.format'] = "A duração é inválida.";
$lang['Invoices.!error.lines[][service_id].exists'] = "ID de serviço inválido.";
$lang['Invoices.!error.lines[][description].empty'] = "Digite uma descrição do item da linha.";
$lang['Invoices.!error.lines[][qty].format'] = "A quantidade tem de ser um número.";
$lang['Invoices.!line_item.coupon_line_item_description_amount'] = "Cupão %1\$s"; // %1$s is the coupon code
$lang['Invoices.!line_item.coupon_line_item_description_percent'] = "Cupão %1\$s - %2\$s%%"; // %1$s is the coupon code, %2$s is the coupon discount percentage, the two percent symbols (%%) must both be used together to display a single percent symbol
$lang['Invoices.!line_item.recurring_renew_description'] = "%1\$s (%2\$s - %3\$s)"; // %1$s is the line item description, %2$s is the invoice's renew date, %3$s is the invoice's next renew date
$lang['Invoices.status.active'] = "Activo";
$lang['Invoices.status.draft'] = "Rascunho";
$lang['Invoices.status.void'] = "Anulado";
$lang['Invoices.!line_item.service_addon_identifier'] = "+";
$lang['Invoices.!line_item.service_created_description'] = "%3\$s%1\$s - %2\$s"; // %1$s is the name of the package, %2$s is the name of the service, %3$s is the addon identifier set only for addon services
$lang['Invoices.status.proforma'] = "Pró-forma";
$lang['Invoices.types.proforma'] = "Pró-forma";
$lang['Invoices.!line_item.service_option_renew_description'] = "? %1\$s - %2\$s"; // %1$s is the package option label, %2$s is the service option name
$lang['Invoices.!note_private.line_item'] = "- %1\$s @ %2\$s: %3\$s"; // %1$s is the line item quantity, %2$s is the unit price, %3$s is the line item description
?>