<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Logs.!error.company_id.exists'] = "ID da empresa inválido.";
$lang['Logs.!error.staff_id.empty'] = "ID de Equipa em falta.";
$lang['Logs.!error.module_id.exists'] = "ID de módulo inválido.";
$lang['Logs.!error.gateway_id.exists'] = "ID de gateway inválido.";
$lang['Logs.!error.url.empty'] = "URL em falta.";
$lang['Logs.!error.status.format'] = "Tipo de estado inválido.";
$lang['Logs.!error.group.empty'] = "Grupo em falta.";
$lang['Logs.!error.contact_id.empty'] = "ID de contato em falta.";
$lang['Logs.!error.type.format'] = "Tipo inválido.";
$lang['Logs.!error.first_name.empty'] = "O Nome não pode estar vazio.";
$lang['Logs.!error.start_date.format'] = "Formato da data de início inválido";
$lang['Logs.!error.deletelog_datetime'] = "Formato de data inválido.";
?>