<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['MerchantGateway.!error.card_number_invalid'] = "O número do cartão é inválido.";
$lang['MerchantGateway.!error.card_expired'] = "O cartão expirou.";
$lang['MerchantGateway.!error.routing_number_invalid'] = "O número de routing é inválido";
$lang['MerchantGateway.!error.duplicate_transaction'] = "Foi detetada uma transação duplicada.";
$lang['MerchantGateway.!error.unsupported'] = "O gateway não suporta essa ação.";
?>