<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ModuleManager.!error.company_id.valid'] = "O ID da Empresa é inválido.";
$lang['ModuleManager.!error.version.valid'] = "A versão é inválida.";
$lang['ModuleManager.!error.name.empty'] = "Tem de especificar um nome para o grupo.";
$lang['ModuleManager.!error.module_row_id.assigned_package'] = "A linha não pode ser apagada porque pertence a um ou mais pacotes.";
$lang['ModuleManager.!error.module_group_id.assigned_package'] = "O grupo não pode ser excluído porque pertence a um ou mais pacotes.";
$lang['ModuleManager.!error.module_row_id.assigned_service'] = "A linha não pode ser excluída porque pertence a um ou mais serviços.";
?>