<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Navigation.getprimary.nav_home'] = "Início";
$lang['Navigation.getprimary.nav_clients'] = "Clientes";
$lang['Navigation.getprimary.nav_billing'] = "Faturação";
$lang['Navigation.getprimary.nav_billing_overview'] = "Vista Geral";
$lang['Navigation.getprimary.nav_billing_invoices'] = "Faturas";
$lang['Navigation.getprimary.nav_billing_transactions'] = "Transações";
$lang['Navigation.getprimary.nav_billing_services'] = "Serviços";
$lang['Navigation.getprimary.nav_billing_reports'] = "Relatórios";
$lang['Navigation.getprimary.nav_packages'] = "Pacotes";
$lang['Navigation.getprimary.nav_tools'] = "Ferramentas";
$lang['Navigation.getprimary.nav_tools_currency'] = "Converter Moeda";
$lang['Navigation.getprimary.nav_settings_company'] = "Empresa";
$lang['Navigation.getprimary.nav_settings_system'] = "Sistema";
$lang['Navigation.getcompany.nav_general'] = "Geral";
$lang['Navigation.getcompany.nav_general_localization'] = "Localização";
$lang['Navigation.getcompany.nav_general_international'] = "Internacionalização";
$lang['Navigation.getcompany.nav_general_encryption'] = "Encriptação";
$lang['Navigation.getcompany.nav_general_contacttypes'] = "Tipos de Contactos";
$lang['Navigation.getcompany.nav_automation'] = "Automação";
$lang['Navigation.getcompany.nav_billing_deliverymethods'] = "Entrega de faturas";
$lang['Navigation.getcompany.nav_billing_notices'] = "Avisos de Pagamento em atraso";
$lang['Navigation.getcompany.nav_billing_coupons'] = "Cupões";
$lang['Navigation.getcompany.nav_billing_acceptedtypes'] = "Tipos de Pagamento aceites";
$lang['Navigation.getcompany.nav_modules'] = "Módulos";
$lang['Navigation.getcompany.nav_gateways'] = "Gateways de Pagamento";
$lang['Navigation.getcompany.nav_taxes'] = "Impostos";
$lang['Navigation.getcompany.nav_emails'] = "Emails";
$lang['Navigation.getcompany.nav_emails_mail'] = "Definições de Email";
$lang['Navigation.getcompany.nav_emails_templates'] = "Templates de Email";
$lang['Navigation.getcompany.nav_emails_signatures'] = "Assinaturas";
$lang['Navigation.getcompany.nav_currency_active'] = "Moedas activas";
$lang['Navigation.getcompany.nav_plugins'] = "Plugins";
$lang['Navigation.getsystem.nav_general'] = "Geral";
$lang['Navigation.getsystem.nav_general_geoip'] = "Configurações GeoIP";
$lang['Navigation.getsystem.nav_general_maintenance'] = "Manutenção";
$lang['Navigation.getsystem.nav_general_paymenttypes'] = "Tipos de pagamento";
$lang['Navigation.getsystem.nav_automation'] = "Automação";
$lang['Navigation.getsystem.nav_backup_ftp'] = "FTP Seguro";
$lang['Navigation.getsystem.nav_backup_amazon'] = "Amazon S3";
$lang['Navigation.getsystem.nav_staff'] = "Funcionários";
$lang['Navigation.getsystem.nav_staff_manage'] = "Gerir Staff";
$lang['Navigation.getsystem.nav_staff_groups'] = "Grupos de Staff";
$lang['Navigation.getsystem.nav_api'] = "Acesso API";
$lang['Navigation.getsystem.nav_help'] = "Ajuda";
$lang['Navigation.getsystem.nav_marketplace'] = "Mercado";
$lang['Navigation.getprimary.nav_home_dashboard'] = "Painel ";
$lang['Navigation.getprimary.nav_billing_batch'] = "Lote";
$lang['Navigation.getprimaryclient.nav_contacts'] = "Contactos";
$lang['Navigation.getsystem.nav_help_index'] = "Recursos";
$lang['Navigation.getsearchoptions.smart'] = "Procura Inteligente";
$lang['Navigation.getsearchoptions.clients'] = "Procura de Clientes";
$lang['Navigation.getsearchoptions.invoices'] = "Pesquisa de Faturas";
$lang['Navigation.getsearchoptions.services'] = "Pesquisa de serviço";
$lang['Navigation.getsearchoptions.packages'] = "Procura de Pacote";
$lang['Navigation.getprimaryclient.nav_paymentaccounts_add'] = "Adicionar Conta de Pagamento";
$lang['Navigation.getprimaryclient.nav_contacts_add'] = "Adicionar Contacto";
$lang['Navigation.getcompany.nav_lookandfeel_themes'] = "Temas";
$lang['Navigation.getcompany.nav_lookandfeel_template'] = "Modelo";
$lang['Navigation.getprimary.nav_clients_browse'] = "Navegar pelos Clientes";
$lang['Navigation.getprimary.nav_packages_groups'] = "Grupos de Pacotes";
$lang['Navigation.getcompany.nav_clientoptions'] = "Opções de Cliente";
?>