<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['NonmerchantGateway.!error.transaction_not_found'] = "A transação é inválida ou não está disponível para o processamento dessa ação.";
$lang['NonmerchantGateway.!error.unsupported'] = "O gateway não suporta essa ação.";
$lang['NonmerchantGateway.!error.general'] = "Ocorreu um erro ao processar o pedido com o gateway.";
?>