<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PackageOptionGroups.!error.company_id.exists'] = "Por favor, especifique um ID válido para a empresa.";
$lang['PackageOptionGroups.!error.name.empty'] = "Por favor especifique um nome de grupo.";
$lang['PackageOptionGroups.!error.name.length'] = "O nome do grupo não pode exceder os 128 caracteres de comprimento.";
?>