<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Packages.!error.package_id.exists'] = "O pacote não pôde ser eliminado pois existe contas ativas com o mesmo.";
$lang['Packages.!error.name.empty'] = "Por favor introduza um nome para o pacote.";
$lang['Packages.!error.qty.format'] = "A quantidade tem de ser um número.";
$lang['Packages.!error.taxable.format'] = "Tributável tem de ser um número.";
$lang['Packages.!error.email_content[][lang].empty'] = "Por favor introduza uma linguagem.";
$lang['Packages.getPricingPeriods.day'] = "Dia";
$lang['Packages.getPricingPeriods.week'] = "Semana";
$lang['Packages.getPricingPeriods.month'] = "Mês";
$lang['Packages.getPricingPeriods.year'] = "Ano";
$lang['Packages.getPricingPeriods.onetime'] = "Uma vez";
$lang['Packages.getStatusTypes.inactive'] = "Inativo";
$lang['Packages.getStatusTypes.restricted'] = "Restrito";
$lang['Packages.!error.pricing[][term].format'] = "Termo tem de ser um número.";
$lang['Packages.!error.pricing[][price].format'] = "O Preço tem de ser um número.";
$lang['Packages.!error.pricing[][setup_fee].format'] = "A Taxa de Instalação deve ser um número.";
$lang['Packages.!error.pricing[][cancel_fee].format'] = "Taxa de Cancelamento tem de ser um número.";
$lang['Packages.getPricingPeriods.day_plural'] = "Dias";
$lang['Packages.getPricingPeriods.month_plural'] = "Meses";
$lang['Packages.getPricingPeriods.year_plural'] = "Anos";
$lang['Packages.!error.pricing[][term].valid'] = "O termo tem de ser maior que 0.";
?>