<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PackageOptions.!error.company_id.exists'] = "ID de empresa inválido.";
$lang['PackageOptions.!error.name.length'] = "O nome não deve exceder os 128 caracteres de comprimento.";
$lang['PackageOptions.!error.values[][name].empty'] = "Por favor introduza um nome para o valor da opção.";
$lang['PackageOptions.!error.values[][pricing][][term].format'] = "O Termo tem de ser um número.";
$lang['PackageOptions.!error.values[][pricing][][term].valid'] = "O termo tem de ser maior que 0.";
$lang['PackageOptions.!error.values[][pricing][][setup_fee].format'] = "Taxa de Instalação tem de ser um número.";
$lang['PackageOptions.gettypes.quantity'] = "Quantidade";
$lang['PackageOptions.gettypes.radio'] = "Rádio";
$lang['PackageOptions.getfields.label_radio'] = "%1\$s (%2\$s)"; // %1$s is the option value, %2$s is the option price
$lang['PackageOptions.getfields.label_select'] = "%1\$s (%2\$s)"; // %1$s is the option value, %2$s is the option price
$lang['PackageOptions.getfields.label_checkbox_setup'] = "%1\$s (%2\$s + %3\$s instalação)"; // %1$s is the option value, %2$s is the option price, %3$s is the setup fee
$lang['PackageOptions.!error.type.valid'] = "Por favor escolha um tipo de opção.";
$lang['PackageOptions.!error.values[][id].exists'] = "ID do valor da opção do pacote inválido.";
?>