<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Permissions.!error.group_id.exists'] = "O grupo de permissão dado não existe.";
$lang['Permissions.!error.action.empty'] = "A permissão deve ter uma ação.";
$lang['Permissions.!error.level.group_empty'] = "O nível deve ser 'staff' ou 'cliente'.";
?>