<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['PluginManager.!error.company_id.exists'] = "ID de Empresa inválido.";
$lang['PluginManager.!error.author.empty'] = "Por favor introduza o autor do Plugin.";
$lang['PluginManager.!error.version.empty'] = "Por favor introduza a versão do plugin.";
$lang['PluginManager.!error.event.empty'] = "Por favor, indique um evento.";
$lang['PluginManager.!error.action.empty'] = "Por favor, indique uma ação.";
?>