<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Pricings.!error.term.format'] = "O Termo tem de ser um número.";
$lang['Pricings.!error.term.length'] = "Prazo comprimento não pode exceder os 5 caracteres.";
$lang['Pricings.!error.period.format'] = "Tipo de Período inválido.";
$lang['Pricings.!error.price.format'] = "O preço deve ser um número.";
$lang['Pricings.!error.setup_fee.format'] = "A Taxa de Instalação tem de ser um número.";
$lang['Pricings.!error.cancel_fee.format'] = "A taxa de cancelamento tem de ser um número.";
$lang['Pricings.!error.currency.format'] = "O código da moeda deve ter 3 caracteres.";
$lang['Pricings.getPeriods.day'] = "Dia";
$lang['Pricings.getPeriods.week'] = "Semana";
$lang['Pricings.getPeriods.month'] = "Mês";
$lang['Pricings.getPeriods.year'] = "Ano";
$lang['Pricings.getPeriods.onetime'] = "Pagamento Unico";
$lang['Pricings.getPeriods.day_plural'] = "Dias";
$lang['Pricings.getPeriods.week_plural'] = "Semanas";
$lang['Pricings.getPeriods.month_plural'] = "Meses";
?>