<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['ServiceChanges.!error.service_id.exists'] = "ID de serviço inválido.";
$lang['ServiceChanges.!error.invoice_id.exists'] = "ID de fatura inválido.";
$lang['ServiceChanges.status.pending'] = "Pendente";
$lang['ServiceChanges.status.error'] = "Erro";
$lang['ServiceChanges.status.canceled'] = "Cancelado";
?>