<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Services.!error.qty.format'] = "Quantidade tem de ser um número.";
$lang['Services.!error.status.format'] = "Estado inválido.";
$lang['Services.!error.date_renews.format'] = "Formato de data de renovação inválido.";
$lang['Services.!error.fields[][value].empty'] = "Um valor dos campos do serviço está vazio.";
$lang['Services.getStatusTypes.active'] = "Ativo";
$lang['Services.getStatusTypes.canceled'] = "Cancelado";
$lang['Services.getStatusTypes.pending'] = "Pendente";
$lang['Services.getStatusTypes.suspended'] = "Suspenso";
$lang['Services.!error.coupon_id.valid'] = "Esse cupão não parece ser válido.";
$lang['Services.!error.invoice_method.valid'] = "Tem de selecionar um método de faturação válido.";
$lang['Services.!error.pricing_id.valid'] = "Tem de selecionar um termo válido.";
$lang['Services.getActions.suspend'] = "Suspender";
$lang['Services.getActions.cancel'] = "Cancelar";
$lang['Services.getActions.schedule_cancel'] = "Agendar Cancelamento";
$lang['Services.!error.client_id.exists'] = "O cliente não existe.";
$lang['Services.getStatusTypes.in_review'] = "Em Revisão";
$lang['Services.getActions.change_renew'] = "Alterar a Data de Renovação";
$lang['Services.!error.client_id.allowed'] = "O cliente não pode aceder a esse pacote.";
$lang['Services.!error.override_price.override'] = "O preço e a moeda devem ser definidos para substituir o preço actual.";
$lang['Services.!error.override_currency.format'] = "Por favor escolha uma moeda válida.";
$lang['Services.!error.pricing_id.exists'] = "Por favor escolha um termo válido.";
?>