<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['StaffGroups.!error.company_id.exists'] = "ID de Empresa inválido.";
$lang['StaffGroups.!error.name.empty'] = "Por favor introduza um nome.";
$lang['StaffGroups.!error.name.length'] = "O comprimento do nome não deve exceder os 64 caracteres.";
$lang['StaffGroups.permission_group.clients'] = "Clientes";
$lang['StaffGroups.permission_group.billing'] = "Faturação";
$lang['StaffGroups.permission_group.packages'] = "Pacotes";
$lang['StaffGroups.permission_group.tools'] = "Ferramentas";
$lang['StaffGroups.permission_group.search'] = "Procurar";
$lang['StaffGroups.permission_group.settings'] = "Definições";
$lang['StaffGroups.permissions.admin_clients_view'] = "Ver Cliente";
$lang['StaffGroups.permissions.admin_clients_add'] = "Adicionar Cliente";
$lang['StaffGroups.permissions.admin_clients_edit'] = "Editar Cliente";
$lang['StaffGroups.permissions.admin_clients_invoices'] = "Listar Faturas";
$lang['StaffGroups.permissions.admin_clients_createinvoice'] = "Criar Factura";
$lang['StaffGroups.permissions.admin_clients_editinvoice'] = "Editar Fatura";
$lang['StaffGroups.permissions.admin_clients_editrecurinvoice'] = "Editar Fatura Recorrente";
$lang['StaffGroups.permissions.admin_clients_deleteinvoice'] = "Apagar Fatura";
$lang['StaffGroups.permissions.admin_clients_edittransaction'] = "Editar Transação";
$lang['StaffGroups.permissions.admin_clients_services'] = "Listar Serviços";
$lang['StaffGroups.permissions.admin_clients_addservice'] = "Adicionar Serviço";
$lang['StaffGroups.permissions.admin_clients_deleteservice'] = "Apagar Serviço";
$lang['StaffGroups.permissions.admin_clients_addcontact'] = "Adicionar Contacto";
$lang['StaffGroups.permissions.admin_clients_editcontact'] = "Editar Contacto";
$lang['StaffGroups.permissions.admin_clients_deletecontact'] = "Apagar Contacto";
$lang['StaffGroups.permissions.admin_clients_accounts'] = "Ver Contas de Pagamento";
$lang['StaffGroups.permissions.admin_clients_editachaccount'] = "Editar Conta de Pagamento ACH";
$lang['StaffGroups.permissions.admin_clients_deleteccaccount'] = "Apagar Conta de Pagamento de Cartão de Crédito";
$lang['StaffGroups.permissions.admin_clients_deleteachaccount'] = "Apagar Conta de Pagamento ACH";
$lang['StaffGroups.permissions.admin_clients_notes'] = "Ver Notas";
$lang['StaffGroups.permissions.admin_clients_editnote'] = "Editar Nota";
$lang['StaffGroups.permissions.admin_clients_deletenote'] = "Apagar Nota";
$lang['StaffGroups.permissions.admin_clients_packages'] = "Definir Pacotes";
$lang['StaffGroups.permissions.admin_clients_merge'] = "Juntar Cliente";
$lang['StaffGroups.permissions.admin_clients_delete'] = "Excluir Cliente";
$lang['StaffGroups.permissions.admin_billing_invoices'] = "Lista de Facturas";
$lang['StaffGroups.permissions.admin_billing_services'] = "Listar Serviços";
$lang['StaffGroups.permissions.admin_billing_transactions'] = "Listar Transações";
$lang['StaffGroups.permissions.admin_tools_convert_currency'] = "Converter Moeda";
$lang['StaffGroups.permissions.admin_tools_logs'] = "Registos";
$lang['StaffGroups.permissions.admin_packages_add'] = "Adicionar Pacote";
$lang['StaffGroups.permissions.admin_packages_edit'] = "Editar Pacote";
$lang['StaffGroups.permissions.admin_packages_groups'] = "Ver Grupos de Pacotes";
$lang['StaffGroups.permissions.admin_company_general_localization'] = "Localização";
$lang['StaffGroups.permissions.admin_company_general_international'] = "Internacionalização";
$lang['StaffGroups.permissions.admin_company_general_themes'] = "Temas";
$lang['StaffGroups.permissions.admin_company_general_encryption'] = "Encriptação";
$lang['StaffGroups.permissions.admin_company_billing_customization'] = "Personalização de Fatura";
$lang['StaffGroups.permissions.admin_company_billing_deliverymethods'] = "Entrega de Faturas";
$lang['StaffGroups.permissions.admin_company_billing_coupons'] = "Cupões";
$lang['StaffGroups.permissions.admin_company_modules'] = "Módulos";
$lang['StaffGroups.permissions.admin_company_modules_manage'] = "Gerir Módulo";
$lang['StaffGroups.permissions.admin_company_modules_install'] = "Instalar Módulo";
$lang['StaffGroups.permissions.admin_company_modules_uninstall'] = "Desinstalar Módulo";
$lang['StaffGroups.permissions.admin_company_gateways_uninstall'] = "Desinstalar Gateway";
$lang['StaffGroups.permissions.admin_company_emails_mail'] = "Configurações de Email";
$lang['StaffGroups.permissions.admin_company_emails_templates'] = "Templates de Email";
$lang['StaffGroups.permissions.admin_company_emails_signatures'] = "Assinaturas de Email";
$lang['StaffGroups.permissions.admin_company_plugins'] = "Plugins";
$lang['StaffGroups.permissions.admin_company_plugins_manage'] = "Gerir Plugin";
$lang['StaffGroups.permissions.admin_company_plugins_install'] = "Instalar Plugin";
$lang['StaffGroups.permissions.admin_company_plugins_uninstall'] = "Desinstalar Plugin";
$lang['StaffGroups.permissions.admin_settings_system'] = "Configurações de sistema";
$lang['StaffGroups.permissions.admin_system_general_basic'] = "Configuração Básica";
$lang['StaffGroups.permissions.admin_system_general_geoip'] = "Opções GeoIP";
$lang['StaffGroups.permissions.admin_system_general_maintenance'] = "Manutenção";
$lang['StaffGroups.permissions.admin_system_general_license'] = "Chave de Licença";
$lang['StaffGroups.permissions.admin_system_automation'] = "Automação";
$lang['StaffGroups.permissions.admin_system_companies'] = "Empresas";
$lang['StaffGroups.permissions.admin_system_staff_manage'] = "Gerir Equipa";
$lang['StaffGroups.permissions.admin_system_staff_groups'] = "Grupos de Pessoal";
$lang['StaffGroups.permissions.admin_system_help'] = "Ajuda";
$lang['StaffGroups.permissions.admin_system_marketplace'] = "Mercado";
$lang['StaffGroups.permission_group.home'] = "Início";
$lang['StaffGroups.permissions.admin_main_calendar'] = "Calendário";
$lang['StaffGroups.permissions.admin_clients_loginasclient'] = "Entrar como Cliente";
$lang['StaffGroups.permissions.admin_billing_printqueue'] = "Fila de Impressão";
$lang['StaffGroups.permissions.admin_billing_batch'] = "Lote";
$lang['StaffGroups.permissions.admin_company_general_addcontacttype'] = "Adicionar Tipo de Contacto";
$lang['StaffGroups.permissions.admin_company_general_editcontacttype'] = "Editar Tipo de Contacto";
$lang['StaffGroups.permissions.admin_company_general_deletecontacttype'] = "Apagar tipo de contacto";
$lang['StaffGroups.permissions.admin_company_general_installlanguage'] = "Instalar Idioma
";
$lang['StaffGroups.permissions.admin_company_general_uninstalllanguage'] = "Desinstalar Linguagem";
$lang['StaffGroups.permissions.admin_company_billing_acceptedtypes'] = "Tipos de Pagamento Aceites";
$lang['StaffGroups.permissions.admin_system_general_addtype'] = "Adicione tipo de Pagamento";
$lang['StaffGroups.permissions.admin_system_general_edittype'] = "Editar Tipo de Pagamento";
$lang['StaffGroups.permissions.admin_system_general_deletetype'] = "Apagar Tipo de Pagamento";
$lang['StaffGroups.permissions.admin_packages_addgroup'] = "Adicionar Grupo";
$lang['StaffGroups.permissions.admin_packages_editgroup'] = "Editar Grupo";
$lang['StaffGroups.permissions.admin_packages_deletegroup'] = "Apagar Grupo";
$lang['StaffGroups.permissions.admin_company_general_edittheme'] = "Editar tema";
$lang['StaffGroups.permissions.admin_company_general_deletetheme'] = "Apagar Tema";
$lang['StaffGroups.permissions.admin_company_billing_addcoupon'] = "Adicionar Cupão";
$lang['StaffGroups.permissions.admin_company_billing_editcoupon'] = "Editar Cupão";
$lang['StaffGroups.permissions.admin_company_billing_deletecoupon'] = "Apagar Cupão";
$lang['StaffGroups.permissions.admin_company_themes'] = "Temas";
$lang['StaffGroups.permissions.admin_company_taxes'] = "Impostos";
$lang['StaffGroups.permissions.admin_company_emails_edittemplate'] = "Editar Template de Email";
$lang['StaffGroups.permissions.admin_company_emails_addsignature'] = "Adicionar Assinatura de Email";
$lang['StaffGroups.permissions.admin_company_emails_deletesignature'] = "Apagar Assinatura de Email";
$lang['StaffGroups.permissions.admin_company_currencies'] = "Moedas";
$lang['StaffGroups.permissions.admin_system_backup'] = "Cópias de Segurança";
$lang['StaffGroups.permissions.admin_system_staff_add'] = "Adicionar pessoal";
$lang['StaffGroups.permissions.admin_system_staff_edit'] = "Editar Staff";
$lang['StaffGroups.permissions.admin_system_staff_status'] = "Status da equipa";
$lang['StaffGroups.permissions.admin_system_staff_editgroup'] = "Editar Grupo de Staff";
$lang['StaffGroups.permissions.admin_company_automation'] = "Automação";
$lang['StaffGroups.permissions.admin_clients_recordpayment'] = "Registar Pagamento";
$lang['StaffGroups.permissions.admin_clients_makepayment'] = "Fazer Pagamento";
$lang['StaffGroups.permissions.admin_reports'] = "Relatórios";
$lang['StaffGroups.permissions.admin_reports_customize'] = "Personalizar relatórios";
?>