<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Staff.!error.user_id.exists'] = "ID de utilizador inválido.";
$lang['Staff.!error.first_name.empty'] = "Por favor introduza o primeiro nome.";
$lang['Staff.!error.email.format'] = "Por favor introduza um endereço de email válido.";
$lang['Staff.!error.status.format'] = "Estado inválido.";
$lang['Staff.!error.staff_id.format'] = "O ID da Equipa tem de ser um número.";
$lang['Staff.!error.uri.empty'] = "Por favor introduza um URI.";
$lang['Staff.!error.title.empty'] = "Por favor introduza um título.";
$lang['Staff.!error.staff_id.exists'] = "ID de Equipa inválido";
?>