<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['SystemRequirements.!error.php.minimum'] = "A versão PHP %1\$s ou superior é necessária. A sua versão: %2\$s."; // %1$s is the minimum version of PHP (i.e. 5.1.3), %2$s is the current version
$lang['SystemRequirements.!warning.imap.recommended'] = "A extensão IMAP é necessária para enviar e receber mensagens via SMTP e IMAP.";
$lang['SystemRequirements.!warning.zlib.recommended'] = "A extensão zlib é altamente recomendada para melhor performance.";
?>