<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Taxes.!error.company_id.exists'] = "ID da empresa inválido.";
$lang['Taxes.!error.level.format'] = "O nível da taxa tem de ser numérico.";
$lang['Taxes.!error.name.length'] = "O nome da taxa não pode exceder os 64 caracteres de cumprimento.";
$lang['Taxes.!error.tax_id.exists'] = "Número de Contribuinte Inválido.";
$lang['Taxes.getTaxStatus.active'] = "Ativo";
$lang['Taxes.getTaxStatus.inactive'] = "Inativo";
$lang['Taxes.getTaxTypes.inclusive'] = "Inclusive";
?>