<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Themes.!error.id.exists'] = "O tema que escolhei não existe.";
$lang['Themes.!error.company_id.exists'] = "ID de empresa inválido.";
$lang['Themes.!error.name.empty'] = "Insira o nome do tema.";
$lang['Themes.!error.type.format'] = "O tipo de tema dado é inválido.";
$lang['Themes.type.admin'] = "Equipa";
$lang['Themes.type.client'] = "Cliente";
?>