<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Transactions.!error.amount.format'] = "A Quantia tem de ser um número.";
$lang['Transactions.!error.type.format'] = "Tipo de transação inválido.";
$lang['Transactions.!error.transaction_type_id.exists'] = "ID de tipo de transação inválido.";
$lang['Transactions.!error.transaction_id.exists'] = "ID de transação inválido.";
$lang['Transactions.!error.date_added.format'] = "A data da transação não pode ser uma data futura.";
$lang['Transactions.!error.invoice_id.exists'] = "ID da fatura invalida.";
$lang['Transactions.!error.date.format'] = "A data aplicada é inválida.";
$lang['Transactions.!error.name.empty'] = "Por favor introduza um nome.";
$lang['Transactions.!error.is_lang.format'] = "is_lang tem de ser um número.";
$lang['Transactions.!error.is_lang.length'] = "O comprimento is_lang não pode exceder 1 caracter.";
$lang['Transactions.types.cc'] = "Cartão de Crédito";
$lang['Transactions.types.ach'] = "ACH";
$lang['Transactions.status.approved'] = "Aprovado";
$lang['Transactions.status.declined'] = "Rejeitado";
$lang['Transactions.status.void'] = "Anulado";
$lang['Transactions.status.error'] = "Erro";
$lang['Transactions.status.pending'] = "Pendente";
$lang['Transactions.status.returned'] = "Devolvido";
$lang['Transactions.!error.currency.missing'] = "Por favor defina uma moeda.";
$lang['Transactions.!error.currency.mismatch'] = "A moeda dada não corresponde a pelo menos uma das faturas associadas.";
$lang['Transactions.debit_types.debit'] = "Débito";
$lang['Transactions.debit_types.credit'] = "Crédito";
?>