<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Users.!error.username.unique'] = "O nome de utilizador já esta a ser utilizado.";
$lang['Users.!error.current_password.matches'] = "Palavra-passe inválida.";
$lang['Users.!error.otp.auth'] = "A password de utilização única é inválida.";
$lang['Users.!error.username.attempts'] = "Demasiadas tentativas de login falhadas detetadas.";
?>