<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['InvoiceDelivery.deliverinvoices.interfax_subject'] = "Fatura #%1\$s"; // %1$s is the invoice number (or the first invoice number in a group of several)
$lang['InvoiceDelivery.deliverinvoices.postalmethods_description'] = "Fatura #%1\$s"; // %1$s is the invoice number (or the first invoice number in a group of several);
?>