<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 4.2.1
 * @copyright Copyright (c) 2018, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['GoGetSSL.!error.gogetssl_name.empty'] = "Por favor introduza um nome de revendedor.";
$lang['GoGetSSL.!error.gogetssl_validity.empty'] = "Por favor introduza um período de validade.";
$lang['GoGetSSL.!error.gogetssl_fqdn.format'] = "Por favor introduza um Domínio válido.";
$lang['GoGetSSL.!error.meta[product].valid'] = "Por favor selecione um produto.";
$lang['GoGetSSL.!error.meta[gogetssl_name].empty'] = "Por favor escolha pelo menos um revendedor.";
$lang['GoGetSSL.!error.api.internal'] = "Ocorreu um erro interno, ou o servidor não respondeu à solicitação.";
$lang['GoGetSSL.please_select'] = "-- Por favor escolha --";
$lang['GoGetSSL.name'] = "GoGetSSL";
$lang['GoGetSSL.module_row'] = "Revendedor GoGetSSL";
$lang['GoGetSSL.module_row_plural'] = "Revendedores";
$lang['GoGetSSL.add_module_row'] = "Adicionar Revendedor";
$lang['GoGetSSL.manage.module_rows_title'] = "Revendedores GoGetSSL";
$lang['GoGetSSL.manage.module_rows.edit'] = "Editar";
$lang['GoGetSSL.manage.module_rows.delete'] = "Apagar";
$lang['GoGetSSL.manage.module_rows.confirm_delete'] = "Tem a certeza de que quer apagar este revendedor?";
$lang['GoGetSSL.manage.module_rows_no_results'] = "Não existem revendedores.";
$lang['GoGetSSL.manage.module_rows_heading.options'] = "Opções";
$lang['GoGetSSL.row_meta.gogetssl_name'] = "Nome do Revendedor";
$lang['GoGetSSL.add_row.box_title'] = "Adicionar Revenda GoGetSSL";
$lang['GoGetSSL.add_row.add_btn'] = "Adicionar Revendedor";
$lang['GoGetSSL.edit_row.box_title'] = "Editar Revendedor GoGetSSL";
$lang['GoGetSSL.edit_row.basic_title'] = "Definições Básicas";
$lang['GoGetSSL.edit_row.add_btn'] = "Atualizar Revendedor";
$lang['GoGetSSL.package_fields.product'] = "Produto";
$lang['GoGetSSL.service_field.gogetssl_csr'] = "Conteúdo do CSR";
$lang['GoGetSSL.service_field.gogetssl_webserver_type'] = "Tipo de Webserver";
$lang['GoGetSSL.service_field.gogetssl_title'] = "Titulo";
$lang['GoGetSSL.service_field.gogetssl_firstname'] = "Primeiro nome";
$lang['GoGetSSL.service_field.gogetssl_lastname'] = "Último nome";
$lang['GoGetSSL.service_field.gogetssl_address1'] = "Linha de Endereço 1";
$lang['GoGetSSL.service_field.gogetssl_city'] = "Cidade";
$lang['GoGetSSL.service_field.gogetssl_zip'] = "Código Postal";
$lang['GoGetSSL.service_field.gogetssl_state'] = "Estado";
$lang['GoGetSSL.service_field.gogetssl_country'] = "País";
$lang['GoGetSSL.service_field.gogetssl_email'] = "Email";
$lang['GoGetSSL.service_field.gogetssl_organization'] = "Organização (introduzir NA se não aplicável)";
$lang['GoGetSSL.service_field.gogetssl_fax'] = "Número de Fax (formato internacional)";
$lang['GoGetSSL.tab_reissue.heading_reissue'] = "Reedição";
?>